### ISSUE TITLE
Danger is broken

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#1004]
Danger doesn't work on external PRs, probably due to the token not being exposed.

![image](https://user-images.githubusercontent.com/1935960/119029135-1f1ca480-b95d-11eb-96df-a7da2871b2c2.png)

**Comment by bruno-garcia** [comment]
I made some PRs and it worked. Was it due to external contributor PR and lack of tokens?

**Comment by lucas-zimerman** [comment]
It used to work with external PRs but it's not able to comment on the given PR https://github.com/danger/danger/issues/1103

**Comment by Tyrrrz** [comment]
What about the `/user` request failing with 403? I'm curious which request does that correspond to.

**Comment by bruno-garcia** [comment]
Last two PRs also didn't get the Danger message:

https://github.com/getsentry/sentry-dotnet/pull/1046

https://github.com/getsentry/sentry-dotnet/pull/1045#issuecomment-855468295

**Comment by Tyrrrz** [comment]
Same errors?

![image](https://user-images.githubusercontent.com/1935960/121067278-b5373400-c77f-11eb-90c5-51b72a4ff59a.png)

I have no idea what to do about it. If no one else has any ideas, I propose to just revert to the previous version.

**Comment by bruno-garcia** [comment]
@Tyrrrz can we write the error message on GitHub Action to the console? So if one peeks at the error to understand what's about, they can see what to do?

Meaning: We can write the message to the PR as a comment, dump as the failure message

**Comment by Tyrrrz** [comment]
@bruno-garcia do you mean wrap the entire thing in try/catch and dump the error to console?

**Comment by bruno-garcia** [comment]
> @bruno-garcia do you mean wrap the entire thing in try/catch and dump the error to console?

That sounds like a solution. Ultimately we want to say: Add this line to the changelog. What' failing is to write a comment to the PR? Then write that as a console message (less user friendly but does the job)

**Comment by Tyrrrz** [comment]
How is it different from this? https://github.com/getsentry/sentry-dotnet/blob/1c04f4c610758e95160b1c8d000951ef5b318275/dangerfile.js#L26-L32

Note that the initial version of dangerfile looked like this:

https://github.com/getsentry/sentry-dotnet/blob/04214d80af1c2be70450cc0c833828bc24ba164e/dangerfile.js

**Comment by bruno-garcia** [comment]
@Tyrrrz What I mean is that I want the message to copy paste into the CHANGELOG instead of: "Add message to changelog"

**Comment by Tyrrrz** [comment]
Ah okay. But that would still not stop the action from failing right? Which is the main concern if I understand correctly.

**Comment by bruno-garcia** [comment]
@Tyrrrz right. But if the user reads the reason for the failure. Copies the message into the changelog and commits. It would pass after that, right? Since it does verify if the changelog entry exists.

**Comment by Tyrrrz** [comment]
No, it will fail regardless because of lack of permissions. In fact, it should already write to the console and shortcircuit if it lacks permissions.

**Comment by Tyrrrz** [comment]
Still broken:

![image](https://user-images.githubusercontent.com/1935960/122462074-fc37dd00-cf68-11eb-98bd-c9a3f677cc9a.png)

Looks like even the original version doesn't work anymore then. I'm out of ideas.

**Comment by bruno-garcia** [comment]
@lucas-zimerman has thoughts?

**Comment by Tyrrrz** [comment]
Closing now as it kinda works with the message still being reported on the console.

**Comment by mattjohnsonpint** [comment]
After #1936, we're seeing this problem again, and it is blocking PRs from external contributors from being merged because required status is never reported.

**Comment by mattjohnsonpint** [comment]
PR #1945 is stuck at:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1396388/191977971-0c6bf823-e4e3-4d4c-94b7-cd9f17370049.png">

**Comment by mattjohnsonpint** [comment]
@vaind is taking a look.

**Comment by vaind** [comment]
I've made some changes to the reused [dangerfile.js](https://github.com/getsentry/github-workflows/commit/c06302f2b755b9199b6b6e70f85e57d06c2f2b7d) so that if it cannot post a comment, it will print annotations and show those in the PR. This, however, didn't fix the issue of not being able to post a status check. Honestly, I don't see how it could have worked with the previous dangerfile that was part of this repo either - I've looked for old PRs that - the most recant one is https://github.com/getsentry/sentry-dotnet/pull/1683 and it doesn't seem to have the Danger status check. 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/6349682/192096203-a2ca09ca-dc69-40a0-be03-78ea5ce87e60.png">

To verify, I've tried rolling back the change in this PR: https://github.com/getsentry/sentry-dotnet/pull/1948 - and it still doesn't post the status check - https://github.com/getsentry/sentry-dotnet/actions/runs/3118212450/jobs/5057345339#step:3:21

One solution could be setting the commit status in another workflow that's running within the head repo - as described here - https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ - but to me, that sounds like too much trouble to be worth it.

Personally, I'd suggest [disabling `Danger` from the Required status checks on this repo](https://docs.gearset.com/en/articles/2437757-managing-status-check-rules-in-github) - this is the first time I see it enabled on Sentry repositories and doesn't seem to be really a great value (as opposed to actual CI test which isn't required to pass...)

**Comment by mattjohnsonpint** [comment]
@bruno-garcia removed the required status check for Danger.  We'll still follow it's suggestions of course, but not block on reporting status.

Thanks @vaind
