### ISSUE TITLE
Remote Code Execution (RCE) vulnerability in System.Text.Encodings.Web@5.0.0

### ISSUE THREAD

**Issue by DominikPalo** [getsentry/sentry-dotnet#1075]
There is a **Remote Code Execution (RCE)** high-severity vulnerability in the **System.Text.Encodings.Web@5.0.0** package (on which the **Sentry.Serilog** package depends). It would be great to update the **System.Text.Json** dependency ASAP to the latest version to get rid of that vulnerability.

### More details:
**Introduced through:**   Sentry.Serilog@3.5.0  ›  Sentry@3.5.0  ›  System.Text.Json@5.0.0  ›  System.Text.Encodings.Web@5.0.0
**Fixed in:** System.Text.Encodings.Web@4.5.1, System.Text.Encodings.Web@4.7.2, System.Text.Encodings.Web@5.0.1
**DB link:** https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267

![image](https://user-images.githubusercontent.com/1623257/123070646-39421a80-d414-11eb-9bff-104c5d2c641b.png)

**Comment by bruno-garcia** [comment]
To clarify the Remote Code Execution flaw exists in `System.Text.Encodings.Web` version 5.0.0 not in Sentry code itself.

It can be mitigated by adding a package reference to your project to `System.Text.Encodings.Web` to any of the versions listed in the issue description.
Alternatively, if adding `System.Text.Json` 5.0.1 directly to your project the issue is also mitigated.

Also this doesn't affect applications using .NET Core 3.x or higher (including .NET 5).

That said, we'll bump the min version of System.Text.Json to 5.0.1 on the SDK itself to make sure users of Sentry don't bring `System.Text.Encodings.Web` 5.0.0 to their apps.
