### ISSUE TITLE
How to truncate Message/Breadcrumbs/Stacktrace if they are too long (RequestEntityTooLarge)?

### ISSUE THREAD

**Issue by Shaddix** [getsentry/sentry-dotnet#1138]
We sometimes face RequestEntityTooLarge error when submitting our exceptions (#957 has a reproduction :)).
This happens because one of Exception.Message, Exception.Stacktrace or Breadcrumb is too big.

Currently such kind of errors are not shown in Sentry at all.

We are ok with truncating the message/breadcrumb/stacktrace to some reasonable length (e.g. 10kb) if they are too long.

How can we implement it?

We can relatively easy truncate breadcrumbs via `options.BeforeBreadcrumb` and recreating a breadcrumb with shortened message.

However, Exception.Message and Exception.Stacktrace do not seem that easy. We can do it via custom `EventProcessor`, but recreating `SentryEvent` is not the same as `Breadcrumb` (there are quite a lot of properties, and I don't think it's a good idea to just copy them over to new event. Moreover, it's easy to miss some property if it's added in Sentry later).
In v.2 of Sentry.Sdk there was an `event.Apply(newEvent)` extension method that copied more or less everything from one event to the other. But as of v.3 this extension method is limited to `Scope` and I can't use it for `SentryEvent`.

Do you have any suggestions, which extension point could I use to do what I'm after?

**Comment by bruno-garcia** [comment]
I don't think Exception.Message can really be a problem.
Other alternative is to change `MaxBreadcrumbs` to a lower value (100 is a lot if each is huge).

As you said, event processor where you can mutate any field like `if (evt.Message.Formatted.Length > xyz); truncate property`.

Since the whole event is mutable, you won't need to recreated anything, just reset the value (Message = Message.Substring(...).

I recommend investigating what integration/part of the code is the culprit of these massive strings and focusing on them. You could have 1 crumb with a large message but if youb have 100 crumbs and all of them are large, combined with other stuff that's sent, it can be an issue.

**Comment by Shaddix** [comment]
you are totally right.

I was thinking that `evt.Exception` is serialized and sent to Sentry (since in JSON the problematic content was under `exception` JSON key).
But turns out, only `evt.SentryExceptions` are sent, which are mutable and could be easily adjusted.

Thanks a lot for the clues!
