### ISSUE TITLE
System.Exception: The semaphore has been disposed.

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [getsentry/sentry-dotnet#1211]
Hello,

During the execution of my production code I get a lot off errors from the client itself. issue cant reproduce in our side,

This is the output of the log.

"stackTrace": "  at System.Threading.SemaphoreSlim.CheckDispose () [0x00013] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at 
		System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at 
		System.Threading.SemaphoreSlim.Release () [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at 
		Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, 
System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler) [0x000a7] in <6eb3c0ec918b4de4a8a187915040d330>:0 ",

**Comment by josh-degraw** [comment]
Hi there! Would you be able to give us any more context around this error? I'm not seeing anything Sentry-specific in that stack trace so it might be tough to repro well enough to fix the issue if it is indeed from the Sentry client.

**Comment by bruno-garcia** [comment]
There's no `Sentry` frame in there so it looks like some `Amazon` SDK issue. Something they register for cancellation with `CancellationTokenSource.Register` and once they invoke the callback, it turns out to throw on a semaphore. Sentry is only capturing this error and letting you know of it.

Also looking at the stacktrace, instead of file names it's a module version id. Is this running Mono AOT? Or some other type of AOT runtime? What version of the SDK and runtime? Sentry should tell you these in the event.

**Comment by sbs-surendhar-kabilan** [comment]
Seems to be issue in sdk thanks for ur response
