### ISSUE TITLE
Xamarin Android: Unhandled exceptions never received in Sentry console

### ISSUE THREAD

**Issue by adamhalesworth** [getsentry/sentry-dotnet#122]
I'm not sure how to configure the new unified Sentry Sdk in order for it to capture unhandled exceptions. I've spent a day attempting to get it to send out unhandled exceptions, but they don't seem to work properly in a Xamarin Android app.

The initialization of Sentry is performed like this:

```cs
SentryClient = SentrySdk.Init(o => {
    o.Dsn = new Dsn(AppConfig.SentryDSN);
    o.Debug = true;
});
```

As per comments in #96 I added:

```cs
AppDomain.CurrentDomain.ProcessExit += (object sender, EventArgs e) => {
    SentryClient.Dispose();
};
```

Then, elsewhere in the Android code (an Activity for example), given the following lines, I get two different results:

```cs
SentrySdk.CaptureException(new Exception("Manually thrown exception")); // this makes it to Sentry.
throw new Exception("Unhandled exception"); // adding this line causes neither exception to make it to Sentry.
```

In the application console, I can see information regarding the event:

```
Info: Capturing event.
Debug: Running processor on exception: Unhandled exception
Debug: Creating SentryStackTrace. isCurrentStackTrace: False.
Debug: Running main event processor on: Event <event-id>
Debug: Event queued up.
Info: Disposing the Hub.
Debug: Disposing SentryClient.
Debug: Disposing BackgroundWorker.
Debug: Event <event-id> in-flight to Sentry. #0 in queue.
Debug: Disposing scope.
Debug: Disposing SentryClient.
```

Randomly (at some point after playing around with various configurations), the Sentry console has received an event with `<unlabeled event>` as its title, and "Discarded invalid value for parameter 'exception'" in the processing errors, but we are unable to determine if this is unhandled or not?

Additionally, if I use `o.DisableAppDomainUnhandledExceptionCapture()` and set up my own exception handler on `AppDomain` these aren't sent either!

Is there anything obvious that I am doing wrong? Based on the documentation I don't think there's much more I should be doing.

**Comment by bruno-garcia** [comment]
@thisdarktao Short answer is: Xamarin is not yet officially supported.

We haven't tested the new SDK with Xamarin yet. It might require a new `BackgroundWorker` or different hooks to handle application crash (like persisting the event (#80) only to be sent when the app restarts or [through a background worker (android)](https://developer.android.com/training/run-background-service/create-service)). Persisting the event is a common way to handle crashes on mobile. It's how [Sentry for iOS](https://github.com/getsentry/sentry-cocoa) and [Sentry for Android](https://github.com/getsentry/sentry-java) do it. This is because often the mobile OS will crash the process before we a chance to push it out to Sentry (and also to avoid losing it in case the user is offline).


> throw new Exception("Unhandled exception"); // adding this line causes neither exception to make it to Sentry.

The reason adding the second line stops making the first exception making to sentry is the following:
An exception that goes unhandled is making Android terminate the process before our internal handler is able to flush the queue:

https://github.com/getsentry/sentry-dotnet/blob/a22e14e22cc8a1ad3f02be1ed06efd6acc834e21/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L36-L39

This behavior seem to be special with Xamarin.Android (perhaps Xamarin.iOS too?) since this hook has been tested with .NET Framework, *Mono* and .NET Core.

We haven't looked into the Xamarin support yet but I can imagine we'd implement a `PersistentBackgroundWorker` or something which would first store the event to _disk_ and only then attempt to send (i.e: after restart).

**Comment by bruno-garcia** [comment]
@thisdarktao I think the answer is here:

> Note: You cannot rely on the AppDomain.UnhandledException event as managed exceptions are never unhandled in MonoDroid; they are always intercepted at the Android/managed boundary within a catch(Exception) block.

[From Xamarin docs](https://developer.xamarin.com/api/event/Android.Runtime.AndroidEnvironment.UnhandledExceptionRaiser/).

Could you please try:

```csharp
AndroidEnvironment.UnhandledExceptionRaiser += (s, e) =>
{
    handle.Dispose();
};
```

**Comment by thisdarktao** [comment]
That's exactly what I'm now trying, give me 20 minutes and I'll test that out.

**Comment by bruno-garcia** [comment]
@thisdarktao I'm online on [this gitter channel](https://gitter.im/getsentry/dotnet) if you'd like to discuss this.

**Comment by knocte** [comment]
> I think the answer is here:

Hey guys, I'm not sure the above assertion might be correct, because I'm using SharpRaven 2.4.0 successfully on Xamarin.Android, using `AppDomain.CurrentDomain.UnhandledException`.

**Comment by thisdarktao** [comment]
@knocte SharpRaven is the old Sentry SDK. It fires Sentry events off immediately as they are created. This new unified SDK queues events and relies on the process being alive long enough to drain the queue.

I was due to work on a persistent storage method so the events don't just disappear but I've not had the time to do so.

**Comment by thisdarktao** [comment]
In my case it didn't.

**Comment by knocte** [comment]
What version of Xamarin.Android are you using?

**Comment by thisdarktao** [comment]
Our project uses Xamarin.Android 9.0. The `AndroidEnvironment` exception handler was incredibly temperamental, around 1 in 10 test exceptions got to Sentry. As @bruno-garcia mentioned above, you cannot rely on `AppDomain.UnhandledException()`. For our use case as well, the SDK needs to persist locally (devices are completely offline while in use).

**Comment by zifeo** [comment]
@bruno-garcia what is the roadmap for that essential piece? According to https://sentry.io/_/tutorials/create-a-5-star-mobile-app-with-xamarin/ Sentry should work with Xamarin however it is currently not.

**Comment by bruno-garcia** [comment]
@zifeo That blog post uses [SharpRaven](http://github.com/getsentry/raven-csharp) which sends the event immediately (as opposed to queuing for submission). Since it doesn't use a background worker thread it would work in some targets where the SDK in this repository doesn't.
Besides that, SharpRaven doesn't persist events to disk so if the device is offline, the event is lost. 
Another limitation is symbolication on iOS, since it's a native target, calling the .NET APIs to get `StackTrace` and `StackFrame` simply don't return what you expect.

A this time Sentry supports Xamarin by offering the [Cocoa SDK for iOS](https://github.com/getsentry/sentry-cocoa) and the [Sentry Android SDK for Android](https://github.com/getsentry/sentry-java). Ideally we'd support Xamarin as we do [React Native](https://github.com/getsentry/react-native-sentry/) but unfortunately that workload isn't planned yet.

**Comment by thisdarktao** [comment]
No movement on this internally then @bruno-garcia?

**Comment by bruno-garcia** [comment]
@thisdarktao Not at the time. A community supported version could be an option.

**Comment by knocte** [comment]
The (old) SharpRaven approach works fine in Xamarin.iOS too right? I don't see any point in Xamarin devs using Sentry.NET then.

**Comment by bruno-garcia** [comment]
SharpRaven doesn't have offline caching like the native iOS/Android SDKs do. So if an app crashes before the event has a chance to sent out or the device is offline, the event is lost. At this point we suggest using the native SDKs.

**Comment by LuckyDucko** [comment]
Is there any update on this?

I would really love to add Sentry into my Xamarin.Forms app, however, it seems that Sentry isn't too focused on this workload in particular.

Now that @bruno-garcia has suggested using the native SDK's, could there be some sort of tutorial, similar to the 'Create a 5 star mobile app with Xamarin' that would provide us with a little guide/start point on how to go about implementing this?

**Comment by Dids** [comment]
Sentry actually works for me in Xamarin.Forms. Only tested on iOS so far, but exceptions are being captured.

**Comment by bruno-garcia** [comment]
Just added to a `Xamarin.Android` app here: https://github.com/getsentry/symbol-collector/blob/dc542e3dfb7b63e4533c4c34d2cd11535c66b490/src/SymbolCollector.Android/MainActivity.cs#L214-L282

**Comment by bruno-garcia** [comment]
Hey folks. I've tested Xamarin with the new alpha and it works. Basically this: https://github.com/getsentry/sentry-dotnet/issues/80#issuecomment-736072508

I'll duplicate the comment here:

> This version has offline caching support: nuget.org/packages/Sentry/3.0.0-alpha.6
> 
> You can enable it by setting a path to CacheDirectoryPath. The SDK will create subfolders to deal with the files coming in.
> 
> I've tried it out with Xamarin and it worked well. So the crash is stored to disk, the app dies often it can't flush out to the network before it dies or it's offline. Then on restart it sends the event.
> 
> If there's a crash on disk from the previous run, by default it blocks Init up to 1 seconds trying to flush it out. So a restart after a crash could be a bit slower for that reason. You can opt-out by setting a TimeSpan.Zero to CacheFlushTimeout.
> 
> This feature exists so that if your app is crashing each time it's launched, events will never be sent to Sentry because it gets killed before the async event submission can happen.
> 
> Be aware that the SDK expects to be using that directory on its own. So if you have multiple instances of your app, you'll need create a subfolder per pid (process id) and deal with it on your own (like on startup check if a previous run had some folder there that needs to be processed).


Let me know if you can give it a try.
