### ISSUE TITLE
Add Pause/Resume session hooks for WPF/WinForms

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#1330]
Something like this: https://stackoverflow.com/questions/5158700/how-to-detect-if-the-current-wpf-window-is-in-the-user-session-foreground

Similar to what Unity does: https://github.com/getsentry/sentry-unity/blob/57f3238393a50d7282b354e89417ad67886835b6/src/Sentry.Unity/Integrations/SessionIntegration.cs#L27

**Comment by mattjohnsonpint** [comment]
Unlike Unity and MAUI, a WPF or WinForms app isn't really ever suspended or resumed, it just may go out of focus (be minimized, etc.). So while we could track those sort of window focus/size-change events, I'm not sure they would add the same sort of value.

Since we already have #512 tracking a possible WinForms package, I'm closing this particular issue.
