### ISSUE TITLE
OperatingSystem no longer from user agent

### ISSUE THREAD

**Issue by mrcarl79** [getsentry/sentry-dotnet#134]
In the old client I'm sure that the OS was picked up and parsed from the user agent, however now it's just the OS of the server.

In Sentry.Protocol.OperatingSystem it says:

/// In web contexts, this is the operating system of the browser (normally pulled from the User-Agent string).

But in sentry-dotnet where it populates this context it takes the server OS.

Is this by design now? is there anyway to override this with the client OS from the user agent? temporarily I'm adding tags with this info but I preferred how it worked previously.

Thanks

**Comment by bruno-garcia** [comment]
@mrcarl79 The docs are correct but at this point only `Javascript` events have the `User-Agent` parsing enabled. We have a issue open to get this fixed so that events from other platforms like .NET and PHP can also take advantage of it.

On `SharpRaven` the reported OS is of the machine running the .NET code, not the `User-Agent`. This is the same in this (new) .NET SDK. The difference here is that the ASP.NET Core integration reports the system OS and runtime as `server-os` and `server-runtime` and no icons are displayed at the top for those. `User-Agent` is correctly reported but at this point, as I mentioned above, it's not being parsed for .NET events.

**Comment by bruno-garcia** [comment]
Since there's nothing to be done on this repo, I'll close this issue.

Please subscribe for changes to: getsentry/sentry#8555 as we'll be updating that one once the parsing is fixed.
