### ISSUE TITLE
Adding a unread ASP.NET stream as attachment breaks sentry

### ISSUE THREAD

**Issue by peterhirn** [getsentry/sentry-dotnet#1369]
### Environment
- Sentry SaaS (sentry.io)
- Google Cloud Function

Which SDK and version?
- Sentry.Google.Cloud.Functions 3.12.0

### Steps to Reproduce
If the request body stream is unread/was never consumed Sentry breaks
```
scope.AddAttachment(context.Request.Body, name)
```

Result
```
Sentry rejected the envelope 8bbe4188e5af44cd819c91cb0c58e34f. Status code: BadRequest. Error detail: invalid event envelope. Error causes: missing newline after header or payload.
```

### Workaround

```fsharp
let drainAndReset (stream: Stream) =
    async {
        try
            let! token = Async.CancellationToken
            do! stream.DrainAsync token |> Async.AwaitTask
            stream.Position <- 0L

            return stream.Length
        with
        | e ->
            logger.LogWarning("Drain error {error}", e.Message)
            return 0L
    }

let logBadRequest (e: exn) (context: HttpContext) =
    async {
        let! length = drainAndReset context.Request.Body

        SentrySdk.WithScope (fun scope ->
            if length > 0L then
                scope.AddAttachment(context.Request.Body, "payload")

            logger.LogError(e, "Bad request {error}", e.Message))
    }
```

**Comment by bruno-garcia** [comment]
Thank you for your explanation about how you resolved this issue.

For reference, solution here: https://github.com/getsentry/sentry-dotnet/issues/1156#issuecomment-985483737

If I understand correct there's nothing for Sentry to fix here. It's all about gotchas with ASP.NET Core Request body buffering and stream positions. I'll close the issue then but feel free to reopen if something needs to be fixed in the Sentry SDK.
