### ISSUE TITLE
Enable Sentry on certain environments

### ISSUE THREAD

**Issue by lHersey** [getsentry/sentry-dotnet#141]
I want to log to Sentry only when the environment is set to **production**, but with this code all exceptions are logged to Sentry in any environment... What am I missing?
```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseSentry(options =>
                {
                    var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

                    if (env == "Production")
                    {
                        options.Dsn = "DNS Key Here";
                        options.Environment = env;
                        options.IncludeRequestPayload = true;
                        options.IncludeActivityData = true;
                    }
                })
                .UseStartup<Startup>();
```

**Exception**

```csharp
        public virtual Task<List<TEntity>> GetAllAsync()
        {
            throw new InvalidOperationException();
            return this.context.Set<TEntity>().ToListAsync();
        }
```
And it was logged...
I tried to implement something similar with a middleware in Configure method on Startup class but with no success.

Thanks in advance!

**Comment by bruno-garcia** [comment]
Do you use `appsettings.json` and appsettings.Production.json`?
It would be simpler to set the `DSN` only on your production configuration file.
Is that an option to you?

**Comment by lHersey** [comment]
Sadly no...

Because I don't want to upload the DNS to my remote repo, I want to manage every secret (DB connection string, Sentry DNS, JWT secret key) with environment variables.

Is there a  way to call UseSentry inside  Startup class (ConfigureServices or Configure)? There I can do something like this

```csharp
if(IHostingEnvironment.IsProduction()) {
         UseSentry();
}
```

Thanks for your help!

**Comment by bruno-garcia** [comment]
@lHersey That's ok. You can set the environment variable, only in production:
`Sentry__Dsn`.

In ASP.NET Core, everything you define via `appsettings.json` can be set via environment variable.
Btw I'm assuming you are using the `DefaultWebHostBuilder` which comes in the ASP.NET Core 2 templates

**Comment by bruno-garcia** [comment]
Besides being able to set anything you would with appsettings.json via env var, Sentry SDK has some environment variables too. 
The one that would help you is: `SENTRY_DSN`.
In this case you can have the standard `UseSentry` code without any `DSN` defined anywhere on what's source controlled and in your prod servers, you can have the `SENTRY_DSN` set. Only then the SDK will be enabled.

**Comment by lHersey** [comment]
I tried to do it but with no success. When I set the  **SENTRY_DSN** on Development the exception is logged. But I did it with this code

```csharp
public static IWebHostBuilder UseSentryOnProduction(this IWebHostBuilder webHostBuilder)
        {
            return webHostBuilder.ConfigureAppConfiguration(RegisterSentryConfig(webHostBuilder));
        }



        private static Action<WebHostBuilderContext, IConfigurationBuilder> RegisterSentryConfig(IWebHostBuilder webHostBuilder)
        {
            return (hostingContext, config) =>
            {
                var env = hostingContext.HostingEnvironment;

                if (env.IsProduction())
                {
                    var sentryKey = hostingContext.Configuration["vidly_SentryKey"];

                    if (String.IsNullOrEmpty(sentryKey)) throw new InvalidOperationException("Error: The 'vidly_SentryKey' environment variable is not set, set this envitonment variable to the sentry dns");

                    webHostBuilder.UseSentry();
                }
            };

        }
```

Then use it like this: 

```csharp
public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseSentryOnProduction()
                .UseStartup<Startup>();
    }
```

Thanks for the help! 👍

**Comment by bruno-garcia** [comment]
I thought you don't want Sentry in Dev but *do* want it in production. Is that correct?
In this case, without any additional code, just leaving no dsn configured anywhere in code or configuration except with the `SENTRY_DSN` environment variable kn production only will achieve that

**Comment by bruno-garcia** [comment]
@DavidMealha This should work. Could we please debug this one?

Could you please set the `Debug` flag to true, like:

```json
"Sentry" : { 
   "Debug": "true" 
}
```

Now the internal SDK logs go to the console and once the logging framework (in ASP.NET Core) bootstraps, it uses that so you'd see the logs in the console and/or text file too if you've setup your logging to do that. 

But since we're looking for SDK initialization, please make sure to run the app on a console (i.e: `dotnet run`) to see the output.

I suspect your issue could be related to this the building intermediate containers raised here: https://github.com/getsentry/sentry-dotnet/issues/103

As a work around, you can use the environment variable: `Sentry__Dsn` instead of `SENTRY_DSN`. This is basically the same as the `appsettings.json`. ASP.NET Core configuration system reads from the `json` configs as well as the environment variables in order to populate the `Options` object. You could also set the debug flag to true via env var: `Sentry__Debug=true`.

**Comment by alesdvorakcz** [comment]
Wouldn't be good to have a configuration option, something like "Enabled": true/false? Or is not setting DSN proper way how to disable sentry in appsettings?

**Comment by bruno-garcia** [comment]
Not setting the `DSN` means the SDK cannot initialize itself. Even if you did call `Init` or `AddSentry`.
For ASP.NET Core and the other integration, such configuration flag exist: [InitializeSdk](https://github.com/getsentry/sentry-dotnet/blob/eef09a0f51c54310916d0e6a7050cc8c2c100afe/src/Sentry.Extensions.Logging/SentryLoggingOptions.cs#L51).
If you set it to false, even if the DSN is available, the integration will not attempt to initialize the SDK.

So unless you call `SentrySdk.Init` yourself, the SDK will be disabled.

**Comment by bruno-garcia** [comment]
@DavidMealha based on that log message, the SDK could not find the `SENTRY_DSN`. I'd check if the env var was correctly set. Maybe try to read the value on ur [app just to test it out: Environment](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netframework-4.7.2).

Could you please provide a repro for the NullPointer? This shouldn't be the case so something to investigate. The error described on #103 is a `ObjectDisposedException` because a container is built and disposed (disposing the SDK) and a new container is created later but the old instance hangs around instead.

**Comment by DavidMealha** [comment]
@bruno-garcia The variable was correctly set, I ended up using the value inside appsettings.json.

I am not sure how to recreate the scenario, since it didn't occurr anymore... It happened when I was using the `SENTRY_DSN` variable. In my `ConfigureServices()` I have a wide range of services (auth, dbcontext, react ssr and application-specific services).

The code from Program.cs and Startup.cs is available here:
https://gist.github.com/DavidMealha/f73c3bf40d3afe7e19f65c49878dfa9f

**Comment by bruno-garcia** [comment]
Seems this issue has been solved. Feel free to reopen otherwise.
