### ISSUE TITLE
Visual Studio 2015 throws "Could not load file or assembly 'System.Net.Http, Version=4.2.0.0" error

### ISSUE THREAD

**Issue by nbhuy89** [getsentry/sentry-dotnet#151]
Hi,

I am using visual studio 2015 with Sentry version 1.1.0, my computer just only install .net framework 4.6.1
When I log information, the sentry dll throws this exception 

Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

at Sentry.Internal.SdkComposer.CreateBackgroundWorker()
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker)
   at Sentry.Internal.Hub..ctor(SentryOptions options)
   at Sentry.SentrySdk.Init(SentryOptions options)

I found out that VS2017 build this package with System.Net.Http with version 4.2.0.0 from 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Http.dll

but in VS2015/.net framework 4.6.1 dont have this dll

You can refer to this question for more detail:
https://stackoverflow.com/questions/47570912/strange-issue-with-system-net-http-4-2-0-0-not-found?rq=1

Any way we can fix this issue?
Thanks,

**Comment by bruno-garcia** [comment]
Microsoft had some problems with SystemNet.Http being distributed via NuGet vs via the .NET Framework installations etc. I'm not sure of details right now but the link you shared has details, for examples, like:

> The problem you're facing is related to Visual Studio, especially 2017 which is shipped with System.Net.Http version 4.2.0.0. However, adopting the new way whereby any references should be done via NuGet, latest version of System.Net.Http which is 4.3.3 contains the dll version 4.1.1.2.

This issue is unrelated with the SDK (which simply offers an assembly targeting `net461` depending on `System.Net.Http`). For that reason there isn't anything we can do in the SDK to help you work around this problem.
