### ISSUE TITLE
intermittent error in CaptureEvent_NonSerializableContextAndOfflineCaching_CapturesEventWithContextKey

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1516]
https://github.com/getsentry/sentry-dotnet/runs/5485978713?check_suite_focus=true#step:6:1235

```
[xUnit.net 00:00:23.71]     NotSentry.Tests.HubTests.CaptureEvent_NonSerializableContextAndOfflineCaching_CapturesEventWithContextKey(offlineCaching: True) [FAIL]
Error: Un-serializable context key should exist
Expected: True
Actual:   False
  Failed NotSentry.Tests.HubTests.CaptureEvent_NonSerializableContextAndOfflineCaching_CapturesEventWithContextKey(offlineCaching: True) [894 ms]
  Error Message:
   Un-serializable context key should exist
Expected: True
Actual:   False
  Stack Trace:
    at NotSentry.Tests.HubTests.CaptureEvent_NonSerializableContextAndOfflineCaching_CapturesEventWithContextKey (System.Boolean offlineCaching) [0x00150] in <f3596d226acd48f8bc36ebc6a5233641>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <e068e2227ab74c1bb3d724ebaab0e3ff>:0 
  ```

**Comment by mattjohnsonpint** [comment]
FWIW, I can't repro this locally.  Been running the test in a loop for awhile now, and it passes every time.  I saw it in CI though, reviewing #1515.  Reran the check jobs and that one passes now (but a different one failed).

**Comment by mattjohnsonpint** [comment]
Appears to be on Mono (net4.6.1 target, Ubuntu and macOS only).

**Comment by mattjohnsonpint** [comment]
I can't prove it's responsible, but I see a hard `.Result` instead of async/await here:

https://github.com/getsentry/sentry-dotnet/blob/b26a2fba91e2d6140444ffd906bef01c2cba8e4a/test/Sentry.Tests/HubTests.cs#L316

I'll fix that and check for any others elswhere.

**Comment by mattjohnsonpint** [comment]
Still happening:

https://github.com/getsentry/sentry-dotnet/runs/5648910180?check_suite_focus=true#step:6:896

**Comment by mattjohnsonpint** [comment]
Still happening:

https://github.com/getsentry/sentry-dotnet/runs/5820960580?check_suite_focus=true#step:6:354

**Comment by mattjohnsonpint** [comment]
At this point, I'm not so sure it's the test that's flaky. It may be indicative to a race condition somewhere in the implementation.

**Comment by lucas-zimerman** [comment]
A long guess but could be similar to one issue spotted during the development of the tracing feature for DiagnosticSource.

https://github.com/getsentry/sentry-dotnet/blob/b26a2fba91e2d6140444ffd906bef01c2cba8e4a/src/Sentry/SentryEvent.cs#L119-L126

The concurrent dictionary/context is being set during the moment you add a new context on those tests, for some reason the data could be lost if inserted right after the dictionary was created IF multiple threads try to access it.

If that's the case, one solution would be setting the context when a new SentryEvent is created

```csharp
        private Contexts? _contexts = new Contexts();

        /// <inheritdoc />
        public Contexts Contexts
        {
            get => _contexts;
            set => _contexts = value;
        }
```

**Comment by mattjohnsonpint** [comment]
That should probably use `Lazy<T>`.

**Comment by mattjohnsonpint** [comment]
Actually perhaps not.  I didn't realize that `Contexts` inherited from `ConcurrentDictionary`.  You would just pre-initialize it as you suggested.  It probably doesn't get much additional benefit from `Lazy<T>`.

It seems there's a lot of places where we use this pattern, which is really not great when thread safety is needed.  Even with pre-initializing the object, since we still have a setter then we can't completely guarantee thread safety.  We could only say it's safe with respect to working with an existing set of contexts - not when supplying a new set.

I'm writing up a new issue about this and will address separately.  Thanks!

**Comment by mattjohnsonpint** [comment]
Welp, the PR with the "fix" just failed this test again, so there's still something else out there.  I'll still push it through, but we still have this flakey test. 😞 

https://github.com/getsentry/sentry-dotnet/runs/5835185437?check_suite_focus=true#step:6:349

**Comment by bruno-garcia** [comment]
To sum up our last investigation pairing:
Fails consistently here:

https://github.com/getsentry/sentry-dotnet/blob/298b105623ede243b85ee67b21ea5c53981b3608/test/Sentry.Tests/HubTests.cs#L355

On any platform or target framework. Fails in both offline caching and without it.

Browsing the code shows that failing to read the value should result in the key not being added at all: https://github.com/getsentry/sentry-dotnet/blob/cb62b94b4ce6edb4c72ddff4a27e2cb11bebee3e/src/Sentry/Protocol/Contexts.cs#L141-L143

Still doesn;t explain why it's flaky but attaching a debugger there could help us understand what's going on.

**Comment by mattjohnsonpint** [comment]
Just to document the latest on this - #1613 changed the caching path to be a new folder every time.  Likely since this test runs for multiple targets, we were stepping on ourselves.

Switching to using our `TempFolder` helper, we found a race condition where the cache worker was still trying to access the temp folder after it was disposed.  Fixed this by doing the test in a try/finally and explicitly disposing the caching transport in the finally - which will shut down the worker before the temp folder gets disposed and deleted.
