### ISSUE TITLE
Align SDK with docs regarding session update for dropped events

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-dotnet#1599]
### Problem Statement

We've updated the docs (https://github.com/getsentry/develop/pull/551) to explain how we would like to handle event filter order, updating of sessions for dropped events and sending of session updates. 

> ### Session update filtering
> 
> Events may be dropped by our filtering mechanisms (sample rate, beforeSend, event processors or ignored exception types). Only events dropped due to sampling should update the session despite being dropped as we assume the event was dropped to save quota but would have been something the developer cares about. Events dropped due to other reasons should not update the session as we assume they are more likely to be dropped because the developer chooses to ignore them.
> 
> #### Filter order
> 
> The python SDK shall serve as a reference here. The order for filtering error events is:
> 1. Check for ignored exception types (a.k.a `ignore_errors`)
> 3. Apply scoped `event_processor` (a.k.a `error_processor`)
> 4. Apply global `event_processor`
> 2. Apply `before_send`
> 5. Update the session if an event made it this far
> 6. Apply sampling rate
> 
> #### Sending the session update
> 
> If the event has been dropped and the session updated, the session update should be sent to the server without the event in case the session changed from healthy to errored or from any state to crashed for user attended sessions.

We should check if we're aligned and adapt if necessary. Here's the issue from the Java SDK where all of this started: https://github.com/getsentry/sentry-java/issues/1916

### Solution Brainstorm

See https://github.com/getsentry/develop/pull/551

**Comment by mattjohnsonpint** [comment]
https://develop.sentry.dev/sdk/sessions/#filter-order

**Comment by mattjohnsonpint** [comment]
What this really needs to check is that in all paths, if an unhandled exception causes the session to become unhealthy, that we always update the session.  If, for example, we set `SentryOptions.SampleRate = 0.0001` and the sessions was unhealthy, we'd still want to send a session update.

**Comment by mattjohnsonpint** [comment]
https://develop.sentry.dev/sdk/sessions/#session-update-filtering

https://develop.sentry.dev/sdk/sessions/#filter-order

**Comment by jamescrosswell** [comment]
Most this happens in [`SentryClient.DoSendEvent` in the .NET SDK](https://github.com/getsentry/sentry-dotnet/blob/d6d531cb7d3699f7c4f1f7225433928fbcdab00d/src/Sentry/SentryClient.cs#L212). 

We don't currently do things in the same order as Python then. 

### Python Order
> 1. Check for ignored exception types (a.k.a `ignore_errors`)
> 3. Apply scoped `event_processor` (a.k.a `error_processor`)
> 4. Apply global `event_processor`
> 2. Apply `before_send`
> 5. Update the session if an event made it this far
> 6. Apply sampling rate

### Current order in .NET:
2.  Apply sampling rate
3. Check for ignored exception types (a.k.a ignore_errors) - ApplyExceptionFilters in .NET
4. Apply scoped event_processor (a.k.a error_processor)
5. Apply global event_processor
6. Apply before_send
**_Update the session if an event made it this far ???_**

### Questions

I'm not sure what is meant by "Update the session if an event made it this far" in the issue description. 

In .NET, if an event has an error then we can end the session or increment the error count in [`Hub.CaptureEventInternal`](https://github.com/getsentry/sentry-dotnet/blob/d6d531cb7d3699f7c4f1f7225433928fbcdab00d/src/Sentry/Internal/Hub.cs#L354C1-L366C14), just before `SentryClient.DoSendEvent` gets called:
```csharp
var hasTerminalException = evt.HasTerminalException();
if (hasTerminalException)
{
    // Event contains a terminal exception -> end session as crashed
    _options.LogDebug("Ending session as Crashed, due to unhandled exception.");
    actualScope.SessionUpdate = _sessionManager.EndSession(SessionEndStatus.Crashed);
}
else if (evt.HasException())
{
    // Event contains a non-terminal exception -> report error
    // (this might return null if the session has already reported errors before)
    actualScope.SessionUpdate = _sessionManager.ReportError();
}
```

Is that **_"updating the session"_**? I'm not sure. 

The `SessionUpdate` created above gets included in the `Envelope` along with the `Event` when the `Event` gets sent [after all of the other stuff in `SentryClient.DoSendEvent`](https://github.com/getsentry/sentry-dotnet/blob/d6d531cb7d3699f7c4f1f7225433928fbcdab00d/src/Sentry/SentryClient.cs#L290)... so that's when it gets sent to Sentry. Is that **_"updating the session"_**?

@bruno-garcia or @bitsandfoxes it would be good to get your steer here. I can then update our code accordingly. 

btw: Do we want unit tests for this one?
