### ISSUE TITLE
Extend Sentry.Protocol.User

### ISSUE THREAD

**Issue by wuh95** [getsentry/sentry-dotnet#161]
I'm using the IUserFactory in an .net core project to manually set the informations send about the user. Now I want to send some extra infos, e.g. a sessionId. I know, that i can display this in the 'Additional Data'-section with the .SetExtra method, but I want to show it under 'User'. Is there a way to extend the Sentry.Protocol.User class to show custom data in Sentry?

**Comment by bruno-garcia** [comment]
You could you give a try in creating a `class MyUser : User` and in this class add the desired properties?
Make sure it's serializable as it'll be serialized and sent to Sentry.

**Comment by wuh95** [comment]
I already tried it like this:
`  [DataContract]
    public class UserWithSessionId : User
    {
        [DataMember(Name = "sessionId", EmitDefaultValue = false)]
        public string SessionId { get; set; }
    }`
The event still makes it to Sentry, but the sessionId is lost in the progress. I looked into the code of Sentry.Protocol and it seems like there is an internal CopyTo-method inside the User, wich is called before sending it. In this method the properties Email, Id, Username and IpAddress are set explicit. So I'm not sure if this is not supported or if I'm making mistake.

**Comment by bruno-garcia** [comment]
`CopyTo` is called when applying the scope into an event. So that's right if `IUserFactory` is setting the value into the Scope, it'll be lost when copied over to the Event:

https://github.com/getsentry/sentry-dotnet/blob/a9495f4e62e24092937e27c5257749778b23769f/src/Sentry.AspNetCore/ScopeExtensions.cs#L36

If you set that directory to the event as in:

`CaptureEvent(new SentryEvent { User = new UserWithSession() });` then it should work.

But fair enough. The requirement is to add additional user related data into the `User` object which is done via all this piping in the SDK and ASP.NET Core integration and DI, Scope etc.

In Rust for example we have a Dictionary called `Other`:
https://docs.rs/sentry/0.13.0/sentry/protocol/struct.User.html#structfield.other

I suggest we implement the same in the `Sentry.Protocol` package.

**Comment by wuh95** [comment]
Thanks for the quick help, PR is open :)

**Comment by bruno-garcia** [comment]
This has been release on Protocol [1.0.4](https://github.com/getsentry/sentry-dotnet-protocol/releases/tag/1.0.4)
