### ISSUE TITLE
Custom TracesSampler ignores sampling decision from sentry-trace header

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#1681]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

6.0.0

### OS

Any

### SDK Version

3.17.1

### Steps to Reproduce

Set up an ASP.NET Core application, include `.UseSentryTracing()`, and add a custom `TracesSampler`:

```csharp
webBuilder.UseSentry(o =>
{
    o.TracesSampler = ctx =>
    {
        return 1;
    }
})
```

Run it, make a request using Postman (or similar tool), and include the [`sentry-trace`](https://develop.sentry.dev/sdk/performance/#header-sentry-trace) HTTP request header:
```
sentry-trace: 00000000000000000000000000000000-0000000000000000-0
```

The `-0` at the end indicates the transaction should not be sampled.

### Expected Result

The transaction should not be sent to Sentry.

### Actual Result

The transaction is sent to Sentry anyway, because the `TracesSampler` return value overrides the value in the `sentry-trace` header.

**Comment by mattjohnsonpint** [comment]
A workaround is to do this inside the `TracesSampler`:

```csharp
if (ctx.TransactionContext.IsParentSampled is false)
{
    return 0;
}
```

The question is whether this is the desired behavior, or if it should be done internally such that the `TracesSampler` doesn't get invoked if the `sentry-trace` header has already said not to sample.

**Comment by mattjohnsonpint** [comment]
Hmmm...  I just re-read the remarks on both settings and now I'm not so sure...

https://github.com/getsentry/sentry-dotnet/blob/eccc2336327408cf655774251b4a56ee9af3d1c2/src/Sentry/SentryOptions.cs#L473-L478

https://github.com/getsentry/sentry-dotnet/blob/eccc2336327408cf655774251b4a56ee9af3d1c2/src/Sentry/SentryOptions.cs#L496-L503

Together, they make it sound like the order of precedence was intended to be as it is, which is:
1. `TracesSampler`
2. Sampled flag in `sentry-trace` header
3. `TracesSampleRate`

That feels wrong though.  I would think it should be:
1. Sampled flag in `sentry-trace` header
2. `TracesSampler`
3. `TracesSampleRate`

(In both cases, first one to make a decision wins)

@bruno-garcia - your thoughts on this?

**Comment by bruno-garcia** [comment]
The background story on why the sampler callback always runs (even if the sentry-trace has a sampled transaction) is that otherwise there's no way for a backend to control the volume if it gets overwhelmed by incoming transactions initiated by a front end.
That said, I agree it's a pitfall, and the only thing done, to my knowledge, to hedge the risk of users falling into this issue, was to add to our docs in all sample code snippets that users should peek into the parent sampling decision if they care about that, examples:

* .NET: https://docs.sentry.io/platforms/dotnet/configuration/sampling/#setting-a-sampling-function
* Java: https://docs.sentry.io/platforms/java/configuration/sampling/#setting-a-sampling-function

**Comment by mattjohnsonpint** [comment]
OK. Then nothing to do here. Closing as works as designed.  Thanka for the clarity.
