### ISSUE TITLE
Consider a API to add custom json converters

### ISSUE THREAD

**Issue by SimonCropp** [getsentry/sentry-dotnet#1736]
split from https://github.com/getsentry/sentry-dotnet/issues/1735

**Comment by lucaswalter** [comment]
Would appreciate this option greatly for our application.

**Comment by mattjohnsonpint** [comment]
@lucaswalter - I agree that it would be useful, but we also have a lot going on at the moment.  An example use case would help us reassess priority.  Thanks.

**Comment by mattjohnsonpint** [comment]
Actually, this was pretty small when I looked into it, so I've added a PR for it.  Look for it in the next release.

**Comment by Cooksauce** [comment]
@mattjohnsonpint Appreciate the quick add!

The major use cases for us are:
1. BCL types which are not handled well by default in STJ - `System.Numerics.BigInteger` being the major one)
  a. This type is central to us in the blockchain industry where 256 bit integers are common
2. Any (custom) types with custom converters


In either of these cases, Sentry becomes useless in capturing data of those types (_via `Exception.Data` for example_) because it cannot serialize the type correctly.

Here's an example of a `BigInteger` captured by the SDK:
![image](https://user-images.githubusercontent.com/31948306/191072326-4c910c7b-9190-4870-b223-3e061f243809.png)
