### ISSUE TITLE
Exceptions on background thread are not handled and reported correctly

### ISSUE THREAD

**Issue by DrummerB** [getsentry/sentry-dotnet#1772]
### Environment

**How do you use Sentry?**
sentry.io

**Which version of the SDK?**
0.20.1

**How did you install the package?**
UPM, git-url

**Which version of Unity?**
2021.3.6f1 LTS

**Is this happening in Unity (editor) or on a player like Android, iOS, Windows?**
Reproduced in Windows Editor and Windows Player

### Steps to Reproduce

1. Create a new empty Unity project.
2. Import sentry-unity 0.20.1 in UPM.
3. Attach the code below to a GameObject
4. Start the game
5. Throw some exceptions in a background thread (click the in-game button).

### Expected Result

Exceptions are reported as events to sentry.io

### Actual Result

Only the first exception is handled and reported correctly.

Something seems to go wrong within the SDK, because after the first exception, subsequent exceptions do not result in any debug logs from Sentry, except a single "Sentry: (Info) Disposing the Hub", which is directly followed by:

> exception inside UnhandledException handler: (null) assembly:C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\MonoBleedingEdge\lib\mono\unityjit-win32\mscorlib.dll type:Exception member:(null)

### Code

```csharp
using System;
using System.Threading;
using UnityEngine;

public class SentryTest : MonoBehaviour
{
	void OnGUI()
	{
		if (GUILayout.Button("Throw Exception On Background Thread"))
		{
			Debug.Log("Pressed button");
			var thread = new Thread(() =>
			{
				Thread.Sleep(1000);
				Debug.Log("Will throw exception");
				throw new Exception("Testing Background Thread Crash 2");
			});
			thread.Start();	
		}
	}
}
```

### Any logs or screenshots

[editor-log.txt](https://github.com/getsentry/sentry-unity/files/9079766/editor-log.txt)

**Comment by bruno-garcia** [comment]
This makes sense in .NET in general since once we return the process crashes, so we flush in there. I believe Hub.Dispose was changed to only flush. If not, maybe that's the fix

**Comment by bruno-garcia** [comment]
from the PoV of Unity, this is a p0

**Comment by vaind** [comment]
> .NET in general since once we return the process crashes, so we flush in there.

Checking if that's the case - this indicates it's not - https://stackoverflow.com/a/6465586/2386130

**Comment by vaind** [comment]
In the end, whether it crashes or not on the given platform doesn't matter. If we think back about what this code is trying to achieve:

https://github.com/getsentry/sentry-dotnet/blob/ab296646ead27298a8cdd567663567b93ec69755/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L28-L41

the point isn't disposing of the hub (thus effectively disabling it, because of line 392):

https://github.com/getsentry/sentry-dotnet/blob/ab296646ead27298a8cdd567663567b93ec69755/src/Sentry/Internal/Hub.cs#L387-L399

- what we really want to do is is flushing the just created event so that it's not lost **if** the app crashes.

My suggestion is to change the code so that it doesn't dispose of the, but instead flushes events. There are a few non-breaking changes we can do to achieve this. E. g. we can add an internal method to the Hub: `FlushSync()`.

**Comment by bruno-garcia** [comment]
> > .NET in general since once we return the process crashes, so we flush in there.
> 
> Checking if that's the case - this indicates it's not - [stackoverflow.com/a/6465586/2386130](https://stackoverflow.com/a/6465586/2386130)

We don't support .NET Framework 1.0 through 2.0. In the versions we support, unless you change `args.Handled=true` (granted, this could be done after we run our code if they subscribed to the event after us), the app will terminte.

**Comment by mattjohnsonpint** [comment]
So, if in the `AppDomainUnhandledExceptionIntegration`, we don't dispose the hub but just *flush* it, then we should be ok here, right?

**Comment by bruno-garcia** [comment]
Thanks for the fix @mattjohnsonpint 
@DrummerB we'll make a release of the Unity sdk with this fix soon

**Comment by DrummerB** [comment]
Great, thanks for the fix!
