### ISSUE TITLE
SentrySdk.Init fails with System.Reflection.MissingMetadataException in release mode

### ISSUE THREAD

**Issue by epaezrubio** [getsentry/sentry-dotnet#2029]
### Package

Sentry

### .NET Flavor

.NET Core

### .NET Version

6.0.0

### OS

Windows

### SDK Version

3.23.1 (latest)

### Steps to Reproduce

1. Create an UWP app and initialize the sentry SDK as specified in the [documentation](https://docs.sentry.io/platforms/dotnet/guides/uwp/)
2. Run the app in Release mode

### Expected Result

No crashes

### Actual Result

An exception is thrown at Sentry.dll!Sentry.SentrySdk.InitHub(Sentry.SentryOptions options) Line 62

```
System.Reflection.MissingMetadataException
  HResult=0x80131543
  Message=This operation cannot be carried out because metadata for the following object was removed for performance reasons:\n\n  EETypeRva:0x00050780\n\nNo further information is available. Rebuild in debug mode for better information.\n\n
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

If the application is run in Debug mode, this error is not triggered.

**Comment by mattjohnsonpint** [comment]
Hi.  I tried and was unable to reproduce the issue on a new UWP app.  (I did notice our UWP docs need a few minor updates though, so thanks for that!)

Here's some more details I found that will help you troubleshoot the problem in your own app:

https://learn.microsoft.com/windows/uwp/dotnet-native/missingmetadataexception-class-net-native#usage-details

https://learn.microsoft.com/en-us/answers/questions/42607/missingmetadataexception-cant-seem-to-figure-out-w.html

In particular, the `EETypeRva` message appears to be hiding the actual type that is failing.  You can get the actual name of the missing method or type if you switch back to Debug configuration, and then compile under .NET Native (project properties, Build tab, "Compile with .NET Native tool chain" checkbox).

Please try that and see if you get a more informative error message.  If it turns out to be a Sentry class, please paste the new error here and I'll re-open the issue.

Thanks.

**Comment by mattjohnsonpint** [comment]
FYI, I updated our UWP docs.
https://docs.sentry.io/platforms/dotnet/guides/uwp/

The main update is that it's probably a good idea to flush in `OnSuspending`.  See https://learn.microsoft.com/windows/uwp/launch-resume/app-lifecycle

Please let me know though about your error, after you try in debug+native mode.  Thanks.

**Comment by epaezrubio** [comment]
Thank you for your quick response. I was unaware of the "Compile with .NET Native tool chain" flag.

In case it may help anybody, I used the [Runtime Directive builder tool](https://dotnet.github.io/native/troubleshooter/type.html) in order to generate the following `Default.rd.xml`:

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Namespace Name="Sentry" Serialize="Required All" />
  </Application>
</Directives>
```

This fixed the problem.

PS: Thank you also for the update regarding `OnSuspending` too, I adapted on my side too :)

**Comment by mattjohnsonpint** [comment]
Good to know that you found a solution.  Could you please also let me know what the error changed to after debugging with native mode on?  I'd like to know which type or method it was failing on for you.  Thanks.

**Comment by epaezrubio** [comment]
The missing metadata was related to `Sentry.Integrations.AutoSessionTrackingIntegration`. Is that what you're looking for?

**Comment by mattjohnsonpint** [comment]
Interestingly, I still don't get the exception you did - even with `AutoSessionTracking = true` in the options.  Can you please share the other sentry options you have set? (except the DSN)

Thanks.

**Comment by mattjohnsonpint** [comment]
This came up on another project of mine, and the culprit was `System.Text.Json`.  Sentry uses that as well, so it's possible that adding `System.Text.Json` to the runtime directives would help here also.  See https://github.com/mattjohnsonpint/TimeZoneNames/issues/92

**Comment by bitsandfoxes** [comment]
The SDK currently does not have any dependencies outside of itself when targeting .NET6 or newer. I'm closing this as stale. Please feel free to reply or reopen if the issue persists for you.
