### ISSUE TITLE
Breadcrumbs added inconsistently for start/end of session

### ISSUE THREAD

**Issue by Ruekov** [getsentry/sentry-dotnet#2046]
### Package

Sentry

### .NET Flavor

.NET Core

### .NET Version

6.0.11

### OS

Windows

### SDK Version

3.23.1

### Steps to Reproduce

In a winfoms project, at Main():
1.- Initialize Sentry
2.- Call method SentrySdk.StartSession();
3.- Call winforms methods (Application.Run(new Form()), etc.)
4.- Within this Form, some info/warning/exception is catched and sent to sentry
5.- After them, (Form() Closed) call method SentrySdk.EndSession();

### Expected Result

Show info/exception/message inside a session

### Actual Result

![image](https://user-images.githubusercontent.com/537713/201647271-87e8ebd3-7dc5-41de-920b-302be20592d8.png)
![image](https://user-images.githubusercontent.com/537713/201649202-6abfc087-db4a-4d39-9582-52f5862d02cf.png)

**Comment by mattjohnsonpint** [comment]
In general, the exception or message that is the event is always shown last in the breadcrumbs list, with the breadcrumbs leading up to it before it.

However, I would expect to see the session start before it ends.  Perhaps that's just due to them happening so close together - I'm not sure.  We'll investigate.  Thanks.

**Comment by mattjohnsonpint** [comment]
@Ruekov - Sorry for the delay on this.  Question - are you by chance setting `AutoSessionTracking = true` in your Sentry options and _also_ using `StartSession` / `EndSession` methods?  That would explain the outcome you described - as the automatically-created session would be ended when you start a new session manually.  Generally, one should _either_ start/session manually, or use `AutoSessionTracking`, but not both.

**Comment by Ruekov** [comment]
> @Ruekov - Sorry for the delay on this. 

Hi @mattjohnsonpint, better late than never :) 

Also sorry for the delay, I was out of scope, I needed to remember what I and my coworkers have done to with this issue.


All scenarios I tested:

- With AutoSessionTracking = true and without StartSession/EndSession (not session data sent!)
![image](https://user-images.githubusercontent.com/537713/233684691-8e359057-5fd0-439f-9ee1-f0f87ad5a916.png)
- Without defining AutoSessionTracking and StartSession/EndSession
![image](https://user-images.githubusercontent.com/537713/233682590-f5583267-cd1d-42d0-8d51-ab8ff3e622f6.png)
- With AutoSessionTracking = false and StartSession/EndSession
![image](https://user-images.githubusercontent.com/537713/233682915-fdefb1df-2239-4bf5-927d-c61cb0eded5c.png)
- With AutoSessionTracking = true and StartSession/EndSession (we saw this was the only way to send the ended session breadcrumb)
![image](https://user-images.githubusercontent.com/537713/233683306-7a665d50-6f4c-4d48-9de9-2bfb8c14591a.png)

Also we saw the metrics related (_Crash Free Sessions_ and _Crash Free Users_) were affected by this. If you need anything like the code used or any log from sentry like event json feel free to ask!

Thanks,

**Comment by Ruekov** [comment]
(Sorry... I pushed the wrong button 😅)

**Comment by mattjohnsonpint** [comment]
Your results align with assumption.  The issue here is with the way that session start/end breadcrumbs are being added, not with how the session actually starts/ends.  The only purpose of the session is for release health (crash free sessions, etc.)  TBH, I'm not sure if there should be any breadcrumbs created for it or not.  I'll have to check.

I agree that we should either be sure that start/end session breadcrumbs are always presented in pairs, or that they're completely removed.  One without the other, or in the wrong sequence, are confusing.  Manual vs automatic shouldn't matter with regard to this point.

Still, you should only use _either_ `AutoSessionTracking=true`, or manual `StartSession`/`EndSession`.  Not both.  Using both is creating two sessions where there should only be one.

**Comment by mattjohnsonpint** [comment]
We'll remove breadcrumbs created related to session start/pause/resume/end events in the next release.  Hopefully that clears up some confusion.  Thanks.

**Comment by mattjohnsonpint** [comment]
To clarify, the behavior of _sessions_ hasn't changed.  Only the extra breadcrumbs it adds have been removed.

The advice about setting either `AutoSessionTracking=true` _or_ starting/ending sessions manually still applies.  Do one or the other, but not both.   Doing both basically is creating two sessions when there really should have been only one.
