### ISSUE TITLE
Handle silent failures / proxy?

### ISSUE THREAD

**Issue by njbmartin** [getsentry/sentry-dotnet#225]
Took me a good few hours last night to work out why sentry wasn't getting any errors, and then found it was the corporate proxy that was blocking it after sniffing with Wireshark.

Setting `SentryOptions.Debug=true` didn't help, and was thinking it might actually be useful if you could set Sentry to throw an error if it fails.

I tried using the `SentryOptions.HttpProxy` option, but couldn't get it working. What worked for me was adding the following to `web.config`:

```xml
  <system.net>
    <defaultProxy useDefaultCredentials="true">
      <proxy usesystemdefault="True"/>
    </defaultProxy>
  </system.net>
```

**Comment by bruno-garcia** [comment]
The SDK does log the outcome of a request to Sentry. If you simply opt in for `Debug=true`, you should see the error and the response from Sentry. 

https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry/Internal/Http/HttpTransport.cs#L58-L64

Since you had an issue with proxy it's possible .NET's `HttpClient` simply threw an exception. In which case we'd be logging here: 

https://github.com/getsentry/sentry-dotnet/blob/f516b2f7f24fef391d4bf74ebb150fa103f0c817/src/Sentry/Internal/Hub.cs#L107-L113

In any case, you should see the error in the console.
When you set the proxy manually, did you consider authentication? With that `xml` configuration you are using the process identity and the system proxy. This is also possible to do via code with `SentryOptions.HttpProxy`.

The `xml` config you showed is a .NET Framework way to set proxy to `WebRequest`/`HttpClient` in .NET processes, and it's unrelated to Sentry's SDK. 

Glad you got your project to work with Sentry. Feel free to reopen if something is unclear.
