### ISSUE TITLE
Transactions and Failed requests aren't captured when making synchronous Http requests

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2335]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

6.0.0

### OS

Any (not platform specific)

### SDK Version

3.30.0

### Steps to Reproduce

- Initialise Sentry
- Create an `HttpClient` using the `SentryHttpMessageHandler`
- Make a synchronous request using `HttpClient.Send`

### Expected Result

Sentry should track things like transactions and capture failed requests

### Actual Result

Transactions and failed requests are not tracked

**Comment by mattjohnsonpint** [comment]
Great catch. Synchronous `HttpClient.Send` was added in .NET 5.0.  We should add a synchronous path to `SentryHttpMessageHandler` using `#if NET5_0_OR_GREATER`

**Comment by mattjohnsonpint** [comment]
Also, it's worse than just not tracking, because of:

https://github.com/getsentry/sentry-dotnet/blob/93c5fa8900b29a6a037ff3b285546b64b173f9f2/src/Sentry/SentryHttpMessageHandler.cs#L63

This is currently being done in `SendAsync`.  It should actually be done in the constructors that don't take an `innerHandler` parameter.

Currently, if you don't pass an `innerHandler`, and you use `Send` instead of `SendAsync`, you'll get:

```
Unhandled exception. System.InvalidOperationException: The inner handler has not been assigned.
```

**Comment by mattjohnsonpint** [comment]
Actually, I was mistaken.  Apparently the rules are more complicated, due to `HttpMessageHandlerBuilder` / `IHttpMessageHandlerBuilderFilter` - which is used in conjunction with `HttpClientFactory`.  It explicitly prohibits (and will throw) if you have `InnerHandler` set to a non-null value during construction - because it is taking responsibility for wiring up the inner handlers.

The approach of assigning a default during `SendAsync` (or `Send`) is fine though, because if it's used with the builder pattern, it will already have been set as not-null (to either another delegating handler, or to the primary handler).

Thus the only problem is that we're missing it on the synchronous `Send` method.
