### ISSUE TITLE
Debug meta info not sent when using `PublishSingleFile=true`

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2362]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

7.0.2013

### OS

Any (not platform specific)

### SDK Version

3.31.0

### Steps to Reproduce

Create a simple console app:

```csharp
using Sentry;

SentrySdk.Init(options =>
{
    options.Dsn = "...";
    options.Debug = true;
});

try
{
    throw new Exception("Test");
}
catch (Exception exception)
{
    SentrySdk.CaptureException(exception);
}
```

In the csproj, configure to upload symbols and sources to Sentry (and authenticate with `sentry-cli login`).
```xml
<PropertyGroup>
    <SentryOrg>...</SentryOrg>
    <SentryProject>...</SentryProject>
    <SentryUploadSymbols>true</SentryUploadSymbols>
    <SentryUploadSources>true</SentryUploadSources>
</PropertyGroup>
```

Compile and publish with:
```
dotnet publish -c Release -p:PublishSingleFile=true
```

Run the app from its published folder:
```
./bin/Release/net7.0/osx-arm64/publish/MyConsoleApp
```

### Expected Result

The event generated and shown in the console debug output should contain a `debug_meta` section, including the `debug_id`.

In Sentry, the source context should be visible, and the debug images section should show the symbols were found.

### Actual Result

The event is missing the `debug_meta` section when `-p:PublishSingleFile=true` is used.  Thus, source context is not shown.

Line numbers will still be shown if the `.pdb` file is present (which it is by default in the `publish` folder), but if you delete it - or ship the executable app without the pdb file, then client-side symbolication won't occur.  Server-side symbolication also won't occur because the `debug_meta` section is missing from the event.

**Comment by mattjohnsonpint** [comment]
The code that resolves the assembly debug information is here:

https://github.com/getsentry/sentry-dotnet/blob/00299c7a950f7229b31153db5cff82001527b0d7/src/Sentry/Internal/DebugStackTrace.cs#L413-L422

https://github.com/getsentry/sentry-dotnet/blob/00299c7a950f7229b31153db5cff82001527b0d7/src/Sentry/Internal/DebugStackTrace.cs#L380-L388

I presume that we're not able to read the assembly directly from a file when that file is a single-file-executable.  We need to figure out how to get a `PEReader` in that environment.

If necessary, we can make another `AssemblyReader` implementation, similar to `AndroidAssemblyReader` - but it also might be possible just to do this directly in `TryReadAssembly`.

**Comment by mattjohnsonpint** [comment]
Note from: https://learn.microsoft.com/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility

>  `Module.FullyQualifiedName` - Returns a string with the value of `<Unknown>` or throws an exception.

Thus, we'll need to figure out first how to get something more usable directly from the `Module` passed in to `GetDebugImage`.

**Comment by jamescrosswell** [comment]
I'm getting slightly different behaviour than what's described in the issue details. When I run:

```bash
dotnet publish -c Release -p:PublishSingleFile=true
```

...the build does not succeed and there is nothing in `./bin/Release/` that could be run.

I get aproximately 10 separate errors from the compiler, all of which are instances of the following 3 errors:

```
error IL3002: Using member 'System.Reflection.Module.Name' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. Returns <Unknown> for modules with no file path.
error IL3002: Using member 'System.Reflection.Module.FullyQualifiedName' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. Returns <Unknown> for modules with no file path.
error IL3000: 'System.Reflection.Assembly.Location' always returns an empty string for assemblies embedded in a single-file app. If the path to the app directory is needed, consider calling 'System.AppContext.BaseDirectory'.
```

Some of those errors come from `Ben.Demystifier/TypeNameHelper.cs`, `Ben.Demystifier/ResolvedParameter.cs` and `Ben.Demystifier/Internal/PortablePdbReader.cs`. 

Others come from `Sentry/PlatformAbstractions/RuntimeInfo.cs`. 

Finally some come from `Sentry/Internal/DebugStackTrace.cs`.

So it seems we'd need to leverage alternatives to those methods in multiple places in our codebase to fix this. 

Will do a bit more digging...

**Comment by mattjohnsonpint** [comment]
Interesting.  The errors make sense, but I wonder why I didn't get them and you did.  But anyway, they make sense.

Great find on `AssemblyExtensions.TryGetRawMetadata`.  That sounds super promising.  In theory, that approach could relieve us from needing to read the assembly from the file in _all_ cases.  Please explore that a bit.  Thanks.

**Comment by mattjohnsonpint** [comment]
... though looking closer, I can't tell whether the values we need are actually in that metadata.  One can get a `MetadataReader` from a `PEReader`, but not the opposite direction - so unless the `PEHeader`, `CoffHeader`, and `DebugDirectoryEntries` are available in the metadata somewhere I'm not seeing, then I don't think that will work.

**Comment by jamescrosswell** [comment]
Yeah I don't think everything is in there. 
- We can definitely get the `ModuleName` from the RawMetadata. 
- RawMetadata doesn't help us out for `Module.FullyQualifiedName` though... we could try to build our own version of that (most of it is in the `AssemblyName` that gets returned from `Assembly.GetName()`) 
- The really tricky ones are the references to `System.Reflection.Assembly.Location`. 
  - One is used to [infer the version of the dotnet runtime](https://github.com/dotnet/BenchmarkDotNet/issues/448#issuecomment-308424100)
  - The other is used in the `PortablePdbReader` to get a `MetadataReader` - that one I think is the crux of it all.

There are a bunch of things in the Ben.Demystifier as well, that won't work properly when things are embedded in a single-file app. 

I did work out why I was getting a bunch of errors and you weren't btw... once again, due to a combination of naivety and stupidity. In this particular case, it's actually helped out as the compiler has identified a bunch of issues that would have been pretty hard to track down otherwise.

**Comment by jamescrosswell** [comment]
Possibly some more progress. ILSpy can open self-contained executables... and ILSpy is open source. 

The entry point to the relevant parts of their code, I believe, is the [`AssemblyTreeNode.LoadChildren()`](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ILSpy/TreeNodes/AssemblyTreeNode.cs#LL174C41-L174C41) method... when you expand a tree node in the ILSpy UI that represents an assembly (which I think is what our single file executables would be represented as), this is the code that runs to enumerate all the various modules that are bundled into the single file executable.

**Comment by jamescrosswell** [comment]
OK, ILSpy is cunning. Here's what it's doing:

### Determine whether it's a bundle
If it can't load the assembly from a file, it then checks to see if it can load it from a bundle
[`var bundle = LoadedPackage.FromBundle(fileName);`](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedAssembly.cs#L363)

Basically it loads the whole package into into a `MemoryMappedFile` and then it [hunts for a bundle signature](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.Decompiler/SingleFileBundle.cs#L40) in that memory stream. If it finds one, it can then return the `bundleHeaderOffset` which is what is used to [lookup all the other bundle entries](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedPackage.cs#L119). 

### Get the other stuff in the bundle
Most of the work there happens in the `SingleFileBundle.ReadManifest(Stream stream)` method. It's this that enumerates all of the entries (which include resource files being bundled with the single file executable, but also any bundled assemblies) with useful stuff like the offset, within the file/stream where that entry is kept. 

### Load details for specific entries/assemblies

In ILSpy at least, this happens when you try to expand the node representing an embedded assembly in the ILSpy UI. That's where the `PackageFolderTreeNode.LoadChildrenForFolder` method gets invoked, and there's some specific [logic in there to handle dlls](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ILSpy/TreeNodes/PackageFolderTreeNode.cs#L68) (I think folders are only relevant for resources - not for embedded assemblies). 

This is where the offsets for bundled assemblies that were collected from the package manifest are used to load the bundled assemblies from memory - which happens in [`LoadedPackage.ResolveFileName(string name)`](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedPackage.cs#L333). 

There's a bit of inception going on at this point.  `LoadedAssembly` is called. One of the parameters that gets passed in is `Task.Run(entry.TryOpenStream)`... so the `LoadedAssembly` that gets returned has a `Task<Stream?>`... The concrete implementaion of that TryOpenStream that gets called, in the case of bundled assemblies is eventually [`BundleEntry.TryOpenStream`](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedPackage.cs#L208). This method is critical as it's where the logic to decompress bundles is implemented, if necessary. Otherwise, if the assembly hasn't been bundled compressed, a plain vanilla `UnmanagedMemoryStream` gets returned starting at the appropriate entry offset.

Finally, once that Task completes and hands back the stream for the assembly we want, this gets used in the `LoadedAssembly` constructor in [a call to `LoadAsync`](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedAssembly.cs#L102)... which is the same method that loaded our single file executable... only this time, the branch of code that gets executed is not that dealing with bundles but the one that [loads vanilla assemblies from a memory stream](https://github.com/icsharpcode/ILSpy/blob/1548555665657c857bac622d5ef1d9aaea489b22/ICSharpCode.ILSpyX/LoadedAssembly.cs#L334).

**Comment by mattjohnsonpint** [comment]
Sounds like we're on the right path.  Cool!

> Thankfully, ILSpy also has an MIT License... so it'd be OK to copy/reuse whichever bits of this logic were appropriate.

If we are just learning from ILSpy and using the same approach, that's fine.  If you actually need to copy code from the ILSpy project, please put it in its own subdirectory and add an attribution file.  For example, see [`/src/Sentry/Internal/FastSerialization`](https://github.com/getsentry/sentry-dotnet/tree/main/src/Sentry/Internal/FastSerialization) - which is another bit of code we've internalized.  Thanks.
