### ISSUE TITLE
Potential memory consumption issue when UseSentryTracing is on in aspnet core 6

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-dotnet#2392]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

6.0.0

### OS

Windows

### SDK Version

?

### Self-Hosted Sentry Version

?

### Steps to Reproduce

Feedback from NDC Oslo attendee: Experienced high memory usage when using sentry tracing on relatively recent Sentry SDK, running under load on ASP.NET Core 6.  Removed `UseSentyTracing` and memory was fine with only errors.

Need to attempt to reproduce and investigate.

(Thanks for the feedback!)

**Comment by SeanFeldman** [comment]
Using a test ASP.NET Core API application (WeatherForecast controller, OOTB sample with the project template), running for 2 hours has resulted in over 1.5GB memory consumption by the process. From the dump analysis, the outstanding message is `AA0003 Finalizer Queue may be blocked and cause high memory usage`,  pointing to `System.Threading. ThreadLocal'1[[System.Collections.Concurrent.ConcurrentBag'1+WorkStealingQueue[[Sentry.Package, Sentry.....]]`

**Comment by SeanFeldman** [comment]
I've conducted a more thorough investigation to identify if the `UseSentryTracing` configuration option enables a memory leak with ASP.NET Core using the Sentry performance feature. 

The error reported previously pointed out a potential problem with the .NET finalizer queue. This turned out to be a false positive. Next, the testing was performed using artillery.io to generate an HTTP load on the ASP.NET Core API used for testing. Unfortunately, the load was too high and intense, which caused the finalization queue to get overwhelmed. Which an extremely high number of concurrent requests, the allocation of `Sentry.Package` is accordingly high. But, the class is fully managed and would be disposed of once the load subsides.

Where does it put this issue? While there is some optimization we could apply, including how `Sentry.Package` works, there's no viable evidence that there's a memory leak associated with the performance feature. As such, the issue will be closed. However, if there's any doubt about the validity of the finding or a reliable repro that could be shared for further investigation, please feel free to share a repro and leave a comment to reopen this issue.

**Comment by thiagoloureiro** [comment]
I had the same problem today during performance tests of one application.
<img width="92" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/29433794/40600378-0052-4023-9401-5e5a43f7aa01">

Application running on .NET 7 (API) 
Sentry 3.39.1 Installed.

After commenting out the line for tracing the memory usage is under 1GB.

**Comment by jamescrosswell** [comment]
@thiagoloureiro I've opened a new issue for this as the issue above relates to a different version of Sentry and a different version of .NET... quite a bit has changed with respect to how Sentry's tracing capability allocates memory since this issue was closed. In any event, let's keep the conversation going in https://github.com/getsentry/sentry-dotnet/issues/2754.
