### ISSUE TITLE
Sentry.NLog integration not working for .Net Windows form application

### ISSUE THREAD

**Issue by KedarC007** [getsentry/sentry-dotnet#2397]
### Package

Sentry.Nlog

### .NET Flavor

.NET Framework

### .NET Version

4.7.2

### OS

Windows

### SDK Version

3.29.1

### Steps to Reproduce

Hi Team,
Nlog.Sentry integration is not logging NLog Events on my sentry project Space. I have installed Sentry NLog  package from Nuget. I have set Sentry Configuration thogh Nlog.Config file. Attaching NLog config file with fake DSN for security concern.
. Normal C# unhandled project exceptions are got logged on project space using SentrySdk not With NlogSentry SDK. Not single event is not getting logged on Sentry Portal. I have tried Sentry Configuration initialization using LogManger.Configuration.AddSentry method as well but that also didn't worked. I have also tried upgrading my Nlog package version but that also didn't solved Problem. I am attaching package.config file for your reference.
I am getting below Log for sentry in nlog-internal.log file
****2023-05-26 13:23:11.8193 Info Sentry(Name=sentry_wrapped): Hub not enabled****

### Expected Result

All NLog events should get logged into Sentry project space for my .Net Windows form application.

### Actual Result

No NLog Events are getting logged for My application but only .Net unhandled exceptions are getting logged.

**Comment by mattjohnsonpint** [comment]
Thanks for reporting.  I'll take a look to see if I can reproduce.

But just so we're on the same page, it's important to understand that Sentry is not primarily intended to be used as a log aggregator.  Logging integrations are there to _augment_ Sentry's error monitoring capabilities.  Generally what this means is that only logs at `ERROR` level or higher will become events in Sentry.  Logs at `INFO` or `WARNING` level are recorded only as _breadcrumbs_.  Breadcrumbs or only kept in memory on the current scope until an error occurs - at which time they're included with the error event.  If no error occurs, or if the scope is popped before an error occurs, then the breadcrumbs are discarded.  This is by design.  If you want to adjust this behavior, you can adjust the `MinimumEventLevel` and/or `MinimumBreadcrumbLevel` options.

**Comment by mattjohnsonpint** [comment]
Hi.  I made an attempt to reproduce the failure, but everything worked successfully.  I used the exact versions of .NET Framework, NLog, and Sentry indicated in your attachments.  I even used your exact `NLog.config` file (except for putting in a valid DSN), and it worked correctly.

I suggest you try reproducing the problem from scratch on a brand new application.  If you can do so, then please zip the entire application and paste it here, or provide a link to it on a github repository, etc.

In the meantime, we can take a look at the debug output to see if there's anything reported by the SDK.  In your `NLog.config`, you are setting near the top `internalLogFile="c:\temp\nlog-internal.log"`.   Please check that to see if there's any useful information.  You can paste it here as well if you'd like me to take a look.  (Delete any existing file first to start from scratch, then create a new one by running your app and doing something that should create a log entry.).

If it doesn't look like there's anything useful, you might want to also set `internalLogLevel="Debug"` so that the Sentry SDK will generate the full detail of debug logging info.  Of course that will also pick up anything else that is logging debug info locally, so your file may end up quite large - and you might want to inspect it before sharing to make sure it doesn't contain any sensitive data.

Thanks.

**Comment by mattjohnsonpint** [comment]
And also just to confirm - you're initializing _only_ through the `NLog.config` file? Or are you also initializing Sentry or adding Sentry to NLog in code?  If both, it's possible that one is stepping on the other, depending on your exact setup.

**Comment by KedarC007** [comment]
> And also just to confirm - you're initializing _only_ through the `NLog.config` file? Or are you also initializing Sentry or adding Sentry to NLog in code? If both, it's possible that one is stepping on the other, depending on your exact setup.

No, I have only configured through NLog.config

**Comment by KedarC007** [comment]
Thanks Team for Support,
I have figured out problem and fixed it. Basically my LogManger.Configuration was getting overridden by one of my UI Logger in my code. I have fixed that and Nlog events started logging as a breadcrum

**Comment by mattjohnsonpint** [comment]
Glad you found a solution!
