### ISSUE TITLE
Does Sentry sink benefit from Serilog.Sinks.Async?

### ISSUE THREAD

**Issue by Xeevis** [getsentry/sentry-dotnet#241]
Hello, I'm wondering if there is any benefit at all in using Sentry with [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async) wrapper which helps to perform logging on background thread.

On the page it does say this, but Sentry isn't mentioned:
>Note: many of the network-based sinks (CouchDB, Elasticsearch, MongoDB, Seq, Splunk...) already perform asynchronous batching natively and do not benefit from this wrapper.

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .Enrich.FromLogContext()
    .WriteTo.Async(a => a.Sentry(o =>
    {
        o.MinimumBreadcrumbLevel = LogEventLevel.Debug;
        o.MinimumEventLevel = LogEventLevel.Warning;
        o.AttachStacktrace = true;
        o.SendDefaultPii = true;
    })).CreateLogger();
```

**Comment by bruno-garcia** [comment]
Sentry's SDK is already async internally so there's no need to use Serilog's async sink with it.

They have a note on their repo:
> Note: many of the network-based sinks (CouchDB, Elasticsearch, MongoDB, Seq, Splunk...) already perform asynchronous batching natively and do not benefit from this wrapper.

When you write `SentrySdk.CaptureException` we just put the event in an in-memory queue and a background worker flushes it:

https://github.com/getsentry/sentry-dotnet/blob/8c52324af9a389e36beefe70c5c34a56072030dc/src/Sentry/Internal/BackgroundWorker.cs#L126-L128

I hope this clarifies. Feel free to reopen otherwise.

**Comment by olsh** [comment]
Would it be better to mention the feature in the repository?

**Comment by bruno-garcia** [comment]
Would be nice. We could link to individual packages Readme from the main one. And there add extra info.

PR welcomed
