### ISSUE TITLE
Callback not called when sentry is not registered

### ISSUE THREAD

**Issue by Vandersteen** [getsentry/sentry-dotnet#2444]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

6.0.0

### OS

Any (not platform specific)

### SDK Version

3.33.1

### Steps to Reproduce

We have some internal nuget packages that integrate with Sentry if sentry is registered.
We currently do something like:

```
hub = serviceProvider.GetService<IHub>() ?? HubAdapter.Instance;
```

Now when calling `WithScopeAsync` when Sentry has not been registered in the .net core app, the code is not called:

```
await _hub.WithScopeAsync(async scope =>
    ... //This code is not called if sentry is not registered
);
```

I tracked it down to this line of code: https://github.com/getsentry/sentry-dotnet/blob/410b30d2ce0c4db93c050778249b0d812aff089c/src/Sentry/SentryScopeManagerExtensions.cs#L52

### Expected Result

Code is being called even if sentry is not registered

### Actual Result

Code is not being called

**Comment by bitsandfoxes** [comment]
This looks to me like intended behaviour.
With the SDK not initialized the instance of the `HubAdapter` will be disabled and `WithScopeAsync` returns with `Task.CompletedTask`.

**Comment by Vandersteen** [comment]
This makes it really unhandy thought during development (where sentry is not initialised).
Or when sentry is 'optionally' enabled

**Comment by bitsandfoxes** [comment]
I can see how that is frustrating, especially since the behaviour is definitely not apparent. We have plans to deprecate those methods.
The idea is that users ideally would not put "business logic" into Sentry SDK callbacks.

**Comment by Vandersteen** [comment]
For some context, we have some shared libraries that handle cross cutting concerns (like service bus / queue handling / ... etc) in our company.

In there we have for example some WorkerServices that handle queues & other background work. The logs are currently 'leaking' in the breadcrumbs. This was 'fixed' in 3.31 I believe, however I now have to do something like this everywhere:


Loops:

```
do
{
  using(_ = _hub.PushScope())
  {
     _hub.ConfigureScope(s => s.Clear());
     ...
  }
}
while(!cancellationToken.IsCancellationRequested);
```

Event Handlers:

```
using(_ = _hub.PushScope())
  {
    //Clear here so that no logs from other background service 'leak' over where we have no control
     _hub.ConfigureScope(s => s.Clear());
     
     _processor = _client.CreateProcessor(options);
     _processor.ProcessMessageAsync += ProcessorOnProcessMessageAsync;
     _processor.ProcessErrorAsync += ProcessorOnProcessErrorAsync;
     await _processor.StartProcessingAsync(cancellationToken);
     
     //Clear here so that no logs from this 'callstack' leak over to Message Handling
     _hub.ConfigureScope(s => s.Clear());
 }
 
     private async Task ProcessorOnProcessErrorAsync(ProcessErrorEventArgs arg)
    {
        using var sentryScope = _hub.PushScope();
        _hub.ConfigureScope(s => s.Clear());
        
        ...
    }
 
```

As you can see, this gets ugly very quickly and leaks happen very quickly as well.
(Imagine going down 2-3 extra levels of this)

On top of that, we do not always have control of the '3rd party' libraries we are using

(Do not that we use Sentry.Extensions.Logging for pure worker services & Sentry.AspNetCore for 'Api' projects).

If we are approaching this in a wrong way, I would love some feedback

**Comment by jamescrosswell** [comment]
> If we are approaching this in a wrong way, I would love some feedback

So all of the above is to avoid a memory leak? Do you have a link to any previous conversations about that? None of the changes that were made in [3.31](https://github.com/getsentry/sentry-dotnet/blob/main/CHANGELOG.md#3310) seem obviously related.

The only thing `Scope.Clear()` does is set all of the properties of the `Scope` back to their default values... which would be irrelevant if the Scope was just about to be garbage collected and once your `using` block finishes, I can't think what would be holding on to a reference to the scope. It'd be good to understand any previous discussions that were had about this.

**Comment by Vandersteen** [comment]
It was 3.30 it seems,

https://github.com/getsentry/sentry-dotnet/issues/1660

**Comment by jamescrosswell** [comment]
Ah, I see. [That](https://github.com/getsentry/sentry-dotnet/pull/2284) might actually have been my first contribution to Sentry 😁 

OK, so nothing in the original issue or the PR that addressed it is about a "memory leak"... that was about a "breadcrumb leak", where you ended up with breadcrumbs on the scope from other background services. 

This is the bit that I'm a bit worried about:

```
    //Clear here so that no logs from this 'callstack' leak over to Message Handling
    //With leak here, I mean a memory leak (logs / breadcrumbs are kept in memory longer than required)
    _hub.ConfigureScope(s => s.Clear());
```

I have no clue how/where the memory leak could be coming from). Neither `Breadcrumbs` nor the `ConcurrentQueue<T>` they're stored in on the `Scope` are disposable... 

Is there any way I could reproduce this? It feels like stabbing in the dark otherwise.

**Comment by Vandersteen** [comment]
I created a small repro here:

https://github.com/Vandersteen/SentryLeak

Do note that you will need a Azure Service Bus ConnectionString to make that repro work.

**Comment by Vandersteen** [comment]
My hunch is that it has something to do with thread locality. But i'll leave that up to you guys :)

**Comment by jamescrosswell** [comment]
I just created an Azure account this morning (testament to the depth of my experience with Azure) but I created an Azure Service Bus resource and got things up and running. 

**_Note:_** I had to tweak your sample. Topics aren't available on the Basic tier, so I changed from a Topic to Queue... I wasn't planning on having multiple consumers so this seemed like a good workaround. Hopefully that change hasn't had any impact on how/whether I can reproduce at my end what you're seeing at yours.

With that line of code uncommented, I wasn't seeing any breadcrumbs and with the line commented out, I did indeed see a (single) breadcrumb:

![image](https://github.com/getsentry/sentry-dotnet/assets/728212/4c23483c-7b44-4931-9b71-506822646eff)

However it looks like it should be there. It's the breadcrumb for the log message that was [created on line 31](https://github.com/Vandersteen/SentryLeak/blob/91046cf1b96e166c438d81dbadee1be28ba22f56/SentryLeak/Consumer.cs#L31).

@Vandersteen is this what you're seeing on your side, when using Topics rather than Queues? Were you expecting to see something different to this?

**Comment by Vandersteen** [comment]
Well, it will stay there for the entire lifetime of the application.
Which is what I wanted to prevent.
I get why you would want it to stay there in some cases, in other cases it would be handy to just be able to start from a 'clean' scope and or clear the scope.

This is now a 'simple' example, but it adds up quickly if you are not careful and can cause memory leaks / oomkills.

The ugly thing now is that our code is littered with .PushScope() & ConfigureScope(s => s.Clear());

**Comment by jamescrosswell** [comment]
> Well, it will stay there for the entire lifetime of the application.

Hm, just that one breadcrumb though right? I leave the application running, with items being pushed to and then consumed from the queue and there is only ever one breadcrumb there. 

If I've understood then, the problem is that that one log message (resulting in one breadcrumb), combined with all the other log messages (from other "init" activities) add up to quite a lot of breadcrumbs littering the scope. Is that what's going on?

btw: Do you set [MaxBreadcrumbs](https://docs.sentry.io/platforms/dotnet/configuration/options/#max-breadcrumbs) explicitly or are you just using the default (of 100)?

**Comment by Vandersteen** [comment]
I haven't played too much with the settings (so MaxBreadcrumbs is the default I guess)

**Comment by Vandersteen** [comment]
Hmmm the max breadcrumbs would mean it does not leak memory as much as I thought.

**Comment by jamescrosswell** [comment]
> I haven't played too much with the settings (so MaxBreadcrumbs is the default I guess)

OK. That, at the very least, puts a cap on the number of breadcrumbs that can pile up. You'll only ever have a maximum of 100 per scope (by default). So memory consumption on the application won't grow indefinitely. 

You still have a practical problem of ensuring that have all the relevant breadcrumbs and they're not drowned out in the noise of a bunch of irrelevant logs. 

There are a couple of tools at your disposal there. 

You can [set minimum levels](https://docs.sentry.io/platforms/dotnet/guides/serilog/#configuration) when configuring logging:
``` csharp
Log.Logger = new LoggerConfiguration()
  .WriteTo.Sentry(o =>
  {
    // Debug and higher are stored as breadcrumbs (default is Information)
    o.MinimumBreadcrumbLevel = LogEventLevel.Debug;
    // Warning and higher is sent as event (default is Error)
    o.MinimumEventLevel = LogEventLevel.Warning;
  })
  .CreateLogger();
```

Another is [the `SetBeforeBreadcrumb` hook](SetBeforeBreadcrumb) but you need some way to sift the logs/breadcrumbs you're interested in from those you're not. I'm not sure I have any silver bullets there... it might be a matter of playing around to see if there are any obvious markers in combinations of things like `Breadcrumb.Type`, `Breadcrumb.Category` or possibly information stored in the `Breadcrumb.Data` dictionary.

**Comment by Vandersteen** [comment]
Thanks for the tips, I'll have a look.

I guess as the original issue is 'resolved' you can go ahead and close this ticket.

I would still be awesome if the callback was still called, but for now we'll work around that
