### ISSUE TITLE
Add Sampling Decision to Trace Envelope Header

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-dotnet#2470]
## Description

See project description: https://github.com/getsentry/team-sdks/issues/8

**Comment by jamescrosswell** [comment]
@bitsandfoxes sorry I just started working on this before I noticed your name on it. It looks like Stephanie assigned you yesterday. 

I'll put work for the time being. If you haven't written any code yet, let me know and I can pick up where I left off... otherwise I can throw away what I've done already (which isn't much).
