### ISSUE TITLE
Transient `EventProcessor` not getting picked up `3.23.0` and newer

### ISSUE THREAD

**Issue by arthursilvakorp** [getsentry/sentry-dotnet#2529]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET Core

### .NET Version

6.0

### OS

Windows

### SDK Version

3.23.0 or higher

### Steps to Reproduce

I'm having an issue where I'm trying to update Sentry from 3.22.0 to 3.23.0+ and this causes the EventProcessor that handles a BackgroundJob to stop working. As a result, tags are no longer being sent to Sentry.io, even though the error itself is being captured.

### Steps to reproduce:
- Clone the following repository: https://github.com/arthursilvakorp/sentry-background-job
- Go to appsettings.json and change Dsn to your own.
- Leave a breakpoint in the `Process` method of `MyEventProcessor` class.
- Debug. The method is going to be called.
- Update Sentry.AspNetCore and Sentry.Serilog from 3.22.0 to 3.23.0 or higher.
- Debug. The method should keep being called, but it's not.

### Expected Result

By updating Sentry to 3.23.0+, EventProcessor should keep being called and the tag "Tag Value Test" should be sent to Sentry.io, like in 3.22.0, as the screenshot shows:

`3.22.0 version`
![3 22 - 1](https://github.com/getsentry/sentry-dotnet/assets/141262777/e03acad5-6909-45a8-a18f-51a974cdac5f)

### Actual Result

By updating Sentry to 3.23.0+, EventProcessor stops being called and tag "Tag Value Test" is not sent to Sentry.io, as the screenshot shows: 

`3.23.0+ version`
![3 23](https://github.com/getsentry/sentry-dotnet/assets/141262777/86b97add-9911-499c-b028-bf79685ad24a)

**Comment by bitsandfoxes** [comment]
Thanks for raising the issue and providing a repro. We'll take a look.

**Comment by bitsandfoxes** [comment]
As far as I can tell this happened with changes to the `SentryMiddleware` in https://github.com/getsentry/sentry-dotnet/pull/1979 I'm not sure yet if that was an intentional change or an uncaught side effect.
But to unblock you, you can add your global eventprocessor directly to the options like so:
```
builder.WebHost.UseSentry( options => options.AddEventProcessor(new MyEventProcessor()));
```

**Comment by jamescrosswell** [comment]
One issue with requiring people to register event processors directly in the Options callback is that it's more difficult to inject dependencies into their custom event processors... so it would be nice if we could reintroduce support for registering these via DI rather than the options callback.

**Comment by bitsandfoxes** [comment]
There's another repro in: https://github.com/getsentry/sentry-dotnet/issues/3454

**Comment by jamescrosswell** [comment]
Curiously, this one from our samples does work:
https://github.com/getsentry/sentry-dotnet/blob/b0a19968ceb0ec5103f3e1887afe2c865351aca3/samples/Sentry.Samples.AspNetCore.Mvc/Program.cs#L43-L44

I'll dig around to see what the difference is.

**Comment by jamescrosswell** [comment]
> As far as I can tell this happened with changes to the `SentryMiddleware` in #1979 I'm not sure yet if that was an intentional change or an uncaught side effect.

It looks like it was moved to the middleware so that it could be registered on the scope to address:
- https://github.com/getsentry/sentry-dotnet/issues/318

However, I'm unable to reproduce the exception described in that issue. It was all the way back when .NET Core 2.2.7 was still a thing so possibly the .net DI framework has seen a few improvements since then and it's no longer a thing. 

I think we can simply move the logic back to the `ApplicationBuilderExtensions`.

**Comment by jamescrosswell** [comment]
Tricky... 

The original/existing solution to do all of this in the SentryMiddleware works because the SentryMiddleware gets  created by the ServiceProvider (and so all of those providers just get injected automatically via the constructor, whether they're singleton, scoped or transient). 

For the background service we can't do this because the Sink gets constructed explicitly:
https://github.com/getsentry/sentry-dotnet/blob/351adeab94d33d41432351e07e5288687d796f83/src/Sentry.Serilog/SentrySinkExtensions.cs#L350

Neither the Sink nor the Hub (which it depends on) have any idea about service providers... 

We could maybe create some processor resolver Func in the Hub as an AsyncLocal and have the middleware wire the resolver up. I think that could work for singleton and transient dependencies. 

It might result in unexpected behaviour for processors with Scoped lifetime when these run in the context of a background service... as that scenario effectively creates a [Captive dependency](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#captive-dependency). 

I'll play around and see if I can get something working though.

**Comment by jamescrosswell** [comment]
I'm out of ideas unfortunately. See comment in the PR that I had prepared to address this:
- https://github.com/getsentry/sentry-dotnet/pull/3476#issuecomment-2224163264

For the time being then, the only way to have custom providers in background workers is by adding these on the `SentryOptions` directly.
