### ISSUE TITLE
Unable to add attachments to events with User Feedback in BeforeSend or SetBeforeSend in v3.35.1

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-dotnet#2549]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

7.01

### OS

macOS

### SDK Version

3.35.1

### Steps to Reproduce

**Create event with User Feedback like this -**
```
var eventId = SentrySdk.CaptureMessage("An event that will receive user feedback.");
SentrySdk.CaptureUserFeedback(eventId, "fran@gmail", "help.", "The User");
```

**From within BeforeSend, add an attachment to the event with configureScope()**
```
    options.BeforeSend = @event =>
    {
        SentrySdk.ConfigureScope(scope =>
        {

            scope.AddAttachment("logger.txt");

        });
        return @event;
    };
```

### Expected Result

Attachment gets attached to the event in beforeSend. 

### Actual Result

Attachment does not get attached.  

Downgrading to 3.31.0 causes this method to work again.  In 3.35.1, normal captureMessages without User Feedback will also work.

**This is an issue from my org which is mix of 3.35.0 and 3.31.0 events. Note that the recent 3.35.0/1 events do not have attachments.  The initial 3 attachments for this issue are 3.35.0 but these were attached using Local Scope and not in BeforeSend**

[User Feedback Issue From my org](https://francisorg.sentry.io/issues/4399139246/events/latest/?query=is%3Aunresolved&referrer=latest-event&stream_index=0)

**Comment by bitsandfoxes** [comment]
Hey there, sorry to see you run into this issue.
There seems to be a gap in our documentation regarding how to utilize `hints` that were introduced in `3.32.0`. We'll fix that. 

In short, the scope gets applied to the event before it hits the `BeforeSend` callback which means modifying the scope within the callback does not affect the event itself.

Instead of the deprecated `BeforeSend` you can (and should) use the `SetBeforeSend` method on the options that allows you to add the attachment to its `hint`.

```
options.SetBeforeSend((@event, hint) =>
{
    hint.Attachments.Add(new Attachment(
        AttachmentType.Default,
        new FileAttachmentContent("<filepath>", true),
        Path.GetFileName("<filepath>"),
        null));
    return @event;
});
```

Admittedly, this is not the most straightforward of user experiences. We'll see if we can make this smoother.
