### ISSUE TITLE
Discussion about Solution files, filters and CI

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2560]
I found it hard to get my head around this:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/5e7cd548-c1b5-4a37-8fd2-c26d0f20c42f)

Mainly because:

1. `Sentry.sln` vs `Sentry.Full.sln` was not very intuitive to me. Shouldn't `Sentry.sln` already be "full"?
In that case, could it be `Sentry.sln` with everything, and just the filters on top? I understand there's some logic based on the solution file to avoid compiling the mobile targets:

https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/Directory.Build.props#L18-L20

Is there another approach?

3. `Sentry-CI-Pack.slnf`: What does give us? Since `pack` happens on the same workflow where things are built, I imagine this saves from looking what projects need to be backed (`<IsPackable>true..`)? Samples are all marked as not packable already:

https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/samples/Directory.Build.props#L6
Same with tests:
https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/test/Directory.Build.props#L8

Is the 'speed up' worth having to maintain this additional filter file?

4. Too many `slfn` files? `SentryNoSamples.slnf`, `SentryAzureFunctions.slnf`, etc. Could this be just `Unload project` instead or are these used often enough?

The biggest problem I see is that everytime we add a new project, we need to deal with 3 solutions and all subsequent slnf because there's no way to use glob patterns, or negate (like everything **except** `/samples`, or for the CodeQL filter, just add everything under `src`, to name a couple).

5. `Sentry.Samples.OpenTelemetry.AspNet` classic msbuild project in the repo. Because `dotnet build` doesn't work here, there was an effort to keep these out, since the creation of this repo. It doesn't seem like this is built in CI (and that's probably good because it'd be slow, and require a separate build script/flow). There was another repo (https://github.com/getsentry/sentry-dotnet-samples and later https://github.com/getsentry/examples/tree/master/dotnet) to keep such samples that are rarely used and don't need to be built in CI on each PR.

6. The `.root` situation. I find these Solution Files thing a bit annoying. We have to manually curate a list of files/scripts etc to get into the solution. And when in the editor we only see what's there. So if something new gets added to the repo, we need to 'remember' (my weakest point) to add. These days IDEs are smarter, Rider for example:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/1307cdf9-1172-4332-b8ef-d5bad0b9b59d)

Already shows you all the files in the repo overlaying with the soltion:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/511bf1fb-88f0-4b1a-9023-a1f02ccbce60)
Now I can see everything in the file system, as god intended:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/5de72480-9507-4029-8b6d-d0a093505c71)

So I propose getting rid of all of those solution items copied over in 3 different `sln` files 

8. How about we stuff all of these filters in some folder?

9. It's hard to see the side effect of some changes. It builds on your filter. But you're actually breaking some sample or other part of the solution.

Or perhaps I'm overthinking, first time trying to contribute here in a year or so. That's possible. Thoughts?

**Comment by jamescrosswell** [comment]
1.  potentially we could rename `Sentry.sln -> SentryNoMobile.sln` and then rename `Sentry.Full -> Sentry.sln`
3. Sounds reasonable. I've been operating on the assumption there's a good reason for most stuff so haven't challenged any of this. The `IsPackable` build property sounds good instead if that's the only reason we have a separate solution for CI though. 
4. I don't use those personally... happy to delete
5. Is there an issue having them in the repo? If they're not part of any of the solutions that get built by CI or that we use when developing, I don't think they get in the way... and it sounds like a pain maintaining a separate repo for these. If we ever need to debug anything or look into issues with Classic ASP.NET, the sample project is a good way of quickly bootstrapping things for investigation, so it's nice to have these next to the source... 
6. Maybe worth thinking about the experience for folks who are new to the repo... as long as the key files they'd need (ready, contrib etc.) are obvious and easy to find, I'm happy with another approach. If they need to "know" that you have to show all files in the IDE to see relevant stuff, it starts to become a bit of a gotcha that will trip people up (repeatedly). So maybe there's an argument to keep those things referenced in the solution files. 
8. I don't mind having the filters in the root directory. They're only really convenient if you're using Visual Studio anyway... in Rider you don't have a solution filter drop down to easily apply different filters in the same way.

**Comment by bruno-garcia** [comment]
After trying to figure out why a specific test project wasn't running, sadly took me too long to check the build yaml. There's a solution filter for that too that has to be manually changed:
```
        run: dotnet test Sentry-CI-Test.slnf -c Release --no-build --nologo -l GitHubActions -l "trx;LogFilePrefix=testresults_${{ runner.os }}"
```

It's quite hard to reproduce CI problems locally due to this complexity

**Comment by bitsandfoxes** [comment]
> I've been operating on the assumption there's a good reason for most stuff so haven't challenged any of this.
I'm in the same boat.

I think there should be as few filters as possible. `Mobile` vs. `No Mobile` comes to mind. I have not yet used a single `.slnf` for local development. 

Regarding CI: I'm of the strong opinion that whatever happens in CI should be as close to what we have in our local environment. Ideally, those should be identical. I'm really not buying into speeding up CI at the cost of complexity.

**Comment by jamescrosswell** [comment]
Re getting rid of the solution filters, there's a StackOverflow thread that looks interesting but I haven't quite wrapped my head around it yet:
* [How do I put a condition on msbuild built-in targets like Build/Rebuild?](https://stackoverflow.com/questions/57908849/how-do-i-put-a-condition-on-msbuild-built-in-targets-like-build-rebuild)

I was thinking we could define some custom `BeforeBuild` logic in our `Directory.Build.targets` file that could check something like the `matrix.os` from GitHub Actions and use that to skip/exit the build for any projects that weren't relevant to a particular CI build. That way we could map projects to the CI builds in build props rather than solution filters. 

However, I think what Mengdi Liang is suggesting would return an exit code of 1, which would stop the project being built but would implicitly break our builds in CI as it would look like an error to GitHub.

Maybe it's easier to keep using the solution filters to determine which projects to include in CI, but we get rid of some of the other unnecessary filters:

| Keep | **Solution**/Filter | Comments |
| ------------- | ------------- | ------------- |
| ✅ | **Sentry.Full.sln** | Rename to Sentry.sln |
| ✅ | SentryNoMobile.slnf | If you don't have a Cocoa/Android dev environment |
| ✅ | Sentry-CI-Build-Linux.slnf |  |
| ✅ | Sentry-CI-Build-macOS.slnf |  |
| ✅ | Sentry-CI-Build-Windows.slnf |  |
| ❌ | Sentry-CI-CodeQL.slnf | Use same slnf as for build |
| ❌ | Sentry-CI-Pack.slnf | Use same slnf as for build + IsPackable build prop |
| ❌ | Sentry-CI-Test.slnf | Use same slnf as for build |
| ❌ | SentryAspNetCore.slnf | Unnecessary |
| ❌ | SentryAzureFunctions.slnf | bUnnecessaryar |
| ❌ | SentryCore.slnf | Unnecessary |
| ❌ | SentryDiagnosticSource.slnf | Unnecessary |
| ❌ | SentryNoSamples.slnf | Unnecessary |
| ❌ | Sentry.Mobile.sln | Unnecessary |
| ❌ | SentryMobile.slnf | Unnecessary |
| ❌ | Sentry.sln | Replaced by SentryNoMobile.slnf |

**Comment by bruno-garcia** [comment]
Would that work with a single solution? Today we need at least two solutions because of this hack:

https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/Directory.Build.props#L18-L20

We'd need a different approach to avoid building those.

I wonder if a script that generates these slnf are also an approach. Because it's useful to have less projects loaded depending on the work you do, it's just hard to maintain all of those filters/slns

**Comment by jamescrosswell** [comment]
> I wonder if a script that generates these slnf are also an approach. Because it's useful to have less projects loaded depending on the work you do, it's just hard to maintain all of those filters/slns

Yeah the solution filters have a super simple structure... that might be the easiest approach. For the most part, we could build the filters on conventions like "include all the projects in this directory". If we wanted to do anything complicated we could use some custom MSBuild properties in the csproj files to override those conventions with explicit includes/excludes.

**Comment by jamescrosswell** [comment]
I didn't like the idea of having to compile a .NET project in order to be able to generate the solution files. I also didn't like the fact that [rosenbjerg/slnf-gen](https://github.com/rosenbjerg/slnf-gen) would need to be called once per slnf we wanted to generate, and it only seemed to accept one glob per include/exclude... I thought there might be cases where it would be convenient to supply multiple globs for either the includes or the excludes. 

So I put together a powershell script that could do this for us based on a json config file. See:
https://github.com/getsentry/sentry-dotnet/pull/2576/files

I'll try setting up the configs for our actual slnf's this evening. If they work, it should result is no changes to our solution whatsoever (those slnf files should look exactly like they do now). 

About the only thing we might want to do is add some comments at the top of the slnf files to let people know these get generated automatically by our powershell script, so they know not to try to change these manually.

**Comment by jamescrosswell** [comment]
I think generating the solution files is the way to go - so far I've tried to do it just for `Sentry-CI-Build-Linux.slnf` and already it [identified various files that really should be part of that build on Linux](https://github.com/getsentry/sentry-dotnet/pull/2576/commits/ce0c0a694a4fac9f1e590472bdc74419067f8b34). 

It would definitely make us more deliberate about what gets included/excluded in those CI builds.

About the only downside of this approach is that JSON files don't support comments. Potentially we could rewrite it to use yaml files instead. For the time being though, this is the config I've got (for a single slnf file so far... it's easy enough to add more):

```json
{
  "solution": "Sentry.Full.sln",
  "filterConfigs": [
    {
      "outputPath": "Sentry-CI-Build-Linux.slnf",
      "includes": [
        "**/*.csproj"
      ],
      "excludes": [
        "modules/**/*.csproj",
        "**/*Ios.csproj",
        "**/*Cocoa*.csproj",
        "**/*MacCatalyst.csproj",
        "**/*Sentry.AspNet.csproj"
      ]
    }
  ]
}
```

The reasoning for the excludes above is (I think - and happy to be corrected on any of this) that:
- We don't want to build the stuff from the modules (these weren't in the original slnf, so I excluded them too)
- The Ios, Cocoa, MacCatalyst projects won't work on Linux
- You also can't run .NET Framework stuff on Linux (like the Asp.Net samples)

It would really be nice to be able to put those explanations in the config file... so I'll take a look at switching it out to YAML instead.

**Comment by jamescrosswell** [comment]
Regarding the `NO_MOBILE` hack, that flag is set for the following solutions/filters:
- `Sentry.sln`
- `SentryAspNetCore.slnf`
- `SentryAzureFunctions.slnf`
- `SentryCore.slnf`
- `SentryDiagnosticSource.slnf`
- `SentryNoSamples.slnf`

None of those are used in CI... essentially it disables mobile target frameworks for developers who are working on any of those solutions/filters, in the following scenarios (I think):

#### Developing on Windows 

Can't target iOS/MacCatalyst https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/src/Sentry/Sentry.csproj#L13-L14

#### Developing on Mac

Don't want to deal with the complexity of setup up the dev environment to support mobile targets https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/src/Sentry/Sentry.csproj#L12-L14

### Alternatives

The Mac use case is valid (particularly if we're thinking about non-Sentry contributors)... it took me ages to get my dev envioronment setup for mobile. It was not easy. 

I think the Windows one is necessary as you literally can't build the solution on Windows unless you omit those target frameworks. Although, if that's true, I'm wondering how we do this on CI since Sentry-CI-Build-Windows.slnf is [based on Sentry.Full.sln](https://github.com/getsentry/sentry-dotnet/blob/047acad9cf4f2fc66898a869f22f049ca34dc496/Sentry-CI-Build-Windows.slnf#L3) (so presumably includes those targets and builds successfully on Windows)?

It looks like we have a different solution for Tizen, and we might be able to leverage this to determine which targets to include, instead of using the `Sentry.sln` hack:

https://github.com/getsentry/sentry-dotnet/blob/b3f81f1cf18c877029076e184ddef4b04acdef7e/src/Sentry.Maui/Sentry.Maui.csproj#L15-L16

**Comment by jamescrosswell** [comment]
I added a [feature request for msbuild](https://github.com/dotnet/msbuild/issues/9159) btw, but I see they've got 1.2k issues on their backlog so I'm guessing we'll need to come up with another plan in the mean time. 

I'll dig into the possibility of disabling target frameworks based on whether workloads are installed or not. Not quite the same but gives us maybe most of what we want/need.
