### ISSUE TITLE
Additional Memory Consumption of 15-20GB 30-90% due to Performance Monitoring

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-dotnet#2607]
### Problem Statement

Upon deploying Performance Monitoring in the aspnet SDK, customer noticed a 30-90% increase in Memory Consumption. It's not a memory leak, because the memory level goes down, but then back up again a lot. spikes.

The machine being used is:
web-nl-3 and web-nl-4 are both m5.2xlarge, which are 8 vCPU and 32GB RAM https://aws.amazon.com/ec2/instance-types/

NetFramework48
SDK version 3.34.0

On track for 120m txns per month because they sent 62m in 14-Days.

**Comment by jamescrosswell** [comment]
One thought about this is that we clone the scope every time a new span or transaction is created. It would be interesting to know how much of the memory that Sentry is allocating is in the form of Scopes (vs TransactionTracers/SpanTracers). 

Assuming all the cloned scopes are significant though, there might be a way to track the differences between child scopes and parent scopes rather than creating entirely new long lived clones. 

So one solution, for example, rather than setting properties directly on the scopes of child spans, we could associate one or more actions with them that could be used to determine the effective scope: `List<Action<Scope>> _scopeModifications`. The actual/effective scope for each span could be retrieved by taking a clone of the root scope and applying any scope modifications (similar to playing back the events in an EventSourcing architecture)... so you'd grab an ephemeral instance of the Span.Scope only when you needed to access it (probably it would have the lifetime of an individual method call... rather than staying in memory for as long as the transaction was running).

This would reduce memory consumption... it would come at the cost of speed though (as every time you needed to access the scope, you'd have to take a clone of the root scope and apply the scope modifications). 

Potentially we could give users the ability to choose whether they want`MemoryOptimizedTracing` or `CPUOptimizedTracing`... depending on which was the more important constraint in their particular business context.

**Comment by bruno-garcia** [comment]
I recommend measuring this (taking a memory heap dump) since guessing what might be the culprit can be a risky/time consuming game

**Comment by jamescrosswell** [comment]
* [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) (which we're using for benchmarking)
  * [BenchmarkSwitcher](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/guides/how-to-run.md#benchmarkswitcher)

**Comment by jamescrosswell** [comment]
When profiling applications I've noticed that, unsurprisingly, where memory is being consumed depends very much on what th application is doing. So if, for example, I get artillery to call this endpoint a few hundred times, most of the memory is consumed by allocations of breadcrumb (and it's various composite properties):

```csharp
                    endpoints.MapGet("/breadcrumbs", async context =>
                    {
                        void BreadcrumbCountdown(int countdown)
                        {
                            SentrySdk.AddBreadcrumb(countdown.ToString());
                            if (--countdown == 0)
                            {
                                return;
                            }

                            BreadcrumbCountdown(countdown);
                        }

                        BreadcrumbCountdown(100);
                        await context.Response.WriteAsync("Hello Breadcrumbs!");
                    });
```

On the other hand, if I have artillery call this, it's all about the scope:

```csharp
                    endpoints.MapGet("/scopes", async context =>
                    {
                        void ScopeCountdown(int countdown)
                        {
                            using (SentrySdk.PushScope())
                            {
                                SentrySdk.ConfigureScope(scope =>
                                {
                                    scope.SetExtra("countdown", countdown);
                                });

                                if (--countdown == 0)
                                {
                                    return;
                                }

                                ScopeCountdown(countdown);
                            }
                        }

                        ScopeCountdown(100);
                        await context.Response.WriteAsync("Hello Scopes!");
                    });
```

I'm wondering if it's possible to get some memory snapshots from real world applications that aren't so biased. It'd be really illuminating to know what was taking up the most memory in the customer application that triggered this issue, for example... and that will depend entirely on what their application is doing and how they've instrumented it with Sentry. Have they used lots of breadcrumbs? Do they have deep scope trees? Are they heavily using Tags? It could be any number of things, but it feels like we're stabbing in the dark a bit without data from real world applications.

**Comment by bitsandfoxes** [comment]
Considering this closed until proven otherwise.
Optimizations that happened:
- https://github.com/getsentry/sentry-dotnet/pull/2642
- https://github.com/getsentry/sentry-dotnet/pull/2641
- https://github.com/getsentry/sentry-dotnet/pull/2636
- https://github.com/getsentry/sentry-dotnet/pull/2632
- https://github.com/getsentry/sentry-dotnet/pull/2619
