### ISSUE TITLE
Sentry for Log4Net in .NET Core 2.2 Console App

### ISSUE THREAD

**Issue by happypotter1993** [getsentry/sentry-dotnet#269]
I have specified the DSN in log4net.config file, but Sentry does not initialize with it.

![image](https://user-images.githubusercontent.com/30451007/63788106-8a654e00-c912-11e9-96a9-eccb0d00b30d.png)

The code where I am using Sentry:
![image](https://user-images.githubusercontent.com/30451007/63788163-9c46f100-c912-11e9-9082-081c33e257d3.png)

______________________________________________________________

Instead of specifying DSN inside log4net.config, if I use it like:

using(SentrySdk.Init("XXXXX"))

then it works as expected.

**Comment by bruno-garcia** [comment]
I'm unsure by looking at your code what's wrong there. 
Perhaps it can't find the path to the log4net configuration/

We have a sample here:

https://github.com/getsentry/sentry-dotnet/tree/c77736679b500f7cc7ad760d0274f2f703d7b34c/samples/Sentry.Samples.Log4Net

It uses the Dsn in the configuration file:

https://github.com/getsentry/sentry-dotnet/blob/c77736679b500f7cc7ad760d0274f2f703d7b34c/samples/Sentry.Samples.Log4Net/app.config#L12-L22

Would it be possible for you to base you sample on that?

**Comment by happypotter1993** [comment]
1. This was a .net core console app. So it does not have app.config by default. 

2. I have copy pasted it exactly from your sample, just changed the DSN and removed comments.

3. The log4net is able to find and load the log4net.config. I have followed the steps exactly as specified in log4net configuration. The console output changes according to the changes in PatternLayout, so I am sure log4net is able to pick up the configuration file.

4. 
There are 3 functions in the Program.cs

EnsureLogger() -  This initializes the logger, if not yet initialized.
GetConfigFile() - This locates the config file for log4net.
Main() - This generates the error which is be logged.

I am attaching both files for your reference.



[log4net.config.txt](https://github.com/getsentry/sentry-dotnet/files/3568250/log4net.config.txt)
[Program.cs.txt](https://github.com/getsentry/sentry-dotnet/files/3568251/Program.cs.txt)

**Comment by bruno-garcia** [comment]
One question: Why use log4net with .NET Core? Is it an existent application you migrated for .NET Framework to .NET Core and it would be too much work to move from log4net to Serilog?

What's the use-case to use log4net on a .NET Core?

**Comment by happypotter1993** [comment]
We are using both .NET Framework and .NET Core across multiple solutions. We are using log4net, log4j etc according to the project language to maintain consistency and ease of use by using a common log4net.config file. We were trying to add sentry by just modifying the config file without any code changes.
Switching to Serilog is a problem because it is available only for .NET.

**Comment by bruno-garcia** [comment]
I understand. To be fair you are paying a high price for this consistency by having the lowest common denominator since log4net doesn't support structured logging, isn't actively developed anymore. The .NET logging ecosystem has moved on from it. It also doesn't ship a `netstandard2.0` target so I wouldn't be surprised our output directory is huge from the `netstandard1.x` mess.

I'll mark this as a bug. We'd need to investigate why it doesn't pick up the config when running on .NET Core, it was never tested as log4net is really here to support old apps that still don't use log4net. Sentry's SDK works well with .NET Core 2.0+ so the problem shouldn't be on the `Sentry` package. [The `Sentry.Log4Net` package targets `netstandard2.0`](https://github.com/getsentry/sentry-dotnet/blob/master/src/Sentry.Log4Net/Sentry.Log4Net.csproj#L4) so no compat issues there with .NET Core 2.0+.

If you'd like to contribute I suggest pulling this repo, changing `Sentry.Samples.Log4Net` and changing the `csproj` to target `netcoreapp2.2` instead of `new461`. You'd be reproducing the problem at that point. Just step through the code and try to figure out what's going wrong there. I doubt log4net has `sourcelink` since last package is from 2017 but if it does you'd be able to step into log4net's code too.

**Comment by bruno-garcia** [comment]
Closed this due to inactivity
