### ISSUE TITLE
Consider making Scope constructors internal

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2760]
Currently Scope has 3 constructors, one of which is public:
https://github.com/getsentry/sentry-dotnet/blob/8de3669b6e6289007c4716fa2b54947967c151d3/src/Sentry/Scope.cs#L236-L254

There's no obvious reason why SDK users would want to use that constructor though. They get at the scopes that have already been created/cloned via things like the `ConfigureScope` extension method.

@bitsandfoxes is this necessary for Xamarin/Unity or could we make this internal?

**Comment by bruno-garcia** [comment]
Looks like it was made public from v1: 

https://github.com/getsentry/sentry-dotnet/commit/22067c862bcb85fe924b7af7f9c62d738cdb0e9b#diff-5ad21d586eb98c0917050a560662833d07ec0203d267f57efef308774d74311fR73

I'm not sure of the impact of changing this, ppl might rely on it already (have a local instance around to pass as an argument to methods that take an instance instead of the callback).

Not sure it's worth changing this
