### ISSUE TITLE
Sentry.Serilog throws if a DSN is not passed even though SentrySdk should already be initialized

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry-dotnet#2866]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

Any (not platform specific)

### SDK Version

4.0.0-beta.1

### Steps to Reproduce

1. Add Sentry.Serilog and Sentry.AspNetCore to the app
2. Init Sentry with `builder.ConfigureWebHostDefaults(webBuilder => webBuilder.UseSentry(...));```
3. Try adding serilog with `builder.Services.CongureLogging()`
4. Use `.WriteTo.Sentry()` with no arguments

### Expected Result

The Serilog `.WriteTo.Sentry()` call shouldn't throw if SentrySdk is already initialized in the HostBuilder with `.UseSentry()`

### Actual Result

Throws during startup with `ArgumentNullException`

**Comment by bruno-garcia** [comment]
Should be an easy fix with SentrySdk.IsEnabled before throwing

**Comment by kanadaj** [comment]
Do note that passing an empty string to `WriteTo.Sentry()` doesn't actually fix this since it uses the following code:
```cs
        if (!string.IsNullOrWhiteSpace(dsn))
        {
            sentrySerilogOptions.Dsn = dsn;
        }
```

**Comment by jamescrosswell** [comment]
Relates to:
- https://github.com/getsentry/sentry-dotnet/pull/2655

**Comment by jamescrosswell** [comment]
@kanadaj I think in this scenario, where you have already initialized Sentry via the generic host (and a call to `UseSentry`), the best option would be to pass a value of `false` in the `initializeSdk` argument when hooking Sentry up to Serilog. So something like:
```
builder.Host.UseSerilog(new LoggerConfiguration()
    .WriteTo.Sentry(initializeSdk: false)
    .CreateLogger());
```

That way, even though you're not supplying a DSN, it won't try to use that (null) value to initialise the SDK anyway. 

I will make a change to the code such that if you do provide a disabled DSN (rather than a null DSN) it won't throw... but in that scenario you'd be initializing Sentry with a DisabledHub and nothing would get sent through to Sentry (which I don't think is what you want). 

I'll also create another ticket to see if we can be a bit smart about how we set the default value of `initializeSdk`... If a call had already been made SentrySdk.Init or UseSentry, for example, we could default this to `false` and conversely if those methods hadn't already been called we could leave the default of `true`.
