### ISSUE TITLE
FrameworkSupportsAot should only be set for .net8 and higher

### ISSUE THREAD

**Issue by jamescrosswell** [getsentry/sentry-dotnet#2886]
@vaind I think this implicitly means we need to change when we support AOT compilation:
https://github.com/getsentry/sentry-dotnet/blob/ebaed3e131d7346ce15ad28a11d37bcd30a99b0a/src/Directory.Build.props#L38-L41

If the serialization only works on net8.0 or greater then the framework only supports AOT on net8.0 or greater as well right (due to trimming)?

_Originally posted by @jamescrosswell in https://github.com/getsentry/sentry-dotnet/pull/2810#discussion_r1398510528_

**Comment by vaind** [comment]
what is this "FrameworkSupportsAot" anyway? google doesn't turn up anything

**Comment by vaind** [comment]
Personally, while I've been an advocate of trying to support net7, I'm all for switching of all the net7 AOT support in favor of net8+ because of this and other differences. We haven't supported NativeAOT for net7 when it came out so no reason to try to add support now that net8 is out. My assumption is that people running NativeAOT on net7 are going to try to update to net8 to get all the optimizations introduced there.

**Comment by bruno-garcia** [comment]
That works, given that it's a major version, new feature (for us), .NET 8 **is LTS**

**Comment by jamescrosswell** [comment]
> what is this "FrameworkSupportsAot" anyway? google doesn't turn up anything
> 
> update: we set `IsAotCompatible` based on that, so that's what this issue is about.

Yeah, it's just a way to centralise the logic for when we enable IsAotCompatible, so we don't have to copy/paste this all over the place every time it changes (like now). Once the AOT stuff settles down, we might be able to remove it but so far it's been good to have the logic for this defined in one place. 

I'll add some docs to the property to make this clear.
