### ISSUE TITLE
SentryHttpMessageHandler on MAUI not propagating traces for HttpClient requests

### ISSUE THREAD

**Issue by drowe5** [getsentry/sentry-dotnet#2931]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

7.0.49

### OS

iOS

### SDK Version

3.41.3

### Steps to Reproduce

1. Create a MAUI app using .NET 7.0 and Sentry.Maui 3.41.3
2. Configure Sentry as needed in MauiProgram.cs (in CreateMauiApp())
3. Write a function as described on the [Automatic Instrumentation](https://docs.sentry.io/platforms/dotnet/guides/maui/performance/instrumentation/automatic-instrumentation/
) page
```
var httpHandler = new SentryHttpMessageHandler();
var httpClient = new HttpClient(httpHandler);

var response = await httpClient.GetStringAsync("https://example.com");
```

4.Run the application in iOS Simulator on Mac (M1) running Sonoma 14.0

### Expected Result

The transaction will show up in the on the web (presumably under either Performance or Discover) sections.

### Actual Result

Transaction is not visible anywhere on the web (though other manually created Transactions as described in [Custom Instrumentation](https://docs.sentry.io/platforms/dotnet/guides/maui/performance/instrumentation/custom-instrumentation/) do appear as expected.)

**Comment by bitsandfoxes** [comment]
Sorry for the delay but I can reproduce this locally. Interestingly, the SDK does set the traceheader as expected but I suspect  the underlying native SDK is overwriting it.

**Comment by bitsandfoxes** [comment]
Relies on https://github.com/getsentry/sentry-cocoa/issues/3490

**Comment by jamescrosswell** [comment]
I can reproduce this. It seems to be due to this logic in the `SentryHttpMessageHandler`:
https://github.com/getsentry/sentry-dotnet/blob/043cb5f8b5e177bbc0b644e1706d2e8c7360488a/src/Sentry/SentryHttpMessageHandler.cs#L66-L69

So a span only gets created by `SentryHttpMessageHandler` if there is already an active transaction set on the scope.

If I add this to a MAUI event handler, a span for the HttpClient request is sent correctly as part of the transaction:

```csharp
        var transaction = SentrySdk.StartTransaction("OnCounterClicked", "Scour the web");
        SentrySdk.ConfigureScope(scope => scope.Transaction = transaction);
        try
        {
            var messageHandler = new SentryHttpMessageHandler();
            var httpClient = new HttpClient(messageHandler, true);
            var html = await httpClient.GetStringAsync("https://example.com/");
            CounterBtn.Text = html;
        }
        finally
        {
            transaction.Finish();
        }
```

I think we could [use this method instead](https://github.com/getsentry/sentry-dotnet/blob/5bcb9cac8b54f283a4ce5cc16573bfdf2970cdf9/src/Sentry/Internal/Hub.cs#L534-L541) in the MessageHandlers... which would either create/send a transaction (if no active transaction was set on the scope) or create a child span of the active transaction (if one was present).
