### ISSUE TITLE
MAUI MacCatalyst Apps have a `default.profraw` generated inside the .app bundle when the app exits

### ISSUE THREAD

**Issue by Redth** [getsentry/sentry-dotnet#2954]
### Package

Sentry

### .NET Flavor

.NET

### .NET Version

8.0.0

### OS

macOS

### SDK Version

4.0.0-beta.4

### Steps to Reproduce

1. dotnet new maui
2. Add Sentry, configure it for a MAUI project
3. Build/Debug the MacCatalyst target
4. Quit the app (IMPORTANT: Quit it gracefully, do not terminate it)
5. Observe in the `bin/Debug/net8.0-maccatalyst/MauiApp1.app` bundle there should be a `default.profraw` file now
6. Make a change to some c# and/or xaml in the app
7. Build/Debug MacCatalyst target again
8. Observe a build error which complains about codesigning and unsigned contents in bundle, ultimately pointing at the `default.profraw` file.

### Expected Result

This file should not get created at least in this location.

### Actual Result

File gets created, causing subsequent incremental builds to fail.

Video:
https://github.com/getsentry/sentry-dotnet/assets/271950/bae02c29-aaa3-42e2-86b0-8322ec208d0f

Sample/Repro project: 
[Archive.zip](https://github.com/getsentry/sentry-dotnet/files/13601458/Archive.zip)

**Comment by bruno-garcia** [comment]
I tried:
1. Created a new app
2. Built through `dotnet build -f net8.0-maccatalyst` and spawned the app from finder: CMD+O
3. Validated no `default.profraw`
4. Added Sentry 4.0.0-beta.4
5. Built through `dotnet build -f net8.0-maccatalyst` and spawned the app from finder: CMD+O
6. Validated no `default.profraw`
7. Changed some code, and `dotnet build -f net8.0-maccatalyst` and spawned the app from finder: CMD+O
8. Still no `default.profraw`

Changed code again and tried to build/launch via `dotnet build -t:Run` instead of via finder. Still couldn't repro.

This is what I see in the bundle:
![image](https://github.com/getsentry/sentry-dotnet/assets/1633368/4a469ed4-875d-4ed3-bfb6-c17448585c16)

**Comment by akoeplinger** [comment]
Seems this is enabled via the `-fprofile-instr-generate` flag when compiling LLVM https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#compiling-with-coverage-enabled

It looks like sentry-native builds with that if RUN_ANALYZER env var is set: https://github.com/getsentry/sentry-native/blob/0b17731c74e40202dea2e10b6c4aec8d6e66a1cd/tests/cmake.py#L152-L155

Did you perhaps pick the binary from the build that enables this instead of the normal one?
https://github.com/getsentry/sentry-native/blob/0b17731c74e40202dea2e10b6c4aec8d6e66a1cd/.github/workflows/ci.yml#L74-L80

https://github.com/getsentry/sentry-native/blob/0b17731c74e40202dea2e10b6c4aec8d6e66a1cd/.github/workflows/ci.yml#L55

**Comment by bruno-garcia** [comment]
Thanks for chiming in @akoeplinger ! We're building `sentry-native` from source so prob that's where the problem is. We build it here: https://github.com/getsentry/sentry-dotnet/blob/main/scripts/build-sentry-native.ps1
I don't see that env var though, @vaind any ideas?

**Comment by bruno-garcia** [comment]
It's odd that it's `sentry-native` specific if it's targeting `maccatalyst` because we use `sentry-cocoa` there and not `sentry-native`

**Comment by vaind** [comment]
And the sentry-native we build in the .net SDK is only linked to when building for osx, so that shouldn't trigger for maccatalyst, right? https://github.com/getsentry/sentry-dotnet/blob/217c11cea611a5f26e4a1abfbb7df37f34695722/src/Sentry/Platforms/Native/buildTransitive/Sentry.Native.targets#L23-L27

On the other hand, sentry-cocoa doesn't use sentry-native AFAIK.

**Comment by bruno-garcia** [comment]
> On the other hand, sentry-cocoa doesn't use sentry-native AFAIK.

that's right, it doesn't.

**Comment by akoeplinger** [comment]
Hmm yeah that kinda invalidates my theory :smile:

**Comment by akoeplinger** [comment]
I can reproduce the issue btw. and confirmed it is including sentry-cocoa (at least judging from the symbol names when I run `nm` against the Sentry binary.

**Comment by akoeplinger** [comment]
So this is definitely coming from sentry-cocoa since `nm` shows this symbol:

```
00000000001898c4 s ___llvm_profile_runtime
```

This static initializer is used to hook up profiling (INSTR_PROF_PROFILE_RUNTIME_VAR is ___llvm_profile_runtime):
https://github.com/llvm/llvm-project/blob/2b1c76c7c4d62f4470fe1527bf239f380c19760a/compiler-rt/lib/profile/InstrProfilingRuntime.cpp#L23

**Comment by akoeplinger** [comment]
Ohhh adding `archive` to the xcodebuild invocation makes everything work as expected 🥳

**Comment by bruno-garcia** [comment]
> Ohhh adding `archive` to the xcodebuild invocation makes everything work as expected 🥳
> 
> I'll open a PR.

wow just got back here and found this! 😅 thanks !!

**Comment by akoeplinger** [comment]
https://github.com/getsentry/sentry-dotnet/pull/2960

**Comment by bruno-garcia** [comment]
Thanks a lot @akoeplinger !! Great to have you contribute here, come again :)
