### ISSUE TITLE
NoMobile sln including mobile targets

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#2990]
Tried loading `Sentry.NoMobile.sln` and includes mobile projects like samples and bindings:

https://github.com/getsentry/sentry-dotnet/blame/725c830167d84b1bab38e349df3e8aa3339fdd7e/Sentry.NoMobile.sln

**Comment by bitsandfoxes** [comment]
The `NoMobile.sln` was added to give us a way to set the `NO_MOBILE` property https://github.com/getsentry/sentry-dotnet/blob/59b29fa26b76e81cec6581f7f737467ab6df4839/Directory.Build.props#L18
since the solution name is readily available.

The filters have either `Sentry.sln` or `SentryNoMobile.sln` as their solution and the idea is to use the `.slnf` for development.

Admittedly, it's not ideal to have a `SentryNoMobile.sln` and a `SentryNoMobile.slnf` next to each other.
@jamescrosswell since we're generating the `.sln` for local development what about renaming it to something like `Dev.NoMobile.sln` or something similar to avoid this?

**Comment by bruno-garcia** [comment]
> The NoMobile.sln was added to give us a way to set the NO_MOBILE property

Do we need the `slnf` then? Can we just have `NoMobile.sln` not contain mobile?

**Comment by jamescrosswell** [comment]
> Do we need the `slnf` then? Can we just have `NoMobile.sln` not contain mobile?

You can but then we're back to manually maintaining multiple Solutions. Every time we add or remove a project, we'd have to do that (manually) to both solutions... which is error prone. Getting rid of multiple solution files we maintain manually was the whole point of creating the scripts to maintain all the solution filter files and copies of the `Sentry.sln` solution file. 

The solution copies aren't really designed to be used directly so yeah, we could come up with some naming convention to make that explicit as @bitsandfoxes suggested. Maybe something like `__Generated.NoMobile.sln` (if that's a valid file name on Windows, Mac and Linux).

**Comment by bruno-garcia** [comment]
if that's not on the root it might already help?

**Comment by jamescrosswell** [comment]
> if that's not on the root it might already help?

True, but you'd need to manipulate/modify the solution file then (not just copy it) to create the NoMobile one. 

Another option - possibly we could give it a name starting with `.` to make it implicity hidden? More of a Linux/Mac thing but hopefully sufficiently clear for Windows users as well...

**Comment by bruno-garcia** [comment]
sounds simple enough to try it out.

More importantly, could you please expand the solution filter section of the CONTRIBUTING.md doc with a description of this? Why we have 2 sln, that you should or not use them directly, etc?
