### ISSUE TITLE
Add more built in metrics units

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3064]
https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/#units-support

for example: 'byte'

I added a custom one and assumed "bytes" and sentry doesn't format that nicely.

**Comment by jamescrosswell** [comment]
> https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/#units-support
> 
> for example: 'byte'
> 
> I added a custom one and assumed "bytes" and sentry doesn't format that nicely.

I think this is a server side thing. When we transmit the unit to Sentry, the unit is simply transmitted as a string in the statsd protocol:
https://github.com/getsentry/sentry-dotnet/blob/0fde2e34300a961fd62fcfd77614ec51b11275e3/src/Sentry/Protocol/Metrics/Metric.cs#L72

Since we're leveraging MeasurementUnit under the hood for the .NET SDK metrics implementation, that means it's this:

https://github.com/getsentry/sentry-dotnet/blob/0fde2e34300a961fd62fcfd77614ec51b11275e3/src/Sentry/MeasurementUnit.cs#L76

If we had other enum values, all that would do is give us an indirect way of passing a different string to statsd - but you can do that already with a custom metric. 

I suspect in your case it was because you used `bytes` rather than `byte`.

**Comment by jamescrosswell** [comment]
Might be worth adding those to MeasurementUnit as well though, to avoid typos like this.

**Comment by jamescrosswell** [comment]
Unless I've misunderstood, it looks like MeasurementUnit already supports all of these:
* [MeasurementUnit.Duration.cs
](https://github.com/getsentry/sentry-dotnet/blob/e75d537c14ded617c99eb33f19cf4ce69ca4de36/src/Sentry/MeasurementUnit.Duration.cs)
* [MeasurementUnit.Fraction.cs](https://github.com/getsentry/sentry-dotnet/blob/e75d537c14ded617c99eb33f19cf4ce69ca4de36/src/Sentry/MeasurementUnit.Fraction.cs)
* [MeasurementUnit.Information.cs](https://github.com/getsentry/sentry-dotnet/blob/e75d537c14ded617c99eb33f19cf4ce69ca4de36/src/Sentry/MeasurementUnit.Information.cs)

@bruno-garcia in the code where you were having problems, were you using a custom `MeasurementUnit` or did you use `MeasurementUnit.Information.Byte`?

**Comment by bitsandfoxes** [comment]
Looks like this is covered by `MeasureUnit.Information.Byte` and Sentry accepts both.

On Sentry:
`MeasurementUnit.Custom("bytes")`
![Image](https://github.com/getsentry/sentry-dotnet/assets/25725783/2d551580-c319-4757-b4d9-5c8feb90d8a6)


`MeasureUnit.Information.Byte`
![Image](https://github.com/getsentry/sentry-dotnet/assets/25725783/5772ef2e-6b5e-4178-aa46-a7de7b701d18)
