### ISSUE TITLE
Enable `AutoSessionTracking` by default

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3104]
See https://github.com/getsentry/sentry-dotnet/blob/7fd6f20262e62761032f2d92fbcac65f9f8c04a4/src/Sentry/SentryOptions.cs#L1009-L1014

There are currently a couple of blockers:
- It does not work with multiple instances of the app running at the same time
- Does not work for server
  - Metrics could be an alternative solution to this

**Comment by jamescrosswell** [comment]
> There are currently a couple of blockers:
> 
> * It does not work with multiple instances of the app running at the same time
> * Does not work for server
>   * Metrics could be an alternative solution to this

@bitsandfoxes given those blockers, do we still want to enable this by default? 

I think it might make more sense to only enable this by default in situations where we know it works... so for client apps basically (possibly even only for mobile apps, since we know there will only be a single instance of those running).

**Comment by bitsandfoxes** [comment]
It's a good call to have the individual integrations handle the default behaviour. MAUI specifically seems like a prime example to have `AutoSessionTracking` enabled by default.
