### ISSUE TITLE
set config ssl

### ISSUE THREAD

**Issue by EngRajabi** [getsentry/sentry-dotnet#315]
Please mark the type framework used:

- [ ] ASP.NET Core

Please mark the type of the runtime used:

- [ ] .NET Core

* Version: 1.2.0

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.AspNetCore

* Version: 1.2.0

add option for bypass ssl vertificate

**Comment by bruno-garcia** [comment]
You can do that by registering your own implementation of `ISentryHttpClientFactory` which ignores SSL certificates.

Register a callback to configure the ClientHandler:

Something like this:

```csharp 
UseSentry(o =>
     o.ConfigureHandler = (h,d) => 
     {
         h.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
      };
```

https://github.com/getsentry/sentry-dotnet/blob/f6007f621d4935ca2570c0163ede944d7c86483f/src/Sentry/SentryOptions.cs#L276-L279

I hope this helps. Feel free to reopen otherwise.

**Comment by EngRajabi** [comment]
This will solve the problem

```c#
 .UseSentry(c =>
                {
                    c.ConfigureHandler = (handler, dsn) =>
                    {
                        handler.ClientCertificateOptions = ClientCertificateOption.Manual;
                        handler.ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true;
                    };
                })
```

You can add this section to your document
