### ISSUE TITLE
.NET SDK powered by OTel

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-dotnet#3159]
### Description:

See [parent ticket](https://github.com/getsentry/team-sdks/issues/4) for more project background. 

We would like to investigate using OpenTelemetry's .NET SDK to replace Sentry performance package in our own SDK. This would allow our users to benefit from all of the instrumentation of the open standard's SDK, while allowing us to tailor the experience. 

### Requirement:
The OTel SDK should run the show in terms of instrumentations and collecting telemetry, our SDK should only do some fine tuning to ensure data is flagged for ingestion properly (OTel attributed as  tags for example)

Open Point:
- Sentry will have a product ready OTLP endpoint, with this, we have an opportunity to exclude the transaction model all together from our implementation. It should be investigated if we need to adapt our existing trxn model.
- Does OTLP give us a simpler route?

### Information:

- [OTel SDK Docs](https://opentelemetry.io/docs/languages/net/)
  - [OTel .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet)
  - [Getting Started](https://opentelemetry.io/docs/languages/net/getting-started/)
- [Microsoft OTel Docs](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel)

# Updated requirements 

See [Discord chat](https://discord.com/channels/621778831602221064/1225041001765146644/1225427049804595382) for context.

- When Sentry is initialized using OpenTelemetry instrumentation, calls to .StartSpan() or .StartChild() on the Sentry SDK should result in spans that fit seamlessly into the auto-instrumentation provided by OpenTelemetry.
- We also need to ensure the correct trace id is used regardless of whether the backend is otel or sentry only

## Sentry Transactions with OTEL Child Spans

Currently leads to unexpected outcomes. 

```csharp
var transaction = SentrySdk.StartTransaction("Program", "Main");
try
{
   Console.WriteLine("Hello World!");
   using (var task = activitySource.StartActivity("Task 1"))
   {
       task?.SetTag("Answer", 42);
       Thread.Sleep(100); // simulate some work
   }


   using (var task = activitySource.StartActivity("Task 2"))
   {
       task?.SetTag("Question", "???");
       Thread.Sleep(100); // simulate some more work
   }


   Console.WriteLine("Goodbye cruel world...");
}
finally
{
   transaction.Finish();
}
```

The Sentry transaction gets ignored. If we turn on Debug mode we see the following warning:
```
Warning: Attempted to start a transaction via Sentry instrumentation when the SDK is configured for OpenTelemetry instrumentation.  The transaction will not be created.
```

And as a result the two Activities show up as separate transactions:
![image](https://github.com/getsentry/sentry-dotnet/assets/728212/52cb7887-523c-4a7e-aef0-a152d0631c32)

We could run into this if people wanted to use OTel to take advantage of automatic tracing for some tech (e.g. Redis) but otherwise they had been instrumenting their app for performance using Sentry... so we probably need to fix this.

**Comment by jamescrosswell** [comment]
A couple of thoughts:
- It seems like a prerequisite to any of the is aligning the way Sentry and OTEL represent traces... specifically, OTEL doesn't distinguish between Transactions and Spans (in OTEL you can have a span that has no parent, but otherwise it has all the same properties etc. of other parented spans). 
- Are we planning on adding a hard dependency on [OpenTelemetry](https://www.nuget.org/packages/OpenTelemetry) to the [Sentry](https://www.nuget.org/packages/Sentry) package? Or would we move Tracing capabilities to the [Sentry.OpenTelemetry](https://www.nuget.org/packages/Sentry.OpenTelemetry#dependencies-body-tab) package? 
- For integrations where OpenTelemetry instrumentation already exists, would we be removing our proprietry instrumentation? For example, `Sentry.AspNetCore` has two bits of middleware... SentryMiddleware and SentryTracingMiddleware. Would the SentryTracingMiddleware be obsolete (replaced by OpenTelemetry tracing for ASP.NET Core)? All that we would really retain then would be the crash reporting?
- Are there some integrations that we maintain that don't have OpenTelemetry equivalents and what do we do with those? For example, if we want to move to using OpenTelemetry [Activity](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-8.0) for tracing, presumably integrations like DiagnosticSource that take events from DiagnosticListener and create SentrySpans from these would need to generate OpenTelemetry Activities from those  DiagnosticListener events instead. These are not really Sentry specific integrations/packages anymore - they become general OpenTelemetry adapters that could potentially be donated to and maintained in another repo (assuming equivalents don't already exist - ideally someone has already built these for OpenTelemetry and we could just obsolete/retire our own integrations... either way, I think we're moving to a model where we're leveraging integrations that are maintained by the broader .NET community). 
- Does it make sense for Sentry to have it's own `OTLP_ENDPOINT_URL`? From what I can tell, you'd do that if Sentry was not running in the same process as the application that was generating the telemetry... so the telemetry would be serialized via json/protobuf or whatever and sent to the endpoint, where it got deserialized and processed/stored. In our case, if Sentry is running in the same process, perhaps we're better off retaining the [SentrySpanProcessor](https://github.com/getsentry/sentry-dotnet/blob/bd62cf0421cc7a5d7b7804f8461fae00d47d43b8/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs) to collect traces? Probably needs a bit of research/consideration...

Overall, this seems like a **_really really_** big piece of work. We might need to break it down into bite sized chunks. Possibly getting rid of Transactions (or rather merging Spans and Transactions) would be a good first step?

**Comment by jamescrosswell** [comment]
### Transaction vs Span

```diff
+ AddBreadcrumb(Breadcrumb breadcrumb) : void
+ Breadcrumbs : IReadOnlyCollection<Breadcrumb>
+ Contexts : SentryContexts
 Description : string?
+ Distribution : string?
 EndTimestamp : DateTimeOffset?
+ Environment : string?
+ EventId : SentryId
 Extra : IReadOnlyDictionary<string,object?>
+ Fingerprint : IReadOnlyList<string>
 GetTraceHeader() : SentryTraceHeader
 IsFinished : bool
+ IsParentSampled : bool?
 IsSampled : bool?
+ Level : SentryLevel?
 Measurements : IReadOnlyDictionary<string,Measurement>
+ Name : string
+ NameSource : TransactionNameSource
 Operation : string
 ParentSpanId : SpanId?
+ Platform : string?
+ Release : string?
+ Request : SentryRequest
+ SampleRate : double?
+ Sdk : SdkVersion
 SetExtra(string key, object? value) : void
 SetMeasurement(string name, Measurement measurement) : void
 SetTag(string key, string value) : void
 SpanId : SpanId
+ Spans : IReadOnlyCollection<SentrySpan>
 StartTimestamp : DateTimeOffset
 Status : SpanStatus?
 Tags : IReadOnlyDictionary<string,string>
 TraceId : SentryId
 UnsetTag(string key) : void
+ User : SentryUser
 WriteTo(Utf8JsonWriter writer, IDiagnosticLogger? logger) : void

- SentrySpan(ISpan tracer)
- SentrySpan(SpanId? parentSpanId, string operation)
+ SentryTransaction(ITransactionTracer tracer)
+ SentryTransaction(string name, string operation, TransactionNameSource nameSource)
+ SentryTransaction(string name, string operation)

-FromJson(JsonElement json) : SentrySpan
+FromJson(JsonElement json) : SentryTransaction

```

**Comment by jamescrosswell** [comment]
Note that our `SentrySpanProcessor` doesn't currently apply the sentry scope to Otel spans when processing these. We could do that here if we wanted to (but only if other SDKs were also planning to do that - they don't seem to currently):
https://github.com/getsentry/sentry-dotnet/blob/a448cc45beef2109a7f5d6d628b4b4dce43f4496/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L433-L439
