### ISSUE TITLE
Performance monitoring is not working

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-dotnet#3269]
### Package

Sentry.AspNet

### .NET Flavor

.NET

### .NET Version

-

### OS

Browser

### SDK Version

4.0.3

### Steps to Reproduce

The customer has set up performance monitoring as indicated by the docs.

### Expected Result

Able to receive transactions.

### Actual Result

Unable to receive transactions. There seem to be no debug logs related to Sentry as well.

The app can be found in [the shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2140).
[Zendesk ticket.](https://sentry.zendesk.com/agent/tickets/114808)

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2140) by [Unito](https://www.unito.io)

**Comment by jamescrosswell** [comment]
@InterstellarStella can you provide a bit more detail? I don't have access to the ZenDesk ticket...

It might be worth getting the customer to upgrade to 4.2.1 for a start (the latest release), if that's possible.

It'd also be great to get some debug logs... so if they could set `Debug = true` in the sentry options and check the consol/debug output to see if there are any clues in there.

**Comment by InterstellarStella** [comment]
Hi @jamescrosswell, @bitsandfoxes has already picked this up internally. I made sure they set `Debug = true` but there were no entries related to Sentry in their logs.

**Comment by apurvasharma001** [comment]
Hi, @InterstellarStella I shared the updated version of Sentry & enabled Debug = true & also shared the screenshot with logs too over the email. Please review it.

**Comment by InterstellarStella** [comment]
Updated the shadow ticket with the newest version of the application which includes the updated Sentry SDK. Also attached the debug logs.

**Comment by bitsandfoxes** [comment]
Hey, sorry for the delay. I tried looking through the repro you've provided but that's a bit more than minimal. I'm not sure what's going on there. The configuration in the `Global.asax.cs` looks good to me. but I could not find anything related to Sentry in the logs. Are you certain the SDK gets initialized properly?

**Comment by apurvasharma001** [comment]
Yes, SDK is initialized perfectly and you have the source code please check if there is missing something that I missed. But I am getting issues in over application on Sentry dashboard.

**Comment by cstechmk** [comment]
Dear Sentry Tech Team, We have been following up for implementation of Sentry Features in ASP.net since Feb 2024. At this time it is important for us to know if a resolution to the case we had generated is a priority for Team Sentry. Let us know in case you need assistance or in case you are not able to fix it. 
<img width="1752" alt="2024-04-30_10-15-15" src="https://github.com/getsentry/sentry-dotnet/assets/12711920/ea5aa8fa-3ebe-47b4-bff2-b67a5e37db27">

**Comment by bitsandfoxes** [comment]
Hey @cstechmk, thanks for reaching out. Supporting ASP.NET and fixing issues is on the top of our prioritize. I've had trouble running the repro provided but it's been updated since then and we'll revisit it shortly.

**Comment by bitsandfoxes** [comment]
This has not been forgotten.

**Comment by bitsandfoxes** [comment]
Alright, sorry, this took a while for me to get back to it but there are a couple of things happening here.
It works, and with a couple of changes to the project you provided I do get automatic performance monitoring showing up in Sentry.
![Screenshot 2024-05-14 at 12 09 16](https://github.com/getsentry/sentry-dotnet/assets/25725783/f13bc6bf-055c-4db8-ac98-e618de9d9668)

The changes I had to make:
1. Upgrade to TargetFrameworkVersin `4.6.2` We [replaced our support](https://github.com/getsentry/sentry-dotnet/pull/2786) for `4.6.1` with `4.6.2` as it went out support over 2 years ago.
2. Install the `Sentry.AspNet` package instead (or in addition) of the `Sentry` package.
3. Init the SDK in `Application_Start()`. The SDK is supposed to be active throughout the whole lifecycle of your applicatoin
4. Make sure the Init happens outside of the `using`. Otherwise, the SDK will get disposed of and shut down.
5. Call `Context.StartSentryTransaction()` and `Context.FinishSentryTransaction` inside of `Application_BeginRequest()` and `Application_FinishRequest()` respectively. You can read more about this on our [docs](https://docs.sentry.io/platforms/dotnet/guides/aspnet/performance/included-instrumentation/) 
6. Add `Server.CaptureLastError()` to `Application_Error()`
7. The SDK is now all setup and ready to go.
