### ISSUE TITLE
User ID is left blank on Android

### ISSUE THREAD

**Issue by espenrl** [getsentry/sentry-dotnet#3302]
### Package

Sentry.Maui

### .NET Flavor

.NET

### .NET Version

8.0.4

### OS

Android

### SDK Version

4.4.0

### Steps to Reproduce

Setup a MAUI project configured for Sentry. Do not override user configuration - hence standard behavior is to be expected with regards to user information in Sentry events.

### Expected Result

According to https://docs.sentry.io/platforms/dotnet/guides/maui/enriching-events/identify-user/#id

```
If you don't provide an id, the SDK falls back to installationId, which the SDK randomly generates once during an app's installation.
```

### Actual Result

User ID is left blank/null in Sentry events.

On iOS the user ID is set to a randomly generated guid and hence works according to documentation.

**Comment by bitsandfoxes** [comment]
Hi @espenrl, thanks for raising this. Looks like a but, the behaviour should indeed be the same on all platforms.

**Comment by espenrl** [comment]
This logic doesn't seem to be implemented at all for Windows.

And for Android it actually seems to be implemented already, but for some reason doesn't work.

https://github.com/search?q=repo%3Agetsentry%2Fsentry-java+user.setid&type=code

And here is for iOS

https://github.com/search?q=repo%3Agetsentry%2Fsentry-cocoa+%22userid+%3D%22&type=code

**Comment by jamescrosswell** [comment]
This should be picked up here:
https://github.com/getsentry/sentry-dotnet/blob/d664fc6de31f688e9d8a2bef26aabd82cf25cc2d/src/Sentry/Scope.cs#L122-L138

And here:
https://github.com/getsentry/sentry-dotnet/blob/5fab09efd4204fd07d95c818df79f7aa71d61e88/src/Sentry/SentryUser.cs#L24-L35

However that's only the .NET side of the sync, which ensures that any changes made in the .NET SDK will be reflected in the Java SDK. Potentially the opposite (Java syncing with .NET) is not setup. Probably need to check if the JavaSDK has any observer/notifier capability around this that we could leverage. 

If not, another possibility would be to imitate this functionality inside the .NET SDK... that'd be a little bit fiddly - we'd need to someone [refactor this](https://github.com/getsentry/sentry-dotnet/blob/711e61eb12bd900c939dba5c046f4b668da7838d/src/Sentry/GlobalSessionManager.cs#L126) so that it could be leveraged via a null coalescing operator in the getter for the user id.

**Comment by jamescrosswell** [comment]
> However that's only the .NET side of the sync, which ensures that any changes made in the .NET SDK will be reflected in the Java SDK. Potentially the opposite (Java syncing with .NET) is not setup. Probably need to check if the JavaSDK has any observer/notifier capability around this that we could leverage.

@adinauer does this look familiar to you (syncing scope data between the SDKs)? Do you know if there is any functionality in the Java SDK to sync scope data when it changes in the Java SDK?

In this particular case, the Java SDK sets the User.Id, but it's not being reflected up in the .NET layer before events get sent to Sentry.

**Comment by adinauer** [comment]
Hey @jamescrosswell we do have `IScopeObserver`, which can be registered in options via `addScopeObserver`. Maybe this NDK implementation helps: https://github.com/getsentry/sentry-java/blob/051ce9bce330e4a690fd59db52e506219a35eae9/sentry-android-ndk/src/main/java/io/sentry/android/ndk/NdkScopeObserver.java

**Comment by jamescrosswell** [comment]
> Hey @jamescrosswell we do have `IScopeObserver`, which can be registered in options via `addScopeObserver`.

Awesome, thanks @adinauer !

@bitsandfoxes I'm not sure we can use though (due to the issues around our enrichers). Maybe best to catch up for a chat about this one.
