### ISSUE TITLE
`scope.User = null` shows warning of CS8625: Cannot convert null literal to non-nullable reference type.

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-dotnet#3331]
### Package

Sentry.AspNetCore

### .NET Flavor

.NET

### .NET Version

7.0.1

### OS

macOS

### SDK Version

4.4.0

### Steps to Reproduce

1. Follow docs on how to clear the user here: https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/enriching-events/identify-user/
2. See warning on start up.

The user does seem to clear normally though, but the build will fail if you have nullable checks and enforce warnings as errors

### Expected Result

No warning

### Actual Result

<img width="457" alt="Screenshot 2024-04-25 at 12 48 13 PM" src="https://github.com/getsentry/sentry-dotnet/assets/96670625/00f09fd5-1203-469a-89db-686218825c7f">

<img width="1000" alt="Screenshot 2024-04-25 at 12 48 49 PM" src="https://github.com/getsentry/sentry-dotnet/assets/96670625/5815592e-93a8-4330-8a8c-a6332b6cf766">

**Comment by oliver-ec** [comment]
Hi, this is something of interest to me. 

We enforce nullables, and we treat those warnings as errors so it's detected at compile time. 

```
 <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
 <Nullable>enable</Nullable>
```

The problem is, when you have this set, this code won't compile 

```cs
SentrySdk.ConfigureScope(scope =>
{
    scope.User = null;
})
```

Because the decompiled code suggests the property 'User' is not nullable. The intent of being nullable is there since the private field is nullable, just not the property.

```cs
 private SentryUser? _user;

public SentryUser User
{
    get
    {
        SentryUser sentryUser = _user;
        if (sentryUser == null)
        {
            SentryUser obj = new SentryUser
            {
                PropertyChanged = UserChanged
            };
            SentryUser sentryUser2 = obj;
            _user = obj;
            sentryUser = sentryUser2;
        }

        return sentryUser;
    }
    set
    {
        if (_user != value)
        {
            _user = value;
            if (_user != null)
            {
                _user.PropertyChanged = UserChanged;
            }

            UserChanged(_user);
        }
    }
}
```

It would make my life happier if the property 'User' was nullable. I.e.

```cs
 private SentryUser? _user;

public SentryUser? User { get.. set... }
```

But I believe my suggestion is more syntactically correct since that property is intended to be nullable according to the documentation when trying to clear the user from scope.

https://docs.sentry.io/platforms/dotnet/enriching-events/identify-user/

**Comment by bitsandfoxes** [comment]
@bruno-garcia, do you have any context knowledge as to why that is? My understanding is that we (Sentry) always need a user in any case to be able to to show how many individual users (based on ID) are affected from any given error.

In any case, instead of setting it to `null` you can always overwrite it with a `new SentryUser()`.

**Comment by bruno-garcia** [comment]
we just don't allow user to be null but you can set all its fields null.

So it's safe to do `scope.User.Email = null` and the same to any other field.

**Comment by jamescrosswell** [comment]
> Can we update the code snippet in [clear user section](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/enriching-events/identify-user/) below to a new example that would not show the warning?

@bitsandfoxes I added a PR to the docs repository:
- https://github.com/getsentry/sentry-docs/pull/9860

**Comment by bruno-garcia** [comment]
Updated docs are live! thanks for reporting
