### ISSUE TITLE
Make span eligible for `Requests`

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-dotnet#3334]
https://docs.sentry.io/product/performance/requests/#span-eligibility

### SentryHttpMessageHandler / SentryGraphQLHttpMessageHandler

- ✅ The op field is set to "http.client"
- ✅ The description field contains the HTTP method and the full URL of the request (e.g., "GET http://my.service.io/some-data").
- ❌ If the request is to a relative URL (e.g., "GET /data.json"), the server.address span data value should be set to the server address (e.g., "my.service.io").
- ✅ The http.response.status_code contains the HTTP response status code (e.g., "200").
  - We appear to store this as "Extra" data rather than in the structured contexts, but the spans still show on the Requests page in Sentry 
    https://github.com/getsentry/sentry-dotnet/blob/24c159fac119315e21df6138dc04bfe3ccd573c2/src/Sentry/SentryHttpMessageHandler.cs#L70

    https://github.com/getsentry/sentry-dotnet/blob/bf4e0b3db4df28447d055cb569093c4307e85cf7/src/Sentry/SentryGraphQLHttpMessageHandler.cs#L57

### OpenTelemetry instrumentation

- ❌ The op field is set to `http.client`
  - The operation name is being set by OpenTelemetry to `Microsoft.AspNetCore.Hosting.HttpRequestIn`
- ❌ The description field contains the HTTP method and the full URL of the request (e.g., "GET http://my.service.io/some-data").
  - Only contains the HTTP method:
     https://github.com/getsentry/sentry-dotnet/blob/af2dd7214bf60eb73630f040c7a75e992c4e2d66/src/Sentry.OpenTelemetry/SentrySpanProcessor.cs#L344
- ✅ If the request is to a relative URL (e.g., "GET /data.json"), the server.address span data value should be set to the server address (e.g., "my.service.io").
- ✅ The http.response.status_code contains the HTTP response status code (e.g., "200").

**Comment by jamescrosswell** [comment]
@bitsandfoxes added some details to the issue description.

**Comment by jamescrosswell** [comment]
So it turns out this scenario isn't actually possible in .NET:
> ❌ If the request is to a relative URL (e.g., "GET /data.json"), the server.address span data value should be set to the server address (e.g., "my.service.io").

The only way to use Relative URLs with HttpClient is like this:
```csharp
using var client = new HttpClient(sentryHandler);
client.BaseAddress = new Uri("http://localhost");
var uri = new Uri("/hello", UriKind.Relative);
await client.GetAsync(uri);
```

The call to `await client.GetAsync(uri)` will throw an exception if you're using a `Uri` with `UriKind.Relative` and you haven't set the `HttpClient.BaseAddress`. On the other hand, if you provide the base address, this gets combined with the relative url to create an absolute Uri. 

No matter which way you do it then, by the time we see the Uri in the `SentryMessageHandler`, it will be an absolute URI. 

We could just always set the `server.address` span data... @bitsandfoxes thoughts?
