### ISSUE TITLE
Scopes not configured on MAUI

### ISSUE THREAD

**Issue by breyed** [getsentry/sentry-dotnet#3417]
### Package

Sentry.Maui

### .NET Flavor

.NET Core

### .NET Version

8.0.300

### OS

Any (not platform specific)

### SDK Version

4.7.0

### Steps to Reproduce

Global scopes are not appearing reliably in crash report for a MAUI project. How to set global scope isn’t documented either (at least as far as I can tell). I’m trying to track a global scope consisting of a tenant and username. The following are unclear:

1. When should I use `SentrySdk.ConfigureScope` versus `builder.UseSentry(options => { options.ConfigureScope …`?
2. When is `Action<Scope> action` called? Immediately? When Sentry needs to know the scope? Another time?
3. How do I change the scope when a user signs out and signs in with a new tenant and username?

A related problem is that even when username does appear, segment still never appears, even if `scope.User.Segment` is set. The documentation for `SentryUser.Scope` (“The segment the user belongs to”) just restates what is obvious from the class and method names and is not useful. What really needs to be documented is where the segment shows up in the Sentry website, its purpose, and any constraints on its value.

### Expected Result

Issues that always show the current scope. A clear, well-docuemnted API.

### Actual Result

Confusing and sometimes the scope info doesn’t appear.

**Comment by jamescrosswell** [comment]
Hi @breyed ,

I'm guessing you already found [these docs](https://docs.sentry.io/platforms/dotnet/enriching-events/scopes/)?

In terms of when the scope get used, it's just before an event gets sent to Sentry ([here](https://github.com/getsentry/sentry-dotnet/blob/37eb4a54cee682bec0d63435ce9959a67fb4656e/src/Sentry/SentryClient.cs#L285-L287) specifically).

It seems like your question is more about which scope will be used and how to make sure you're setting data in the correct way and and the correct time, to ensure this data gets sent to Sentry as you'd expect. 

Sentry's scopes are stored in a stack. When a new scope is pushed to the stack, it will be a clone of whatever scope was previously at the top of the stack.  Scope configuration that you perform via SentryOptions will be applied to the root scope in the stack (and so implicitly gets applied to all scopes). This is a good place to set scope values that won't change over the life of the application. 

However, the Sentry .NET SDK has a couple of different "modes" for managing scopes. For server applications, the default is to store scopes in an `AsyncLocalScopeStackContainer`... basically scopes stick with the SynchronizationContext in this case. Another way to think about that is that the scopes have an affinity with a specific async/await flow. This is perfect for server style applications (like ASP.NET Core web apps) since separate requests have isolated scope data. 

For UI applications (like MAUI) the [default mode](https://github.com/getsentry/sentry-dotnet/blob/bd62cf0421cc7a5d7b7804f8461fae00d47d43b8/src/Sentry.Maui/Internal/SentryMauiOptionsSetup.cs#L37-L36) is Global mode... in this case you don't get a separate scope stack for each synchronization context. Instead the scope stack is a singleton and changes you make to any scopes on the stack will be persisted for that scope (and any child scopes that get cloned from it) for the duration of the application.

If you modify the [code for the OnCounterClicked event handler](https://github.com/getsentry/sentry-dotnet/blob/28bd2a88b2dcc24ed288d4a862a6808c6ac4bfbc/samples/Sentry.Samples.Maui/MainPage.xaml.cs#L30-L46) in Sentry.Samples.Maui to look instead like this:
```diff
    private void OnCounterClicked(object sender, EventArgs e)
    {
        _count++;
+        SentrySdk.ConfigureScope(scope => scope.SetExtra("Click Count", _count));

        if (_count == 1)
        {
            CounterBtn.Text = $"Clicked {_count} time";
        }
        else
        {
            CounterBtn.Text = $"Clicked {_count} times";
        }

        SemanticScreenReader.Announce(CounterBtn.Text);

        _logger.LogInformation("The button has been clicked {ClickCount} times", _count);
    }
```

... then you'll see that any exceptions that get sent to Sentry when you click on the `Throw and Capture Exception` button will also have a `Click Count` in the _Additional Data_ section:
<img width="921" alt="image" src="https://github.com/getsentry/sentry-dotnet/assets/728212/d7f4c9e3-87e0-451c-b825-b96a98200766">

Depending on how you're handling authentication and authorization in your application, you should be able to do something similar to this.

Alternatively, you could use [SentryOptions.SetBeforeSend](https://docs.sentry.io/platforms/dotnet/guides/maui/configuration/options/#before-send) to configure a hook that adds the information just before events get sent to Sentry.

**Comment by breyed** [comment]
Thanks for the detailed explanation of how `ConfigureScope` works. That’s just what I needed to know. You may want to add that to your documentation.

My one remaining question is the purpose of `SentryUser.Segment`. I tried setting that in my code but haven’t seen it anywhere on sentry.io when looking at an issue.

**Comment by jamescrosswell** [comment]
> My one remaining question is the purpose of `SentryUser.Segment`. I tried setting that in my code but haven’t seen it anywhere on sentry.io when looking at an issue.

It looks like [this property has been deprecated](https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/#dsc-specification) in Sentry. I'll add a ticket to deprecate/remove this from the .NET SDK as well. Thanks for the heads up and the feedback!
