### ISSUE TITLE
Missing request information from captures exceptions

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dotnet#3504]
### Package

Sentry.AspNetCore

### .NET Flavor

Other

### .NET Version

8.0.0

### OS

Other

### SDK Version

4.8.1

### Steps to Reproduce

1. Create API endpoints in AWS lambda using API Gateway v2 proxy integration
2. Instrument the Sentry SDK with the following config:
```
SentrySdk.Init(options =>
{
options.Dsn = "...";
options.Debug = true;
options.DiagnosticLevel = SentryLevel.Error;
options.AutoSessionTracking = false;
options.TracesSampleRate = 1.0;
});
```
3. Trigger an error in the api gateway.

### Expected Result

Captured exceptions have the API request information (body, routes). 

### Actual Result

The captured exceptions do not have the information automatically added. Errors captured outside the API gateway do contain the request information as expected, the issue seems to affect only API gateway errors. 

Setting `MaxRequestBodySize` to `always` does not have any effect in the behaviour. 

A possible workaround is to [manually add it using additional context](https://docs.sentry.io/platforms/dotnet/guides/aws-lambda/enriching-events/context/), but it requires additional configuration.

**Comment by bitsandfoxes** [comment]
Hey,
Instead of calling init explicitly (which "just" initializes the core package) I'd recommend something like we have here in our [AWS lambda samples](https://github.com/getsentry/sentry-dotnet/blob/main/samples/Sentry.Samples.Aws.Lambda.AspNetCoreServer/LocalEntryPoint.cs)
The SDK provides extension methods to i.e. `IHostBuilder` that allows it to setup all kinds of middlewares and integrations to provide the contexts you're looking for.
We also have some [docs](https://docs.sentry.io/platforms/dotnet/guides/aws-lambda/) here as well.
