### ISSUE TITLE
Sentry not emitting events set to trigger deliberately for dotnet

### ISSUE THREAD

**Issue by weshead** [getsentry/sentry-dotnet#352]
Please mark the type framework used:

- [X ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X ] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [X ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:
 .NET Framework 4.6.2
MVC 3.0.0.1
Sentry 2.0.1

Hello,
I am attempting to utilize Sentry in my .NET 4.6.2 MVC 3.0.0.1 application that is not emitting events set to trigger deliberately. I have attached a screenshot of the updates. To make the test as simple as possible - we implemented the package in the Application_Start() and manually registered an event, but the events are not making it to our account. This test case would only emit the event at the beginning when the application is running. 

Thank you for your help.

Fiddler Screenshot of traffic
![image](https://user-images.githubusercontent.com/1334889/73964970-e62bfe00-48d8-11ea-9cf8-8e1d8dda3578.png)

IIS Express Log
[iis-express-log-sentry-event-missing.txt](https://github.com/getsentry/sentry-dotnet/files/4166986/iis-express-log-sentry-event-missing.txt)

Github PR that implements Sentry.
![sentry-pr-screenshot](https://user-images.githubusercontent.com/1334889/73965452-cd701800-48d9-11ea-9cef-1576dcd7326a.png)

**Comment by bruno-garcia** [comment]
I can see you're disposing the SDK right after calling CaptureMessage. That means no event will be capture after calling Dispose.

Also, it's odd to CaptureException(this) from the constructor since the object hasn't finished being constructred yet. I'm not sure that'd be a valid scenario.

Did you try this one your local dev machine? Do processes need a proxy to access the Internet?
Can you try first one of the samples in this repo, like the console app? Just add your DSN to them and run.

In this sample: https://github.com/getsentry/sentry-dotnet-samples/blob/master/AspNetMvc5Ef6/Global.asax.cs

The SDK is correctly initialized. [Exception thrown here is captured correctly](https://github.com/getsentry/sentry-dotnet-samples/blob/master/AspNetMvc5Ef6/Controllers/HomeController.cs#L40).

**Comment by weshead** [comment]
Hey Bruno
Thank you very much for your observations and suggestions. I'm told by the dev that the screenshot I shared was a snapshot of the code that was a less than ideal representation. 

Regardless... the events started to appear in Sentry. My team is speculating that the project instance created in Sentry.io was not in a state to receive events. We are just intuiting this because it took 7 hours to register a "test" event created on Sentry.io, entirely.
![image](https://user-images.githubusercontent.com/1334889/73993937-59edfb00-4919-11ea-911c-0203d05fd082.png)

Your observations were correct. We were instantiating the code too early in the lifecycle. Your spotted our explicit CaptureException(this) calls in our custom exception handling in our application. These references were to test producing exceptions around unit tests we have written. We were concerned because they did not provide events, which prompted me to reach out and create an issue.

Bruno, you are a dotnet-warrior, and I am grateful to get your attention on this issue. Thank you again.

**Comment by bruno-garcia** [comment]
Glad the problem sorted out @weshead !
It shouldn't take more than 1 or 2 seconds for an event to show up in Sentry, even after creating a new account and a new project (I just tested to help a customer).

Anyway happy it's fixed. Let us know if you have further problems.
