### ISSUE TITLE
Unhandled exception not reported but .NET Serilog SDK.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-dotnet#3531]
### Package

Sentry.Serilog

### .NET Flavor

.NET Core

### .NET Version

3.1.0

### OS

Any (not platform specific)

### SDK Version

4.9.0

### Steps to Reproduce

1. Download the repro: [TestSentry.zip](https://github.com/user-attachments/files/16598245/TestSentry.zip)
2. Update the DSN in startup.cs
3. Run the app

### Expected Result

The error thrown in the controller is recorded to sentry.

### Actual Result

Error is not recorded. 
I have tried initialising the .NET SDK directly but the error is not logged.

**Comment by bitsandfoxes** [comment]
Thanks for the repro. I can confirm this not working but after taking a quick peek I'm not entirely sure why that is. The SDK is definitely initialized. We'll have to investigate.

**Comment by samibn** [comment]
Any updates on this please

**Comment by bitsandfoxes** [comment]
Hey @rodolfoBee, @samibn!
So this seems to be a configuration issue rather than a bug. Here is what's happening:

1. The project is an ASP.NET Core app
2. The repro is using `Sentry.Serilog` and providing a DSN
3. Because the DSN is provided the SDK auto-initializes and hooks itself up to all kinds of things i.e. `UnhandledExceptionHandler`
4. The controller throws an exception
5. Since this is an ASP.NET Core project there is its own, built-in exception handling in place. The exception never bubbles up for the SDK to capture
6. The error goes unreported

To fix this and properly configure the project you'd need to add `Sentry.AspNetCore` package and make these modifications:

``` Program.cs
namespace TestSentry
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseSentry(options =>     //    <-- Initialize the Sentry ASP.NET Core integration
                    {
                        options.Dsn = "your-dsn";
                    });
                });
    }
}
```

and remove the DSN from the logger configuration.

Alternatively, if you do not want to use `Sentry.AspNetCore` you can add and handle those exceptions yourself i.e. 
```
app.UseExceptionHandler(errorApp => { /* your handling goes here. either capture or log the error */ });
```
