### ISSUE TITLE
Monitoring http client calls to Sentry

### ISSUE THREAD

**Issue by christopher-taormina-zocdoc** [getsentry/sentry-dotnet#357]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ X ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [ ] Mono
- [ X ] .NET Core

* Version: 2.1

Please mark the NuGet packages used:

- [ ] Sentry
- [ ] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ X ] Sentry.AspNetCore

* Version: 1.2.0

We want to monitor that the SentrySDK is correctly working in our application by having it emit metrics to our monitoring service.The firs option we've explored was to add this functionality http client directly through a handler, but the `SentryHttpClientFactory` option is internal, and the two options around configuration (`ConfigureHandler` and `ConfigureClient`) do not allow us to add an additional handler as it needs to be passed in when constructing these objects. Our current solution has been to implement our own `IDiagnosticLogger` and decide when to record these kinds of metrics based on some string parsing of the message that is passed to the Log function. Can the `SentryHttpClientFactory` option be made public to allow this level of custom configuration?

**Comment by bruno-garcia** [comment]
Firstly, It makes sense to expose a way to add decorating `HttpMessageHandler`s.

Today we don't expose `SentryHttpClientFactory` or a way to override the factory used internally because some parts of the SDK (for example `RetryAfterHandler`) we wouldn't want to be left out of the handler pipeline.

That said, I agree it makes sense to add a hook for the kind of scenario you need but I hope we can get somewhere which doesn't include exposing the whole factory and a way to replace it altogether.

Would it help if we changed the signature from `Action<HttpClientHandler, Dsn>` to `Func<HttpClientHandler, Dsn, HttpClientHandler>` instead? This would allow you modify as well as return a totally new instance if you will, so the decorating approach would work here.

**Comment by christopher-taormina-zocdoc** [comment]
@bruno-garcia Yeah I think that would solve this need pretty well.

**Comment by bruno-garcia** [comment]
@christopher-taormina-zocdoc came up with a second proposal:

https://github.com/getsentry/sentry-dotnet/pull/359

If that'll work for you, I'll merge and make a release.

**Comment by christopher-taormina-zocdoc** [comment]
@bruno-garcia I think that will do fine. Thanks for the help!

**Comment by bruno-garcia** [comment]
Btw it's been released: https://github.com/getsentry/sentry-dotnet/releases/tag/2.0.3

Feel free to reopen if there's some issue.
