### ISSUE TITLE
logcat attachment can't be previewed in Sentry

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#3703]
### Integration

sentry-android

### Build System

Other

### AGP Version

Not sure, using .NET build tools

### Proguard

Enabled

### Version

7.14.0 

### Steps to Reproduce

Logcat is a text file. So even without building a customer viewer for it (suggested on the issue below), we could at least show it as text.

* https://github.com/getsentry/sentry/issues/61005

[Example event](https://sentry.sentry.io/issues/4891888819/events/142923af2aaa4c24a69d138424ee5d71/)

### Expected Result

![Image](https://github.com/user-attachments/assets/6379ef5a-ef12-4ef0-9f51-689c31247b3e)

### Actual Result

See the logs without the need to download it.

**Comment by bricefriha** [comment]
> this seems to stem from the symbol collector attaching this manually and not providing a proper mime-type

The `mime-type` we are attaching is `text/logcat` 
```csharp
new ByteAttachmentContent(bytes), "logcat.log", "text/logcat"); 
```
([LogCatAttachmentEventProcessor.cs, line 84](https://github.com/getsentry/sentry-dotnet/blob/5e5dece224da202cf8b7674ae5a2693c3f5cbbfb/src/Sentry/Platforms/Android/LogCatAttachmentEventProcessor.cs))

I think we could just change the `mime-type` to `text/plain` since Sentry's previewer [supports it](https://github.com/getsentry/sentry/blob/d4f5584da02f71f4c2a1a00792b9558c22df61db/static/app/components/events/eventAttachments.tsx#L38-L56).

Would there be any limitation in doing that?

**Comment by bitsandfoxes** [comment]
Fixed by https://github.com/getsentry/sentry-dotnet/pull/3711
