### ISSUE TITLE
Manually sent events do not get breadcrumbs from integration

### ISSUE THREAD

**Issue by josh-degraw** [getsentry/sentry-dotnet#378]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [ ] WinForms
- [ ] Xamarin
- [x] Other: Windows Service and Console App

Please mark the type of the runtime used:

- [x] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version:

Please mark the NuGet packages used:

- [x] Sentry
- [ ] Sentry.Serilog
- [x] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.0

I don't know if this is something that just can't be avoided, or if I'm just not doing it right.
But sometimes I want to sent an event to sentry that falls outside of the criteria I have specified for the NLog integration (e.g. send an event at a lower level than is configured to send to sentry, for a very specific use case such that I wouldn't want to enable it at that level globally).

When I do this, the resulting event does not have any breadcrumb information except for the breadcrumbs from other manual usages of `SentrySdk.CaptureEvent` or `SentrySdk.AddBreadCrumb`.

Example event capture:
```c#
var logger = LogManager.GetCurrentClassLogger();
logger.Info("I would expect this line to add a breadcrumb to the following event");
var ev = new SentryEvent
{
    Message = "blah",
    Level = SentryLevel.Info,
    Logger = logger.Name,
};
ev.SetExtra("extra", "extra");
ev.SetTag("tag", "Something");
SentrySdk.CaptureEvent(ev);
```
_Should_ I expect this to work, or would the threading / tasks in the NLog system prevent this from working like I'm expecting it to with Sentry?

**Comment by snakefoot** [comment]
Think there should always be two modes:
1. Isolated instances with support for Service Fabric and dependency injection. Where multiple services are living in the same process, and each service have their own isolated sentry-client.
2. Single shared instance that is accessed with static singleton by the entire application-process.

The second mode is often the default, and is the simple and most user-friendly approach. The first mode is good for advanced scenarios and for unit-testing.

Think it could be nice if the NLog-target could be initialized to run in both modes:
- Specify that NLog-target should create its own isolated sentry-instance
- Specify that NLog-target should use the static singleton sentry-instance

And probably have the static-singleton-instance mode as default, because it is most user-friendly mode. See also #370 where using multiple NLog-targets each with their own isolated sentry-instance.

**Comment by bruno-garcia** [comment]
> Single shared instance that is accessed with static singleton by the entire application-process.

Sharing state through static is just an API we can't run away from. It allows disconnected integrations to share breadcrumbs and other things.

> Isolated instances with support for Service Fabric and dependency injection. Where multiple services are living in the same process, and each service have their own isolated sentry-client.

I agree. Taking a `IHub` or `ISentryClient` is already the approach in the code based. It's at least used for unit testing but it would allow a refactor where we can vary the instance we pass in depending on some configuration. Right now things are mostly wired through `IHubAdapter.Instance` which is a singleton that points to the static entrypoint so that things wired together (different integrations share state). This way, anything a user calls explicitly via `SentrySdk.AddBreadcrumb` will use the same underlying instance as the integrations that take a `IHub` in the constructor.

i.e:
https://github.com/getsentry/sentry-dotnet/blob/75bfe9dc40d849f15b32eb06cf5eee2c37564a89/src/Sentry.Extensions.Logging/SentryLogger.cs#L19-L23

I would expect the snippet from @josh-degraw to work though. Could this be some NLog special handling? If you step into the `logger.Info`, does it go into the `IHub` field which points to the static `SentrySdk` and hence the same instance of `Hub` which you reach through directly calling `SentrySdk.CaptureEvent`?

**Comment by snakefoot** [comment]
Yes when looking at the Sentry source code, then the default HubAdapter will write to the static instance by default.

I guess one could have a race-condition if using NLog Sentry Target together with `<targets async="true">` , as the NLog AsyncWrapper introduces a small delay to optimize for batching.

**Comment by snakefoot** [comment]
@josh-degraw I would also expect your code to work, unless using custom IHub or having activated `<targets async="true">`. Is this the case?

**Comment by josh-degraw** [comment]
@snakefoot Yes, I do have the async wrapper enabled. That was my suspicion for the cause of the issue, as I have also had other odd things happen that I think are related to that, e.g. sometimes when certain events are sent to sentry from NLog it shows the NLog AsyncWrapper stack trace rather than the app stack trace (I do get the app stack trace as data though), but that may be for another issue.

**Comment by snakefoot** [comment]
Remember that you can declare multiple `<targets>`-section in your Nlog.config:

```c#
<targets>
   <target name="sentry" />
</targets>

<targets async="true">
   <target name="file" />
</targets>
```

Any reason why you are using `AsyncWrapper` around the Sentry-Target?

**Comment by josh-degraw** [comment]
@snakefoot, I might do that if that's the only issue here. No specific reason necessarily, I was just hoping to reduce latency in the app itself so I enabled the async wrapper for all targets since it's easier to declare it that way. But I guess since sentry itself is asynchronous in how the event queue works anywayit's probably an unnecessary extra indirection now that you've pointed it out. I'll close this issue for now and try changing that here and see if that fixes the issue.

**Comment by snakefoot** [comment]
Yes there is a lot of action going on in the Sentry-Target to capture state, which the logging thread will be punished by.

Surprised that the native Sentry-Client performs capture of stacktraces, and not just rely on the stacktrace from the Exception (From you comment "shows the NLog AsyncWrapper stack trace ")
