### ISSUE TITLE
SentrySdk.MinimumEventLevel - how can I check what it is set to?

### ISSUE THREAD

**Issue by CADbloke** [getsentry/sentry-dotnet#441]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [X] WPF
- [ ] WinForms
- [ ] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [X] .NET Framework
- [ ] Mono
- [ ] .NET Core

* Version: 4.8

Please mark the NuGet packages used:

- [X] Sentry
- [X] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [ ] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version:  2.1.1.0

I want to check the `MinimumEventLevel` The Sentry sink for Serilog is set to. How can I do that?

**Comment by bruno-garcia** [comment]
@CADbloke that value is part of SerilogOptions: 

https://github.com/getsentry/sentry-dotnet/blob/1e6101d477a8b65728bfe70a2b3156aff8be2404/src/Sentry.Serilog/SentrySerilogOptions.cs#L27

Unless you've changed it during initialization, the default value is declared there.
Is that because you bind the configuration value with Serilog configuration system? I'm not sure I follow.

**Comment by CADbloke** [comment]
Sorry, you’re right. If I want to read it I need to get it from Serilog. Duh. 
Sorry about that.

**Comment by bruno-garcia** [comment]
No worries, glad it's sorted out!
