### ISSUE TITLE
Runtime.Current.Version null on Windows 10 2004 .NET Framework 4.8

### ISSUE THREAD

**Issue by KristianWedberg** [getsentry/sentry-dotnet#443]
`Runtime.Current.Version` is `null` on .NET Framework 4.8 after upgrading to Windows 10 2004, build 19041.264.

I expected it to be "4.8".

Also, to avoid this becoming `null` again later, I suggest making `Version` the largest version where the build number is not too large. Showing e.g. 4.8 on a 4.8.1 installation is much better than getting a `null`.

Cheers,
Kristian

**Comment by bruno-garcia** [comment]
Transfered to this repo not to get lost on that repository as we plan to make a monorepo

**Comment by KristianWedberg** [comment]
There's no "4.8.1" yet as you say, that was just an example of a future version that would again return `Runtime.Current.Version` as `null`, unless as I suggested setting any larger unknown build numbers to the last known .NET Framework version.

**Comment by bruno-garcia** [comment]
I believe .NET Framework will not have any more releases after `4.8`.

**Comment by CADbloke** [comment]
+1 - same issue here.

I found the version of 4.8 in the registry at `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\` key is "Version", mine is `4.8.04084`, "Release" is `528372`. Reference: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

You could use the old code and just check for builds > 528040 since 4.8 is the end of the line. For now. Like VBA etc. 

The "Release" / build would be handy actually, I definitely have seen issues related to Windows 10 updates so it would be nice to know what actual release they are running.

**Comment by bruno-garcia** [comment]
This should be processed then by Sentry on the server:

https://github.com/getsentry/relay/blob/8a226679c5d7023df00a71da293fec798f0f248f/relay-general/src/store/normalize/contexts.rs#L57-L58

Could you please confirm what's the derived `runtime.name` and `runtime.version` in the event?

**Comment by bruno-garcia** [comment]
I see. The value is missing there on relay. I'll make a PR to add support.

**Comment by bruno-garcia** [comment]
It was actually missing two values.

Thanks for raising this. The SDK will report the right value from the next release.
Sentry will report also 4.8 even for apps on old SDK version once we release my patch on Relay
