### ISSUE TITLE
Support for Release Health and Performance Monitoring

### ISSUE THREAD

**Issue by bddckr** [getsentry/sentry-dotnet#502]
Please mark the type framework used:

- [ ] ASP.NET MVC
- [ ] ASP.NET Web API (OWIN)
- [ ] ASP.NET Core
- [ ] WPF
- [x] WinForms
- [x] Xamarin
- [ ] Other:

Please mark the type of the runtime used:

- [ ] .NET Framework
- [x] Mono
- [x] .NET Core

* Version: The latest stable for both, that is .NET Core 3.1.401 and Xamarin.Android 11.0.2.0.

Please mark the NuGet packages used:

- [ ] Sentry
- [x] Sentry.Serilog
- [ ] Sentry.NLog
- [ ] Sentry.Log4Net
- [x] Sentry.Extensions.Logging
- [ ] Sentry.AspNetCore

* Version: 2.1.6 of both.

---

It looks like both [Release Health](https://docs.sentry.io/product/releases/health/) and [Performance Monitoring](https://docs.sentry.io/product/performance/) aren't (directly?) supported.

Is there any way for me to utilize these platform features, perhaps with the underlying `Sentry.Protocol` package? I'm totally fine with having to identify and generate session details myself, as well as performance data.

Ultimately I'm interested in filling the Sentry release's user information, as well as gain some insight into our client apps' performance when it comes to hitting our servers.

**Comment by bruno-garcia** [comment]
@bddckr we're planning to start working towards adding both release health and performance support to .NET soon.

@lucas-zimerman created already some support for both features on an external library: https://github.com/lucas-zimerman/sentry-dotnet-performance-addon

We'll use this issue to track progress.

**Comment by bruno-garcia** [comment]
You've selected WinForms and Xamarin. What do you use on the server?

**Comment by bddckr** [comment]
We're using Sentry on the server and our web frontend, too. I wasn't mentioning this as I'm primarily interested in device-only insight for now and I'm not yet sure on buy-in from the rest of the teams for any potential cross-team insight we might be able to get via Sentry.

For my purposes (and after just a quick glance for now) it looks like Lucas' library does exactly what I am after! Thanks for the pointer and great to hear it's on the roadmap.

**Comment by bruno-garcia** [comment]
Just to clarify. You're looking to use this on a Xamarin and WinForms app then, correct?

To help us prioritize things, could you describe a bit the targets? The WinForms app, is it .NET Framework or core? And what versions? Xamarin iOS and Android or something else?

**Comment by bddckr** [comment]
Yes, exactly. We have two apps:
* Xamarin.Android (not Forms or anything, literally just a "native .NET Android app" by just using the C#<->Java bindings)
* .NET Core for Windows and macOS

**Comment by lucas-zimerman** [comment]
Haven't tested on WinForms but it should work just fine since it works well on Xamarin.Forms (on Android) and the SDK calls are based on the official SDKs so it'll not be complicated to change to the official implementation once it's done. (Except for the IsolateTracking, not sure how that could be done on the official SDKs using a single Hub.)

**Comment by mol** [comment]
We're using Sentry in Mailbird, which is a WPF app running .NET 4.7.2, and we'd also love support for both health and performance monitoring :)

**Comment by bruno-garcia** [comment]
To clarify Release Health isn't getting in 3.0.0.

I'be raised an issue to track Release health for Client apps (WPF, Console, WinForms, Xamarin, UWP, Blazor, etc): https://github.com/getsentry/sentry-dotnet/issues/713

I also created one for Server Apps (like ASP.NET and ASP.NET Core): https://github.com/getsentry/sentry-dotnet/issues/714

For performance monitoring, I created:

Performance Monitoring Manual API (so you can track it in any .NET app programatically):
https://github.com/getsentry/sentry-dotnet/issues/715

And ASP.NET Core auto instrumentation which creates transactions per request automatically:
https://github.com/getsentry/sentry-dotnet/issues/716

**Please upvote the issue that's most relevant to you**. It can help us prioritize things.

I'll close this issue now since we'll be addressing it through those.
