### ISSUE TITLE
Enumerate all .NET Framework installations

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#531]
PlatformAbstractions API is able to enumerate all .NET Framework installations.
An integration could be created to do so on .NET Framework.
The data would fit on a `Context` called `.NET Framework`

Basically: NetFrameworkInstallIntegration class that implement ISdkIntegration
and it'll call hub.AddEventProcessor(s => s.Contexts[".NET Framework"] = GetInstallations()
this method GetInstallations will returns an object that lists all installations.

The integration could be added by default on #if NET461 but there should be a way to opt-out (like `options.RemoveIntegration<NetFrameworkInstallIntegration>();`

**Comment by lucas-zimerman** [comment]
@bruno-garcia IHub doesn't implement AddEventProcessor (but since Register exposes SentryOptions you would be able to add the EventProcessor on it).
Also, as far as I know, `options.RemoveIntegration<NetFrameworkInstallIntegration>();` wouldn't stop the events to get attached with the .Net List.

Lastly, I feel this feature could be sorted with an event processor (as showed on PR), but I can rollback to the SdkIntegration solution.

**Comment by bruno-garcia** [comment]
> Also, as far as I know, options.RemoveIntegration<NetFrameworkInstallIntegration>(); wouldn't stop the events to get attached with the .NET List.



What do you mean by the event getting attached to .NET List?
