### ISSUE TITLE
Scope data from async methods missing

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#54]
Given the following code:

```c#
private static async Task doThings()
{
    SentrySdk.AddBreadcrumb("things crumb");
    SentrySdk.ConfigureScope(o => o.SetTag("tag1", "a"));
}

public static async Task<int> Main(string[] args)
{
    using (var sdk = SentrySdk.Init(s =>
     {
          s.Dsn = new Dsn("<url>");
     }))
    {
        await doThings();
        SentrySdk.CaptureMessage("Sample event");
    }

    return 0;
}
```

No breadcrumbs/tags are available or sent to the Sentry endpoint.  If I convert the function to non-async, the breadcrumb and tag is available.

**Comment by bruno-garcia** [comment]
Your snippet won't compile for me because the `async` method `doThings` doesn't have an `await`:
![image](https://user-images.githubusercontent.com/1633368/42867085-cae59e32-8a6e-11e8-92d8-7a0c41afd65b.png)

If I add a `await Task.Yield();` to schedule the continuation (and get the compiler happy), the event gets sent. But as your said, without the tag and breadcrumb.

![image](https://user-images.githubusercontent.com/1633368/42867213-2f6d6aba-8a6f-11e8-87e5-9ed91b0df4fd.png)

I found the issue in the code and it's indeed a bug. 
Thanks for raising this!
