### ISSUE TITLE
Request: Populate basic user information

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#57]
The previous C# SDK would automatically populate the Username, IP, etc.  I see that we can manually add it using an event handler, but it would be useful to populate automatically if not provided.

**Comment by bruno-garcia** [comment]
We opted to not send the `Environment.UserName` due to privacy concerns.
You can always initialize the sdk and immediately set the user to the scope:

```csharp
SentrySdk.Init();
SentrySdk.ConfigureScope(s => s.User = new User(..));
```

We could build a convenience method that creates a user perhaps? Although the only thing we can do is really get one of the machine's IP address (as it might contain multiple) and the Windows username.

**Comment by lunim** [comment]
Thanks for the follow-up, I'll add it as described.
