### ISSUE TITLE
Consider changing SentryOptions.SampleRate to non-nullable double

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-dotnet#749]
Newly added traces sample rate is a non-nullable double, which matches the guidelines and Java's implementation:

https://github.com/getsentry/sentry-dotnet/blob/e62781ca688b9ebadf41434f90b3382262d14c91/src/Sentry/SentryOptions.cs#L397-L419

Existing event sample rate option is instead a nullable float:

https://github.com/getsentry/sentry-dotnet/blob/e62781ca688b9ebadf41434f90b3382262d14c91/src/Sentry/SentryOptions.cs#L144-L171

I suggest we change the event sample rate to a non-nullable double as well to be consistent with other SDKs and the guidelines.

**Comment by bruno-garcia** [comment]
The problem is that it becomes hard to know when a value has been set explicitly by a user or not, when the user defined value takes presedence over some configuration-bound value (say aspnetcore reading configuration and applying to the model, without overriding). For that reason I prefer having `null` be the explicit: No one has set a value here. That said, I'm OK with changing this it folks decide that's best

**Comment by SimonCropp** [comment]
does SampleRate  need to have a get? can we make it a set only, then it can be a non null set property, but a nullable field

**Comment by bruno-garcia** [comment]
Worth noting some Sentry SDKs have the following behavior:

If `TraceSampleRate` is not set. No transactions are emitted from the SDK. 
If `TraceSampleRate` is set to `0`, and a transaction is created with a already defined `sampled` flag (i.e: An incoming HTTP request includes a `sentry-trace` header with a `sampled=1` flag), the SDK will continue that trace. Meaning, it'll emit a transaction, and forward the trace-id to all outgoing HTTP requests.

There's more in the docs: https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/configuration/sampling/#configuring-the-transaction-sample-rate
