### ISSUE TITLE
Offline caching

### ISSUE THREAD

**Issue by jwillmer** [getsentry/sentry-dotnet#80]
I am using sentry in an offshore environment and depending on the position of the vessel we don't have an internet connection. How can I cache the messages and send as soon as the internet is back on?

I saw that other implementations have same needs (JS with offline first progressive web apps). So please think about handling this as a feature request - workaround is also welcome.

**Comment by bruno-garcia** [comment]
@jwillmer Thanks for letting us know of your use case.

We'll take it into account when prioritising.
In fact, we'll need this to support Xamarin.

**Comment by cpwood** [comment]
@jwillmer I have vaguely similar requirement: caching data until the user gives their approval for it to be sent to sentry.io in accordance with our privacy policy.

I ended up implementing my own simplistic ISentryClient which stuck everything in a `ConcurrentQueue<Tuple<SentryEvent, Scope>>`. This then gets bound via `HubAdapter.Instance.BindClient()`.

Then, upon the user giving consent (or, in your case, the internet connection being established), it creates an instance of `SentryClient` within a `using` block and sends the data to sentry.io by calling `CaptureEvent()` for each queued item.

Maybe a similar approach could work for you?

**Comment by bruno-garcia** [comment]
@cpwood that's an interesting usage of the API.
One thing to note though is that `SentryClient` internally hold the `HttpTransport` which in turn has an `HttpClient`.

That means that `SentryClient` should be re-used throughout the lifetime of the app and only disposed when the app is about to terminate (which will flush any queued events).

For caching in disk, one options is refactoring `BackgroundWorker` so that the in-memory queue becomes a strategy which I can replace with something that will store to disk and read from disk before calling the transport. The downside of this is the API would have to offer `async` methods now which would be a leaking abstraction.
Another options is to implement a new `ITransport` that will do the caching. Since that contract is `async`.

So today what we have is:

> `SentryClient` -> `BackgroundWorker` -> `HttpTransport` -> `HttpClient`

Where the first two interfaces offer sync APIs and the two latter offer async APIs. The BackgroundWorker is the one with an internal `Task` calling the transport and awaiting response.

What I propose is to create a decorator `Transport` that will write the `SentryEvent` to disk upon `CaptureEventAsync` and will internally hold a `BackgroundWorker` holding a standard `HttpTransport`.

Looking like this:

> `SentryClient` -> `BackgroundWorker` -> `CacheTransport` -> `BackgroundWorker` -> `HttpTransport` -> `HttpClient`

What do you think?

**Comment by cpwood** [comment]
@bruno-garcia that would be amazing! 

I did consider doing something with the `BackgroundWorker` myself and came to similar conclusions. For me, the imperative was to "get the job done quickly" so I didn't go down the road of refactors and pull requests, but it certainly is a better way of achieving the objective I had.

For background information, our situation is that we have a Windows application installed on desktops. The code that's running will collect personally-identifying information, so we can't just upload it without permission (especially since GDPR).

Connected with that, one other requirement I've brushed up against and worked around is that I need to de-obfuscate our stack traces (since the deployed code is obfuscated). Since Sentry doesn't do this for us (at least not with Babel.NET), we wrote some server-side code that will do that. Our server will basically then act as a de-obfuscating proxy:

> `Client Application` ->`De-obfuscating Proxy` -> `Sentry`

Getting the library to post to _our_ server required a bit of an inelegant kludge. I'm guessing the ability to define a new transport would also allow us to loop our proxy in more elegantly? i.e.

> `SentryClient` -> `BackgroundWorker` -> `CacheTransport` -> `BackgroundWorker` -> `OurCustomHttpTransport` -> `HttpClient`

**Comment by bruno-garcia** [comment]
@cpwood sure! The composition should still allow you inject your own `ITransport` at the last level and support your use case.

Interesting scenario regarding obfuscation. I'm not familiar with [Babel.NET](http://www.babelfor.net/) I wonder how many other Sentry users have such requirements (obfuscate their assemblies and de-obfuscate on the backend before sending to Sentry).

Do you intend to open source this service? Are you using sentry.io or self hosted?
Such story could be a nice addition to the .NET support from Sentry.

/cc @mitsuhiko

**Comment by mumat** [comment]
Has there been progress on the offline caching? We currently rely on a custom infrastructure on client side (Xamarin mobile App) combined with our own proxy to convert the crash reports to sentry format. We think we are loosing many reports due to our custom infrastructure and would like to move to a sentry only solution but we need the support for offline caching.

**Comment by mumat** [comment]
Unfortunately I don't have too much time, but I guess I could manage to spare some for a project like this. @bruno-garcia you mentioned that we could discuss the design ahead of time?

**Comment by bruno-garcia** [comment]
@mumat Sure. We could start with a chat on [Discord](https://discordapp.com/invite/Ww9hbqr). Then raise a new issue with some points and then review the PR.

**Comment by bruno-garcia** [comment]
#557 added support, we're going to iron out some details in the retry mechanism: OK to retry if offline but not if server error etc.

But basically this is coming soon! I hope y'all can give it a try and give feedback.

**Comment by bruno-garcia** [comment]
This version has offline caching support: https://www.nuget.org/packages/Sentry/3.0.0-alpha.6

You can enable it by setting a path to `CacheDirectoryPath`. The SDK will create subfolders to deal with the files coming in.

I've tried it out with Xamarin and it worked well. So the crash is stored to disk, the app dies often it can't flush out to the network before it dies or it's offline. Then on restart it sends the event.

If there's a crash on disk from the previous run, by default it blocks `Init` up to 1 seconds trying to flush it out. So a restart after a crash could be a bit slower for that reason. [You can opt-out by setting a TimeSpan.Zero to CacheFlushTimeout](https://github.com/getsentry/sentry-dotnet/blob/429c58bbaa2aae2ad02c772d6f04c19e3039481a/src/Sentry/SentryOptions.cs#L384).

This feature exists so that if your app is crashing each time it's launched, events will never be sent to Sentry because it gets killed before the async event submission can happen.

Be aware that the SDK expects to be using that directory on its own. So if you have multiple instances of your app, you'll need create a subfolder per pid (process id) and deal with it on your own (like on startup check if a previous run had some folder there that needs to be processed).

**Comment by Tyrrrz** [comment]
@bruno-garcia are we still missing anything on this?

**Comment by bruno-garcia** [comment]
@Tyrrrz All we need is to GA 3.0.0 so "soon TM"

**Comment by bruno-garcia** [comment]
3.0.0 is out with offline caching!

`CacheDirectoryPath` is the option, if a path is set, it picks up. Proper docs on docs.sentry.io will follow (see #770)
