### ISSUE TITLE
Add general usage example in README

### ISSUE THREAD

**Issue by jwillmer** [getsentry/sentry-dotnet#82]
I know you link to examples but 90 percent of the time I just need to send an exception. Why do I need to dig through code for this use case? Your previous repo did a great job in displaying all what is needed to get started in the README.

**Comment by bruno-garcia** [comment]
I avoided up to this point because documenting: `SentrySdk.CaptureException(e);` would not be the way to go if you are using the Logging or ASP.NET Core integrations. 
You can always do that but you might instead prefer on of the other ways like `LogError` or take `ISentryClient` via dependency injection.

I agree these are advanced scenarios and a small sample on how to get started would be valuable.

Thanks for your feedback.

**Comment by bruno-garcia** [comment]
@jwillmer 

Although, isn't this section enough of an introduction: 

https://github.com/getsentry/sentry-dotnet/blob/7ba0b21d4618ed588810cefffa11ea5a43ff92a8/README.md#without-any-framework-integration

**Comment by bruno-garcia** [comment]
@jwillmer 
I've merged into master:

https://github.com/getsentry/sentry-dotnet#basic-usage-without-framework-integration

Could you please let me know if that's what you had in mind?

**Comment by jwillmer** [comment]
Looks good, thx.
