### ISSUE TITLE
Add MVC action as span

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#869]
We could start a span when the controller action starts and finish end it ends.
ActionFilters is a good candidate.

**Comment by Tyrrrz** [comment]
I've looked into action filters and I'm not sure they are applicable for this problem.

Local filters are applied using attributes on actions or controllers, which we can't do for obvious reasons.
Global filters are added via `services.AddControllers(o => o.Filters.Add<...>())`, which we also don't have access to. We could try to get the controllers service registration and try to inject the filter that way, but that would make it so that `services.AddSentry()` would HAVE to be called last. And even then, I'm not sure if it's actually doable.

I think if we were to do this, we have to get the action in the middleware somehow. I'm not entirely sure what's the best way to do it.

Thoughts?
