### ISSUE TITLE
Feature Request: Allow Breadcrumb data to accept objects as values

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry-dotnet#88]
Currently, the breadcrumb accepts additional data as a dictionary of <string,string>.  Allowing objects as values would remove the need for end-users to serialize.  Currently, the SentryEvent extras accepts <string,object>, updating breadcrumb to be the same would be useful.

**Comment by bruno-garcia** [comment]
Currently Sentry doesn't really support a serialized object in its `data` bag.
Serializing an object shows up like this:

![image](https://user-images.githubusercontent.com/1633368/44662508-3e857d80-aa0e-11e8-868a-e8b533d2c898.png)

I think this could be a feature request opened on [Sentry](https://github.com/getsentry/sentry) and if implemented, change the SDKs which is a coordinated thing now as align the API.

**Comment by bruno-garcia** [comment]
@lunim I'll close this as per my comment above.
If Sentry itself is changed to support breadcrumbs value as objects we can reopen this and implement support in this SDK.

**Comment by boukeversteegh** [comment]
It seems that this feature is now implemented:

https://github.com/getsentry/sentry-javascript/issues/623#issuecomment-720981987

Can we reopen this perhaps?

**Comment by bruno-garcia** [comment]
It's a bit of an issue to take `object` because often people put data that can't be serialized by default and we have issues.

Forcing this to be `ISerializable` will introduce friction, since one would need to implement the interface and get serialization done. To be quite honest at this point I would prefer the caller serializes it.

**Comment by boukeversteegh** [comment]
For me it would be fine to serialize the data client side. for example I
have protobuf messages that are easily serializable to JSON  and I would
like to display them in the breadcrumbs, as json objects.

For this, only one extra overload would be needed, which accepts a JSON
serialized string

On Tue, 3 Aug 2021 at 23:29, Bruno Garcia ***@***.***> wrote:

It's a bit of an issue to take object because often people put data that
can't be serialized by default and we have issues.

Forcing this to be ISerializable will introduce friction, since one would
need to implement the interface and get serialization done. To be quite
honest at this point I would prefer the caller serializes it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/getsentry/sentry-dotnet/issues/88#issuecomment-892178914>,
or unsubscribe

**Comment by bruno-garcia** [comment]
It currently accepts `string` as a value so it should already work if you're serializing before setting it.

There are different extension method, for example accepting a value tuple:

https://github.com/getsentry/sentry-dotnet/blob/6b60f9cffe1ceb507cbc0d0075afb9ada870603b/src/Sentry/IHasBreadcrumbs.cs#L44

**Comment by boukeversteegh** [comment]
I see, thanks for your reply. Looking at it, I have two questions:

- How do I use this overload? `SentrySdk.AddBreadCrumb` is the documented approach, but this overload is not available on the `SentrySdk` static class.
- In the source code, it seems that it adds a KeyValuePair to the `Dictionary<string,string>`, so we're not really setting the top-level data object.

Thinking about it more, I suppose that as long as the Sentry UI displays the string values as is, including whitespace and linebreaks, then it doesn't really matter whether or not it understands JSON, since we can include a pretty-printed json string in the breadcrumbs.

I will experiment with this approach.

**Comment by SimonCropp** [comment]
@boukeversteegh @lunim looks like @bruno-garcia answered this one.

**Comment by boukeversteegh** [comment]
Sorry to keep this open.

My current workaround is to pass a dictionary like this;

```c#
Dictionary<string, string> data = new();
data.Add(key, JsonFormatter.Format(message)); // formats a Protobuf message to JSON
SentrySdk.AddBreadcrumb(description, category, null, data);
```
It's just shown as a string, and the json structure is not handled in any way, but it's workable for small messages. Haven't tested yet with formatted/multiline strings.

Closing this is OK I suppose. Thanks!
