### ISSUE TITLE
Add overloads to TransactionTracer.Finish() that takes HttpStatusCode instead of SpanStatus

### ISSUE THREAD

**Issue by ibedard16** [getsentry/sentry-dotnet#914]
Recently, I had to write a custom sentry tracing implementation. It wasn't hard, but there were some things I wish were better.

One thing that would be nice is the ability to call `transaction.Finish()` with an HttpStatusCode. There were already overloads that accepted types of `Exception` and `SpanStatus`, but neither of those really helped my use-case.

The `Exception` overload works, but the project doesn't always use the specific `Exception` types handled by the `SpanStatusConverter.FromException`. However, it does try to return accurate status codes in every exception thrown.

The `SpanStatus` overloads might have helped a little bit, but I would have needed something like the `SpanStatusConverter` class, which I couldn't use because it was `internal`.

I initially considered asking to expose the `SpanStatusConverter` class... but the more I thought about it, I would much rather have been able to call `Finish()` with an `HttpStatusCode` directly. I'm not really sure anyone should need to dive into the Sentry internals to figure out what a `SpanStatus` is in order to call this function.

**Comment by bruno-garcia** [comment]
Sounds like this could be an extension method to `Transaction`, but just like the Exception approach, it's likely something users would want to extend. Less in this case since `HttpStatusCode` is an enum and users are not going to have their own types like `Exception`.

We could consider adding this but for the time being we're avoiding extending the public API while we discuss some general approach to collecting spans.

For the time being I suggest you create an extension to `Transaction` with your own mapping but lets keep this issue open and update as we go

**Comment by Tyrrrz** [comment]
@ibedard16 you can also just copy-paste this method in your own code:

https://github.com/getsentry/sentry-dotnet/blob/86dab4c93316960e724d2b869f4b2f56ab5332c5/src/Sentry/SpanStatus.cs#L82-L99

**Comment by SimonCropp** [comment]
seems this should be resolve-able with the the above suggestions. @ibedard16 please let us know if this is still a problem for you
