### ISSUE TITLE
transaction.Finish() overrides the transaction status set via the public setter with the default parameter (Ok).

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet#919]
repro:

var tran = startTransaction();
tran.Status = SpanStatus.Error;
tran.Finish();

That's due to:
public void Finish(SpanStatus status = SpanStatus.Ok)

Suggestion: Have a proper parameterless method.
Also, don't set Ok if nothing was set. Sentry has a status: 'unknown' when nothing is set. Verify the spec/other SDKs if they default to OK or just send it without status.

**Comment by Tyrrrz** [comment]
@bruno-garcia I think a better design would be to disallow mutating the `Status` property from anywhere but the `Finish(...)` method.

Otherwise we will also have problems with `ISpan.Finish(Exception ex)` overload since that infers the status from exception and overrides it.

We can, of course, also make it so that `ISpan.Finish(Exception ex)` only overrides the status if it's presently set to `Unknown`. Either way, that's going to be a breaking change. What's your opinion?

**Comment by Tyrrrz** [comment]
Also note that Sentry has `UnknownError`, not `Unknown`, which might be the reason `Ok` was chosen as default instead -- to avoid defaulting to a status that implies the presence of an error.
