### ISSUE TITLE
Device Free memory should be unsigned long

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-dotnet#929]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Both 

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
.NET 2.0.8 (but I checked that it's the same with 3.1.1)

### Steps to Reproduce

Set Device Free memory to a negative value.

### Expected Result
Event with a negative value.

What you thought would happen.

### Actual Result
![image](https://user-images.githubusercontent.com/8229322/113886631-37fb3d00-9797-11eb-8cdc-083cb5736590.png)

What actually happened. Maybe a screenshot/recording? Maybe some logs?
The above picture.

Since Sentry only expects an unsigned integer, it would be nice to change the value from long? to unsigned long?

**Comment by bruno-garcia** [comment]
Note that this is a breaking change

**Comment by lucas-zimerman** [comment]
The SDK could discard negative values when serializing, signed long will do the job for years :D

**Comment by bruno-garcia** [comment]
@lucas-zimerman I'm more interested in knowing where that negative value comes from. Perhaps validating the value there before setting

**Comment by lucas-zimerman** [comment]
it came from my side, I was converting the total available memory from long to int and that's what happened (manually set the value outside the SDK)

**Comment by bruno-garcia** [comment]
The reason I'm not a fan of not serializing the value is that it hides the problem. Suddenly some events come in without the value and the user is left wondering why. Raises an issue and we're left with trying to reproduce it. We either change the data-type to `unsigned` or leave it as-is so the caller can fix on their end.

**Comment by Tyrrrz** [comment]
Hmm, this looks like "working as expected" to me. An invalid value was set manually and then Sentry discarded it with an error message on ingestion.

Using `ulong` instead of `long` would only make the conversion explicit but will still allow for this:

```csharp
var foo = -1L;
var ufoo = (ulong) foo; // the value will be 18446744073709551615
```

This looks like it creates a far more dangerous issue.

See: https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYAMBYAUBgRjzwDcBDMAAgDMB7WygXkoFoCAZAblIsojobMAFBAA2tKAHMAlDXrdceVAQCcIgdM5A==

In general, I think relying on the value type's bit size or signdness for validation is a bad idea. The validation should happen at runtime, either on client side or server side (as it is now). That is, until refined types become a mainstream feature of every language.

**Comment by lucas-zimerman** [comment]
Fair enough, then, I believe it's ok to close this issue.
