### ISSUE TITLE
Attach to global exception handler without wrapping in a using statement

### ISSUE THREAD

**Issue by ChaosCA** [getsentry/sentry-dotnet#96]
Hey there. I'm trying to port my application from the old client to this one but I'm running into an issue. It's not really possible for me to be using the `using` keyword for calls that might have an exception, I don't have control of the event loop.

However I still like to record exceptions and messages. To test I used the following bit of code:

```
		Sentry.SentrySdk.Init("my-dsn");
		Sentry.SentrySdk.AddBreadcrumb("Started", "Resource start");
		Sentry.SentrySdk.AddBreadcrumb("Some failure", "Resource start failed", level: Sentry.Protocol.BreadcrumbLevel.Warning);
		Sentry.SentrySdk.CaptureMessage("Uh oh", Sentry.Protocol.SentryLevel.Warning);
		Sentry.SentryEvent logEvent = new Sentry.SentryEvent(new Exception("Error with questions"));
		logEvent.User.Username = "testing";
		logEvent.User.Id = "123";
		Sentry.SentrySdk.CaptureEvent(logEvent);
```

However nothing is sent to Sentry. Is there anyway to not use the `using` statement and instead make my own factory for the instance so it can be used in a similar manner to the old SDK? 

If an exception happens in the application I would like Sentry to log it, even if it's uncaught in a `using` statement, but I can't seem to initialize it or keep the SDK created with my DSN so how would that be possible?

**Comment by bruno-garcia** [comment]
@ChaosCA thanks for raising this. I'll try to clarify:

`CaptureEvent` and similar methods are all synchronous because what they do is queue the event in a memory queue. A worker task reads from this queue and sends the event to Sentry asynchronously.

The `IDisposable` returned by the `Init` call serves as a way to make sure events queued up are flushed out. If here are no events queued, calling `Dispose` returned immediately. If not, it'll block for up to [`ShutdownTimeout`](https://github.com/getsentry/sentry-dotnet/blob/eef09a0f51c54310916d0e6a7050cc8c2c100afe/src/Sentry/SentryOptions.cs#L201) which by default is 2 seconds.

In case of an unhandled exception that will crash your app, the SDK will capture the exception and make sure it gets flushed out by disposing the itself. Since the app is about to terminate, it makes sense to do it then. This happens when handling the [`UnhandledException `](https://github.com/getsentry/sentry-dotnet/blob/eef09a0f51c54310916d0e6a7050cc8c2c100afe/src/Sentry/Integrations/AppDomainUnhandledExceptionIntegration.cs#L37) event from `AppDomain`.

If you can't have the `Init` call in a `using` block, you can hold the `IDisposable` it returns and make sure it gets called at the of the execution of your app. Like in ASP.NET it would be the `Application_End `.  On a Winform app it would be `Application.ApplicationExit` or `AppDomain.CurrentDomain.ProcessExit`.

If for some reason you can't keep the reference to the `IDisposable`, you can call [`SentrySdk.Close`](https://github.com/getsentry/sentry-dotnet/blob/eef09a0f51c54310916d0e6a7050cc8c2c100afe/src/Sentry/SentrySdk.cs#L110).

**Comment by ChaosCA** [comment]
Interesting and thank you for clarifying @bruno-garcia 

If what you say is true, shouldn't the code I pasted above work? I don't hold onto the `IDisposable` however the `SentrySdk` should still be configured from the init.

**Comment by bruno-garcia** [comment]
If you call `CaptureEvent` and exit immediately, there will be no time for the worker thread to send event.

In your snippet there's no hold (and call) of the `IDisposable` returned by `Init`, no call to `SenteySdk.Close` and no unhandled exception so I would expect that event not to be sent.

**Comment by ChaosCA** [comment]
Even with a `SentrySdk.Close()` call and waiting >30 minutes nothing is called.

**Comment by bruno-garcia** [comment]
Hi @ChaosCA. Sorry for the late reply but I'm on holiday.
You can use the flag: `Debug` set to `true` to see what's going on.

By default, calling `Close` will block by up to 2 **seconds** if there are messages to be queued up to be sent to Sentry. If, for example, there is only 1 message to be sent, and that takes 500ms, calling `Close` would take only 500ms.

By any chance are you using the `Sentry.Extensions.Logging` package and you project has the name prefixed: `Sentry`? If that's the case, you might have hit [this issue](https://github.com/getsentry/sentry-dotnet/issues/99).

If you can share a small reproducible code I'd be able to debug that for you.

**Comment by ChaosCA** [comment]
Thanks @bruno-garcia you've been really helpful. 

I was able to find the issue, one Nuget package we use requires an older version of Newtonsoft.Json than the version 11 that this package requires. I believe I can fix this on my end by binding either or to the newer or older version using as described here: https://stackoverflow.com/questions/49235726/can-i-load-2-versions-of-newtonsoft-json-at-the-same-time

**Comment by ChaosCA** [comment]
Thank you :)
