### ISSUE TITLE
System.NullReferenceException in /_/src/Sentry.AspNetCore/SentryMiddleware.cs in roughly 1 in 100 requests

### ISSUE THREAD

**Issue by ViMaSter** [getsentry/sentry-dotnet#963]
### Environment
Sentry SaaS (sentry.io)
**Sentry SDK:** .NET 3.3.4
**Framework:** ASP.NET Core 5.0
Deployed to Azure Web Apps

### Steps to Reproduce
This issue only occurs sporadically (1 in 100 requests) and has only occurred 2 days after upgrading to `3.3.4`. I wasn't able to reproduce this issue locally and so far has only occured on our Azure hosted instances.
1. Inside `Program.Main()` we call `webBuilder.UseSentry()` with the generic .NET Host builder ([source for reference](https://gist.github.com/ViMaSter/1a357ee06a750c4ddc893f4a5e0b4679))
2. Inside our Controller we call `SentrySdk.ConfigureScope()` like so:
```cs
public async Task<ActionResult<FullLessonData>> FetchLessonByLessonID(long lessonID)
{
    var (status, lesson) = await _lessonModelGenerator.LessonByID(lessonID, User);
    SentrySdk.ConfigureScope(scope =>
    {
        scope.SetExtra("lessonModelGenerator.responseStatus", status.ToString());
    });
    return status switch
    {
        LessonModelGenerator.ResponseStatus.OK => lesson == null ? Forbid() : Ok(lesson),
        LessonModelGenerator.ResponseStatus.NoAccess => Forbid(),
        LessonModelGenerator.ResponseStatus.NotFound => NotFound(),
        _ => throw new NotImplementedException("LessonModelGenerator.ResponseStatus is not handled")
    };
}
```
3. In roughly 1 in 100 requests, we receive a `System.NullReferenceException` in `  File "/_/src/Sentry.AspNetCore/SentryMiddleware.cs", line 139, col 9, in async Task SentryMiddleware.InvokeAsync(HttpContext context)
` [(The full sentry log + callstack for reference.)](https://github.com/getsentry/sentry-dotnet/files/6396684/98793d3590154ac0a267fe39d3e7dfda.log)

### Expected Result
No exception is thrown during normal operations

### Actual Result
[Raw JSON of the sentry event that captures the exception including callstack](https://github.com/getsentry/sentry-dotnet/files/6396684/98793d3590154ac0a267fe39d3e7dfda.log)

**Comment by bruno-garcia** [comment]
Thanks for the details. Does this happen only if you call `ConfigureScope` and `SetExtra`? Or that was just additional information for context?

The line and column point to the end of the method:

https://github.com/getsentry/sentry-dotnet/blob/d25c97f0e5c77b520e30877444e93a9147afb9cd/src/Sentry.AspNetCore/SentryMiddleware.cs#L139

This makes it hard to debug. 
I suspect this could be due to [TieredCompilation](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation). Would it be possible to rebuild/redeploy without this option?

**Comment by bruno-garcia** [comment]
There's some extra info in there:

```
  "metadata": {
    "function": "Task QueryStringValueProviderFactory.CreateValueProviderAsync(ValueProviderFactoryContext context)",
    "type": "System.NullReferenceException",
    "value": "Object reference not set to an instance of an object."
  },
```

**Comment by ViMaSter** [comment]
> Thanks for the details. Does this happen only if you call `ConfigureScope` and `SetExtra`? Or that was just additional information for context?

So far it has only occurred once and on this specific controller action, which includes these to calls. At the moment I can't say for certain that either the `ConfigureScope()`-call or `SetExtra()`-are the root case, until this happens again on another controller either with or without these specific `SentrySdk.`-calls, sorry. I had added this just for context.

>The line and column point to the end of the method:
> ... 
>This makes it hard to debug.

Looking at the source was my first instinct too and exactly because it's pointing to the end of the scope instead of an explicit call, I've opened this issue. :)

> Interestingly it shows on a metadata field on the event which isn't in the protocol. But seems like that's the culprit. Though I'm not sure why the last line of the Sentry middleware is in the stack trace

The only info related to `System.NullReferenceException`s inside the `QueryStringValueProviderFactory` that I could find, points to accessing `HttpContext` across multiple thread pools. ([1](https://github.com/dotnet/aspnetcore/issues/3219), [2](https://github.com/dotnet/aspnetcore/issues/2806), [3](https://github.com/dotnet/aspnetcore/issues/3321))

(Let me preface this by saying I'm not familiar with the inner workings of the .NET client of Sentry, this is purely guesswork.)  
I am under the impression, that sending the event to the data source happens asynchronously to sending the HTTP response back to the client - that way Sentry doesn't prolong sending the HTTP response. (Please correct me if I'm already wrong here!)  
If that's the case, could this stem from Sentry carrying references to request-related data until after the HTTP request is already fully handled and ASP having already disposed (parts of) the data by the time Sentry is actually trying to access it (i.e. for serializing it to send it to the data source)?

Unrelated to that: I tried `grep`ing through the `getsentry/sentry-dotnet` repository's code and like you mentioned I also couldn't find anything related to the `metadata`-key. I'm back at work when this post is 20 hours old (can't access our Sentry instance over the weekend), I'll see if any other events we've recorded so far contain the `metadata`-key too and see if I can find out what their value might be related to, if it's of any assistance.

Otherwise is there anything else I can do to provide additional info (aside from waiting until this issue occurs again)?

**Comment by ViMaSter** [comment]
Sorry, I forgot about this part:
> I suspect this could be due to [TieredCompilation](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/compilation). Would it be possible to rebuild/redeploy without this option?

Absolutely. I'll see how big of a performance impact his will have on our API and it's build times. If it's in an acceptable range, I'll keep it disabled and see if this mitigates it fully.  
However if we notice this slowing down our response and build times too heavily, I'll be forced to re-enable it. (Besides, judging the success of it is going to be difficult without having a clear repro-case anyway, but I will report back after at least a week of operations with it disabled.)

**Comment by bruno-garcia** [comment]
> I am under the impression, that sending the event to the data source happens asynchronously to sending the HTTP response back to the client - that way Sentry doesn't prolong sending the HTTP response. (Please correct me if I'm already wrong here!)

That's right, calling `Sentry.CaptureException` does only queue the event for submission and doesn't prolong your HTTP response. But creating the Sentry event, including reading the HTTP request data happen on the calling thread. So we're safe in that regard.

What's not going to work is if you're calling something like:
```csharp
// Callling from your controller action:
Task.Run(() => {
  SentrySdk.CaptureException(..);
```
This ^ is going to cause an error while processing the event (it still going to get into Sentry but we'll log an error when trying to read the Request data into the scope (since it'll throw, but the SDK catches such errors).
So in any case, it shouldn't break the way it broken for you.

Are you kicking off work to a background thread from a web request? Through `Thread`, `ThreadPool.QueueQueueUserWorkItem`, `Task.Run`, `Task.Factory.StartNew` or event `Parallel.ForEach` or friends?

> Unrelated to that: I tried greping through the getsentry/sentry-dotnet repository's code and like you mentioned I also couldn't find anything related to the metadata-key. I'm back at work when this post is 20 hours old (can't access our Sentry instance over the weekend), I'll see if any other events we've recorded so far contain the metadata-key too and see if I can find out what their value might be related to, if it's of any assistance.

Must be part of Sentry's ingestion pipeline. Let me ask @jan-auer or @untitaker if they know what that is about.

> Absolutely. I'll see how big of a performance impact his will have on our API and it's build times. If it's in an acceptable range, I'll keep it disabled and see if this mitigates it fully.
However if we notice this slowing down our response and build times too heavily, I'll be forced to re-enable it. (Besides, judging the success of it is going to be difficult without having a clear repro-case anyway, but I will report back after at least a week of operations with it disabled.)

Tiered compilation will only change cold start. The time for the service to start responding requests and the time of the first request. That's because without it, it'll JIT the whole thing with the best performance it can (as it did before this feature was added in .NET Core 3 or something). So unless it's a huge monolith it's likely going to be OK. Particularly if you do hit the service as part of your rollout process (to warm cache and JIT, etc).

Do you have a link to this event in Sentry so I can peek?

**Comment by ViMaSter** [comment]
Sorry for the delayed response again! (Just noticed the 6 hour time difference between us.) I'm also off on vacation from May 8th until May 23rd, so after that the earliest I can get back to you is May 24th, since I'm not able to access any of our tools (including Sentry) during that time; just as a heads-up!

---

> Are you kicking off work to a background thread from a web request? Through Thread, ThreadPool.QueueQueueUserWorkItem, Task.Run, Task.Factory.StartNew or event Parallel.ForEach or friends?

Just double-checked, but it doesn't seem that way: Inside `_lessonModelGenerator.LessonByID()` we're just connecting to a DB via `Microsoft.Data.SqlClient.SqlConnection` and querying it by `await`ing [Dapper](https://github.com/DapperLib/Dapper)'s `QueryAsync()`. That's the only logic omitted from my initial post.

> Must be part of Sentry's ingestion pipeline.

As I mentioned, here's a few samples of some of our other, handled exceptions - they're unrelated to the problem of my original post, just adding them for context.  

I was able to find these these distinct "formats":
https://sentry.io/organizations/sunlab-gmbh/issues/2149889509/events/2874af93c62145e29d564a148271e210/json/
```jsonc
{
    // ...
    "metadata": {
        "title": "The request was rejected with the following error: invalid_grant ; The specified refresh token is..."
    }
    // ...
}
```

https://sentry.io/organizations/sunlab-gmbh/issues/2281257492/events/47dce9ca88b54a488c25464bd68e4470/json/
```jsonc
{
    // ...
    "metadata": {
        "filename": "/src/Services/BillwerkIAPHelper.cs",
        "function": "async Task<Dictionary<string, string>> BillwerkIAPHelper.MissingSubscriptionIDsForApple(Guid userID, string appleIAPReceipt)",
        "type": "System.Net.Http.HttpRequestException",
        "value": "{\"Message\":\"AppleIapReceipt is not a valid base64 string!\"}"
},
    // ...
}
```

https://sentry.io/organizations/sunlab-gmbh/issues/2319991026/events/9ac766469acc4a14b2b8324eea751649/json/
```jsonc
{
    // ...
    "metadata": {
        "type": "System.AggregateException",
        "value": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Resource temporarily unavailable)"
    },
        // ...
}
```

> Do you have a link to this event in Sentry so I can peek?

Sure! https://sentry.io/organizations/sunlab-gmbh/issues/2370002750/events/98793d3590154ac0a267fe39d3e7dfda/?project=5503090/
It's a closed organization, so unless you've got elevated privileges due to being part of the staff, I'll have to ask around to see if I can open it up for you. If you're looking for something in particular, I'll make sure to forward it to you ASAP.

> Tiered compilation will only change cold start. The time for the service to start responding requests and the time of the first request. That's because without it, it'll JIT the whole thing with the best performance it can (as it did before this feature was added in .NET Core 3 or something). So unless it's a huge monolith it's likely going to be OK. Particularly if you do hit the service as part of your rollout process (to warm cache and JIT, etc).

Awesome; our production environment are swapped with our warmed-up staging environment anyway, so a few more seconds for internal development instances is perfectly acceptable. I've disabled it and it's rolling out to our production instance as we speak.
The good news is, the issue hasn't reappeared in the last 5 days; even with Tiered compilation still enabled. However, that will also make it difficult to say if disabling Tiered compilation will make a difference to the underlying issue.

**Comment by jan-auer** [comment]
`metadata` indeed comes from the ingestion pipeline. It is [generated here](https://github.com/getsentry/sentry/blob/ee95a3e4fc14f5eb2386d719926cd92c47c05fa0/src/sentry/event_manager.py#L898-L911) and [written here](https://github.com/getsentry/sentry/blob/ee95a3e4fc14f5eb2386d719926cd92c47c05fa0/src/sentry/event_manager.py#L669-L670). They are used by the Sentry UI to render issue titles among other things. 

They are definitely unrelated to any SDK problems.

**Comment by bruno-garcia** [comment]
Looking at the issue, it include SentryMiddleware's at the bottom of the stack because we add it in the beginning of the pipeline. In order to get errors from any middleware. But from there it goes into `Swagger`, `Authorization`, `Routing` and other middlewares with the offending line being from `CreateValueProviderAsync ` from `Microsoft.AspNetCore.Mvc.Core` but doesn't seem related to Sentry though (I removed the bug label for that reason, for now. We can definitely change this if more hints come in and contradict this assumption).

It doesn't help that PDBs don't seem to be shipped anymore with the .NET Runtime (no line numbers from framework frames are available) and Sentry doesn't fetch these from NuGet's symbol server currently, so we don't known which line threw.

As your links point out this seem to be related to the HttpRequest object getting accessed outside of the transaction which is odd given the stack trace does show the request pipeline in it.

**Comment by ViMaSter** [comment]
Just wanted to give a quick update: Unfortunately the issue has resurfaced on May 20th (the original event happened on April 29th), even with `<TieredCompilation>false</TieredCompilation>` set inside the `.csproj`-file. (I've just now managed to look into this further, please excuse the delay.)

[Here's the raw JSON of the new Sentry event.](https://github.com/getsentry/sentry-dotnet/files/6582514/sentry.963.json.log)

The issue inside the same controller, but on a different action. Sadly the call stack is equally opaque as during the first occurence.
The method in question is equally complex however. We're running a few SQL `SELECT`-statements using Dapper, closing the database connection after that and then transform the data with LINQ to return an `OkObjectResult()`.

In the meantime, I'll re-enable tiered compilation, to see if disabling it it at least reduces the reproducibility. I haven't seen the issue locally still, so aside from this event, I'm afraid I'm still unable to contribute additional details.

**Comment by bruno-garcia** [comment]
By looking at the stacktrace, it just says the it went through the SentryMiddleware:

https://github.com/getsentry/sentry-dotnet/blob/520969006f28698646d9d4c25bdb7789bc2b401a/src/Sentry.AspNetCore/SentryMiddleware.cs#L112

But it goes into the middleware pipeline: `SwaggerMiddleware`->`SwaggerUIMiddleware`->`AuthenticationMiddleware`.. etc and eventually fails on a property (`HasFormContentType`) from `DefaultHttpRequest` in `Microsoft.AspNetCore.Http`.

This error doesn't seem related to the .NET SDK. It just happens that Sentry can capture because it happens on the middleware pipeline and Sentry adds itself to the begining of it and captures any errors that bubble through it.

**Comment by SimonCropp** [comment]
@bruno-garcia so based on that, this should be closed as not related to sentry?
